module.exports = () => ({
  code: 10000,
  msg: 'ok',
  data: {
    banners: [
      {
        id: '407ed7e5f6d81e608813f092e14a26d2',
        tips: '618宽带活动',
        imgUrl: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_20220616175328_product_edfde3b2.png',
        targetUrl:
          'https://gkzx.jujienet.com/broadband-web/activity/discountList?activityId=1ee20f842cf59c1b651bdaa625beebd9&sourceOrigin=618B&enter=616',
      },
    ],
    area: { cityCode: '330100', chineseName: '杭州市', provinceCode: '33' },
    navList: [
      {
        navIcon: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/icon/icon_20220621174244_icon_811475e9.png',
        navTagIcon: '',
        navUrl: 'https://wx.10086.cn/website/businessPlatform/home/broadband/process',
        urlType: '2',
        navName: '进度查询',
        navTips: '进度查询',
      },
      {
        navIcon: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/icon/icon_20220621174503_icon_d3a86d8b.png',
        navTagIcon: '',
        navUrl: 'https://wx.10086.cn/website/page/broadBand/index?cscd=367B997DD97FB7C3F04248FC6F72934A\t',
        urlType: '1',
        navName: '移动账号',
        navTips: '移动账号',
      },
    ],
    active: null,
    activeGridView: [
      {
        path: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_20220622165633_product_2550f306.png',
        title: '宽带缴费',
        subTitle: '官方保障',
        content: null,
        linkUrl:
          'alipays://platformapi/startapp?appId=2021001164644764&appClearTop=false&startMultApp=YES&page=%2Fpages%2Findex%2Findex%3FchInfo%3Dkuandaizhongxin',
        button: null,
        id: '8bf97aecc259828f6e7f153730305cff',
      },
      {
        path: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_20220622165509_product_61e4743c.png',
        title: '宽带续约',
        subTitle: '快速办理',
        content: null,
        linkUrl: 'https://gkzx.jujienet.com/broadband-web/bbRenewal/renewalInit',
        button: null,
        id: '1e61f921d7abc77a5317af8b6b66536b',
      },
      {
        path: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_20220620185438_product_c820c4dc.png',
        title: '宽带提速',
        subTitle: '一键升级',
        content: null,
        linkUrl: 'https://gkzx.jujienet.com/broadband-web/speedUp/index\t',
        button: null,
        id: '38fb2fd71e04acc5415415972a0e7d67',
      },
    ],
    find: {
      more: false,
      title: '发现',
      url: '',
      findList: [
        {
          adPic: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_20220316103909_product_e06f9807.png',
          adText: '加享8大权益',
          adTitle: '首月0.01元购',
          adUrl: 'https://benefit.jujienet.com/benefit/index/10171',
          id: 'f048488235cb8d73e140fdbad3d2ff68',
          priority: '3',
          urlType: '2',
        },
      ],
    },
    benefit: {
      more: false,
      title: '发现权益',
      url: '',
      findList: [
        {
          adPic: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/adv/adv_2113_product_29877191.png',
          adText: null,
          adTitle: '移动5G流量包',
          adUrl: ' https://ll.qiangka.com/cmcccl5g?no=ZcknBGMU#max',
          id: '0c44f43a8b98110a75f5c7b0ea80737f',
          priority: '3',
          urlType: '2',
        },
      ],
    },
    productList: [
      {
        moduleId: 27,
        more: true,
        title: '优选宽带',
        moduleKey: 'OPTIMIZING_BROADBAND',
        tags: '优选宽带',
        url: null,
        type: 1,
        productList: [
          {
            id: 143682063,
            title: '100M',
            label: '12个月',
            titleType: '0',
            tips: '每天不到2元',
            tipsother: null,
            price: 699.0,
            goodsNo: 'ba85101e11dd49c39780795f0a48ec11',
            oldprice: null,
            changes: null,
            monthprice: 58.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '0',
            displaytitle: '电信100M宽带新装',
            spesDesc: { bandwidth: '100M', contractPeriod: '12个月', widetype: 'ADSL' },
            goodsLabelDesc: ['', '', '', '每天不到2元'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143682064,
            title: '200M',
            label: '12个月',
            titleType: '2',
            tips: '装成送50元',
            tipsother: null,
            price: 360.0,
            goodsNo: 'b35e19dec33542538d742c95155a6080',
            oldprice: null,
            changes: null,
            monthprice: 30.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '2',
            displaytitle: '移动200M宽带新装',
            spesDesc: { bandwidth: '200M', contractPeriod: '12个月', widetype: '光纤' },
            goodsLabelDesc: ['', '', '免费1台ITV', '装成送50元'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143682065,
            title: '300M',
            label: '1个月',
            titleType: '1',
            tips: '自由无合约',
            tipsother: null,
            price: 49.0,
            goodsNo: '953fa1e29c4a4669a31126a140483efd',
            oldprice: null,
            changes: null,
            monthprice: 49.0,
            url: null,
            h5Url: null,
            type: 5,
            picUrl: null,
            operator: '1',
            displaytitle: '联通300M宽带融合',
            spesDesc: { bandwidth: '300M', contractPeriod: '1个月', widetype: '光纤' },
            goodsLabelDesc: ['49元即享', '', '', '自由无合约'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143682066,
            title: '300M',
            label: '1个月',
            titleType: '1',
            tips: '30GB/月',
            tipsother: null,
            price: 79.0,
            goodsNo: '3cb459b309f54b66bce0c4365ff657e0',
            oldprice: null,
            changes: null,
            monthprice: 79.0,
            url: null,
            h5Url: null,
            type: 5,
            picUrl: null,
            operator: '1',
            displaytitle: '联通300M宽带融合',
            spesDesc: { bandwidth: '300M', contractPeriod: '1个月', widetype: '光纤' },
            goodsLabelDesc: ['', '', '', '30GB/月'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143682067,
            title: '200M',
            label: '12个月',
            titleType: '1',
            tips: '低至1天1元',
            tipsother: null,
            price: 360.0,
            goodsNo: 'f2a9652d225244c4ac1a5d7e151777b3',
            oldprice: null,
            changes: null,
            monthprice: 30.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '1',
            displaytitle: '联通200M宽带新装',
            spesDesc: { bandwidth: '200M', contractPeriod: '12个月', widetype: '光纤' },
            goodsLabelDesc: ['安装费100元', '', '', '低至1天1元'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
        ],
      },
      {
        moduleId: 29,
        more: true,
        title: '每日推荐',
        moduleKey: 'DAILY_SPECIAL',
        tags: '100M-200M',
        url: null,
        type: 3,
        productList: [
          {
            id: 143694516,
            title: '100M',
            label: '12个月',
            titleType: '4',
            tips: '新装特惠',
            tipsother: null,
            price: 199.0,
            goodsNo: '73542df812554f83b57a713d8beaaf8a',
            oldprice: null,
            changes: null,
            monthprice: 17.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '4',
            displaytitle: '华数100M宽带新装',
            spesDesc: { bandwidth: '100M', contractPeriod: '12个月', widetype: 'ADSL' },
            goodsLabelDesc: ['', '', '', '新装特惠'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143694517,
            title: '200M',
            label: '12个月',
            titleType: '4',
            tips: '新装特惠',
            tipsother: null,
            price: 299.0,
            goodsNo: '3fd1eb4ae2ad49b788a5577d82e5812f',
            oldprice: null,
            changes: null,
            monthprice: 25.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '4',
            displaytitle: '华数200M宽带新装',
            spesDesc: { bandwidth: '200M', contractPeriod: '12个月', widetype: 'ADSL' },
            goodsLabelDesc: ['0门槛无捆绑', '', '', '新装特惠'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
          {
            id: 143694518,
            title: '100M',
            label: '3个月',
            titleType: '4',
            tips: '0门槛 无捆绑',
            tipsother: null,
            price: 198.0,
            goodsNo: '37cdd9230d624b8f8f96c8233410bfd3',
            oldprice: null,
            changes: null,
            monthprice: 66.0,
            url: null,
            h5Url: null,
            type: 1,
            picUrl: null,
            operator: '4',
            displaytitle: '100M3个月198元',
            spesDesc: { bandwidth: '100M', contractPeriod: '3个月', widetype: 'ADSL' },
            goodsLabelDesc: ['', '', '', '0门槛 无捆绑'],
            goodsSort: 99,
            cornerIcon: null,
            cornerIconName: null,
            specialMark: null,
            showPrice: null,
          },
        ],
      },
    ],
    liteVipList: null,
    oaoList: [
      {
        id: 0,
        title: '5G-199融合套餐',
        label: null,
        titleType: '1',
        tips: null,
        tipsother: null,
        price: 0.0,
        goodsNo: '52022061510266829',
        oldprice: null,
        changes: null,
        monthprice: null,
        url: null,
        h5Url: null,
        type: 5,
        picUrl: null,
        operator: '0',
        displaytitle: '5G-199融合套餐',
        spesDesc: { bandwidth: '1000M' },
        goodsLabelDesc: ['高速宽带线上一键办理', '', '', ''],
        goodsSort: 0,
        cornerIcon: 'https://broadband.oss-cn-shanghai.aliyuncs.com/staticPic/111.png',
        cornerIconName: null,
        specialMark: 'oao',
        showPrice: '199元/月',
      },
    ],
  },
});
