module.exports = () => ({
  code: 10000,
  msg: 'ok',
  data: {
    status: 0,
    msg: 'ok',
    netHalls: [
      {
        yytName: '中国电信（杭州竞舟支局营业厅）',
        yytCode: '3301063145228',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州古荡支局营业厅）',
        yytCode: '3301063145227',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州益乐支局营业厅)',
        yytCode: '3301063144991',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州黄龙支局营业厅）',
        yytCode: '3301063145355',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州古墩支局营业厅)',
        yytCode: '3301061806406',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州崇仁支局营业厅）',
        yytCode: '3301063143809',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州翠苑支局营业厅）',
        yytCode: '3301063143815',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州灵隐支局营业厅）',
        yytCode: '3301063143812',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州古翠支局营业厅）',
        yytCode: '3301063145243',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
      {
        yytName: '中国电信（杭州天目支局营业厅)',
        yytCode: '3301061775228',
        provName: null,
        provCode: null,
        latnName: null,
        latnCode: null,
        areaName: null,
        areaCode: null,
        provinceName: null,
        provinceCode: null,
        cityName: null,
        cityCode: null,
        countryName: null,
        countryCode: null,
      },
    ],
  },
});
