module.exports = () => ({
  code: 10000,
  msg: 'ok',
  data: {
    devingidine: true,
    operator: null,
    goodList: [
      {
        id: '04ef95d5ef684a12967e0b2be9b58f0a',
        goodsNo: '52022061510266829',
        title: '5G-199融合套餐',
        subtitle: null,
        displaytitle: null,
        listviewPic: null,
        previewPic: null,
        goodsGraph: 'https://www.189.cn/images/2022/4/8/00000000F56D7F62164A4CD1B42321D31F764610.jpg',
        activityRulesPic: null,
        spesDesc: { bandwidth: '1000M', hasSecondaryCard: true, secondaryCardNum: 2 },
        goodsType: '5',
        price: 0.0,
        originalPrice: null,
        stock: null,
        productOperator: '0',
        priority: null,
        viewCount: null,
        buyCount: null,
        businessType: null,
        serviceNo: 10001206,
        goodsStatus: null,
        delFlag: null,
        isHot: null,
        isAgreement: null,
        isHide: null,
        goodsLabelDesc: ['高速宽带线上一键办理', '', '', ''],
        goodsDescription: null,
        operatorLogo: null,
        typeSymbol: null,
        averagePrice: null,
        operatorCode: null,
        agreementNames: null,
        cornerIcon: null,
        cornerIconName: null,
        payment: null,
        prepayAmount: null,
        splendMinCount: null,
        splendMaxCount: null,
        splendSelectCount: null,
        child: null,
        mailWays: null,
        goodsTipsResp: null,
        additionalName: null,
        isAddition: null,
        isTips: null,
        thirdActivitiesId: null,
        thirdDeviceId: '8330100',
        goodsTrdNo: '00000000DC1FAFCD5BD208DFE053AA1410AC5F3D',
        goodsAdditionals: null,
        additionalInfo: null,
        h5Url: null,
        goodsGraphList: null,
        headImg: null,
        submitMarketingImg: null,
        productPro: '33',
        productCity: '330100',
        isAuth: null,
        thirdGoodsType: null,
        bandwidthNum: null,
        specialMark: 'oao',
        showPrice: '199元/月',
      },
    ],
  },
});
