module.exports = () => ({
  code: 10000,
  msg: 'ok',
  data: {
    status: 1,
    msg: '查询成功',
    broadbandAccount: 'a111178563',
    latnId: null,
    broadbandName: 'e9视讯宽带(优化版)-6M 1299元/年(4M宽带拨号+2MITV)(F)',
    installAddress: '***01室',
    oweAmount: 0,
    expirationDate: 1717171199000,
    payMode: null,
    isNoGoods: true,
    code: '0000',
    operatorCode: '0',
    operatorName: '电信',
    goodsInfoList: [
      {
        price: 1299.0,
        title: 'e9视讯宽带(优化版)-6M 1299元/年(4M宽带拨号+2MITV)(F)(包期促销)(停售仅允许续包)',
        goodsTrdNo: '200000072',
        operatorLogo: '/images/w3.png',
        reserveFour: null,
        reserveSix: null,
        productType: '1',
        broadbandRate: '100M',
        contractPeriod: '12',
        selIsChange: null,
        discntCode: null,
      },
    ],
    accountType: '2',
    serviceNo: 10001026,
    reserveOne: null,
    reserveTwo: null,
    reserveThree: null,
    reserveFour: null,
    reserveFive: null,
    reserveSix: null,
    reserveSeven: null,
    isTicket: '1',
    custName: '刘*',
    hasGetAmount: null,
    securityCode: null,
    fail: false,
    success: true,
    owe: false,
  },
});
