const address = require('address');
const { port } = require('../../config');

const getFileByEnv = (key) => {
  const fileName = `${key}.png`;
  const url = `http://${address.ip()}:${port}/static/benefit/${fileName}`;
  return url;
};

module.exports = (req) => {
  return {
    "code": 200,
    "data": {
        "dataList": [],
        "dataMap": {
            "buttonImg": "",
            "categoryPackageList": [],
            "data": null,
            "errorToast": {
                "authErrorToast": "",
                "orderErrorToast": "",
                "sendShortMessageErrorToast": "",
                "tradeErrorToast": ""
            },
            "frontExtInfo": {
                "flowNum": "5GB",
                "enableType": "订购立即生效",
                "enableTime": "当月有效",
                "flowName": "全国流量",
                "tips": "",
                "contractPeriod": "无",
                "exit": "退订次月生效",
                "subTitle": "19元/月",
                "mainTitle": "电信PLUS会员月包",
                "renewDesc": "自动续订",
                "detail": "一、资费说明\r\n1.套餐费：19元/月，首月一次性收取费用，每月月初一次性收取费用。有效期：长期。不退订次月起自动续订。协议期内仅限订购一次，协议期内用户可每月享受权益包内特权一次。\r\n2.权益内容：5G流量+影音/视频会员N选1。\r\n3.权益领取路径：翼支付APP—权益专区。\r\n二、业务规则\r\n1.生效规则：订购立即生效。\r\n2.重复订购规则：同一号码不可重复订购。\r\n3.到期处理规则：双方无异议次月自动续订。\r\n4.退订规则：合约生效期内退订该合约，需要拨打中国电信10000客服电话或中国电信线下营业厅办理解约，退订次月生效。若用户当月退订，自退订之日起当月内仍可领取权益。\r\n5.权益领取规则：仅限办理号码领取，每月5日起领取（用户号码状态为正常），当月未按时领取或欠费等原因未领取视作自动放弃，后续不支持补领。权益内容可能有所调整，具体以领取页面实际显示为准，权益有效期以领取页面说明为准。若办理号码已订购相关权益，领取权益后，有效期将在原有效期上自动叠加。\r\n6.权益发放规则：权益发放会有延迟，领取后请等待几分钟后再查询。\r\n7.流量使用规则：流量月底自动清零，主副卡不可共享流量，副卡可单独订购。",
                "crossMonth": "0",
                "flowPrice": "19元"
            },
            "headImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/headImg788a0d2b76334bd58d536e6b9d9e2656_20250710110048.png",
            "holderImg": "",
            "llgAccount": "",
            "marketingTitle": "特惠流量",
            "msg": "获取成功",
            "operatorCode": 0,
            "oppoServiceTypeNo": "",
            "provinceId": 0,
            "ruleImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/ruleImgd25eb8b058604eeba97ffbf4cfe28d6a_20250710110056.jpg",
            "skuItem": {
                "agreementName": "隐私协议",
                "agreementNameSuffix": "及页面规则",
                "agreementShowLimit": 1,
                "buttonImg": "",
                "buttonText": "立即办理",
                "category": "",
                "categoryId": 1,
                "channelBrand": "",
                "channelProductMainTitle": "",
                "channelProductSubTitle": "",
                "cnId": 10034,
                "confInfo": null,
                "defaultChoose": 2,
                "detailImgs": [
                    // "https://chaac.oss-cn-hangzhou.aliyuncs.com/ruleImgd25eb8b058604eeba97ffbf4cfe28d6a_20250710110056.jpg"
                ],
                "dialType": 0,
                "enterLocation": "",
                "errorToast": {
                    "authErrorToast": "",
                    "orderErrorToast": "",
                    "sendShortMessageErrorToast": "",
                    "tradeErrorToast": ""
                },
                "externalLinkUrl": "",
                "extraConfig": {
                    "autoSendSmsCode": false,
                    "autoSubmitOrder": false,
                    "bulletComment": false
                },
                "failurePrompt": "提交异常，请重试",
                "frontExtInfo": {
                    "flowNum": "5GB",
                    "enableType": "订购立即生效",
                    "enableTime": "当月有效",
                    "flowName": "全国流量",
                    "tips": "",
                    "contractPeriod": "无",
                    "exit": "退订次月生效",
                    "subTitle": "19元/月",
                    "mainTitle": "电信PLUS会员月包",
                    "renewDesc": "自动续订",
                    "detail": "业务规则详情\r\n1.业务介绍\r\n随心用轻享优惠包是由江苏电信联合省内优质商户打造的本地化生活消费类权益业务。随心用轻享优惠包业务包含每月6元*2张随心用消费券（微信立减金或云闪付代金券可任选1项领取），以及每月2GB国内通用流量。\r\n随心用消费券权益涵盖了商超便利、餐饮美食、休闲娱乐、生活服务等众多本地生活消费领域，旨在为用户提供品质化的本地生活消费优惠体验及服务。\r\n2.优惠资费\r\n10元/月\r\n3.订购规则<REDBOLD>\r\n1)订购成功立即生效（具体生效时间以短信通知为准），首月功能费全额计扣，流量全额提供，有效期至当月月底。次月起每月自动续订，费用月初一次性收取。<REDBOLDEND>\r\n2)业务有效期2年，如双方在有效期届满前30日未提出异议，有效期自动续展，每次续展2年。\r\n3)退订次月生效，退订当月正常收取整月月费。如不再需要此业务，用户需主动退订，退订可前往电信营业厅门店或拨打10000咨询。<REDBOLD>\r\n4)有效期内支持重复订购，每个号码12个月限订购5次。 注：本页面每个号码仅支持订购1次，如需再次订购可前往其他渠道办理（如线下营业厅）。\r\n5)时长型套餐、1元包天、不支持办理流量包的互联网卡等套餐的用户不可办理。<REDBOLDEND>\r\n6)订购期间如因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等，中国电信有权提前30天通过短信、用户电话或公告的方式通知用户终止本业务。\r\n7)本业务所含涉及功能为中国电信联合合作方提供，若合作关系发生变化，中国电信有权对相关内容进行调整或停止提供。若用户不同意调整，可申请退订本业务。\r\n4.随心用消费券权益领取规则\r\n1)订购用户每月可领取6元*2张随心用消费券。\r\n2)随心用消费券包含微信立减金及云闪付代金券两种形式，用户可根据使用需求每月任选1项领取。\r\n3)订购首月随心用消费券权益领取时间为自订购成功之日起30天内，次月起每月领取时间为当月1日5:00至当月最后一日23:59。\r\n4)随心用消费券领取方式：\r\n使用已订购业务手机号码，\r\n登录“118114聪明生活”微信小程序，前往“我的-我的权益”页面领取。\r\n或登录“天翼生活”app，前往“我的-待领权益”页面领取。\r\n5)已订购业务手机号码在非正常状态下（如欠费停机、停机保号、销户等）无法领取随心用消费券。\r\n6)当月随心用消费券超期未领视为自动放弃处理，权益自动失效。\r\n5.随心用消费券使用说明\r\n1)微信立减金\r\n微信立减金领取成功后，可通过微信app“我-卡包-券和礼品卡”页面查看到账情况及使用。\r\n微信立减金领取成功后30天内有效，到期未使用自动失效。\r\n领取页面全部商户列表，选择【微信支付专区】可查看微信立减金可用券商户。\r\n前往商户门店使用微信支付消费，订单金额大于立减金面额0.01元即可自动抵扣使用，单笔订单限使用1张。\r\n微信立减金一经领用，不退现、不找零，不可转他人使用，使用后若发生退款将不再返还。<REDBOLD>\r\n随心用微信立减金优先级使用规则为微信端统一配置要求，具体以微信端实际抵扣情况为准，如有疑问可联系微信客服。<REDBOLDEND>\r\n2)云闪付代金券\r\n云闪付代金券领取成功后，可使用业务订购手机号登录云闪付app“我的-优惠券”页面查看到账情况及使用。\r\n云闪付代金券领取成功后30天内有效，到期未使用自动失效。\r\n领取页面全部商户列表，选择【云闪付支付专区】可查看云闪付代金券可用券商户。\r\n前往商户门店使用云闪付支付消费，订单金额大于代金券面额0.01元即可自动抵扣使用，单笔订单限使用1张。\r\n云闪付代金券一经领用，不退现、不找零，不可转他人使用，使用后若发生退款将不再返还。\r\n6.流量发放及使用规则\r\n1)订购成功后首月流量立即到账，次月起每月1号流量自动充值到账。\r\n2)包内流量为国内通用流量，可用于中国电信移动通信网络，仅限在中国大陆境内（不含港澳台地区）使用，不含WLAN（Wi-Fi）上网。\r\n3)包内流量仅限业务订购号码单独使用，不可与其他号码共享，当月剩余流量自动清零，不可结转至次月。\r\n4)提速规则：\r\n本业务不具备提速功能，流量包使用速率与主套餐速率保持一致。\r\n对于达量降速套餐用户订购本业务，本业务所含流量不纳入套餐的达量降速阈值，即主套餐达量降速流量阈值与本业务流量分别独立计算。<REDBOLD>\r\n5)流量包抵扣顺序：优先于套内流量使用。<REDBOLDEND>\r\n7.特别说明\r\n1)本业务所涉及的各项权益，其相关功能系中国电信联合合作方提供，若在业务有效期内、外出现中国电信联合合作方的平台变更、技术升级、产品迭代或合作关系变化等情况，中国电信可以对相关业务内容、功能、可选权益等进行调整或优化升级，以便为用户提供更好的服务。\r\n2)页面可用券门店仅供参考，具体以门店实际营业状态为准。如遇商户门店经营状态变更(如停业、歇业等)导致无法用券的情况，您可就近前往其他可用券门店使用随心用消费券，或联系客服处理。<REDBOLD>\r\n3)如有其他相关问题，可拨打客服热线118114-4-5（拨打客服热线正常收取通话费用）。<REDBOLDEND>",
                    "crossMonth": "0",
                    "flowPrice": "19元"
                },
                "headerImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/headImg788a0d2b76334bd58d536e6b9d9e2656_20250710110048.png",
                "iconImg": "",
                "isReadOnly": 0,
                "isvTitle": "电信PLUS会员月包19元/月",
                "itemId": 105270,
                "listImg": "",
                "logoImg": "",
                "marketingSkuTip": null,
                "marketingSkuTitle": "特惠流量1122",
                "packageItemGroupId": 0,
                "packageItemGroupName": "",
                "payChannelList": [
                    {
                        "browserType": "",
                        "channelGroup": "",
                        "cnId": 10034,
                        "cnName": "聚合H5",
                        "createTime": "2022-11-01 09:44:23",
                        "dateParams": null,
                        "delFlag": false,
                        "extendData": {},
                        "iconImg": "",
                        "id": 94,
                        "isAsc": "",
                        "orderByColumn": "",
                        "payType": 0,
                        "searchValue": "",
                        "showName": "话费支付",
                        "timeParams": null,
                        "updateTime": "2024-12-25 10:40:24"
                    }
                ],
                "payType": 0,
                "pluginBackgroundImg": "",
                "pluginProductImg": "",
                "pocTitle": "",
                "pocTitleTwo": "",
                "price": 19.00,
                "productAttributes": 19,
                "productAttributesName": "充流量",
                "productEntryId": 27,
                "productEntryName": "权益组合包",
                "promoteScore": 0.0,
                "ranks": 1,
                "servicePhoneType": 0,
                "skuId": 12811,
                "skuImg": "",
                "skuProps": {
                    "合约": "1"
                },
                "skuUserAgreements": [
                    {
                        "agreement": "",
                        "agreementName": "隐私协议",
                        "agreementNameSuffix": "及页面规则",
                        "cnId": 0,
                        "createTime": null,
                        "dateParams": null,
                        "defaultChoose": 2,
                        "delFlag": false,
                        "enable": false,
                        "enterId": 0,
                        "extendData": {},
                        "id": 11355,
                        "isAsc": "",
                        "orderByColumn": "",
                        "searchValue": "",
                        "showLimit": 0,
                        "skuId": 0,
                        "templateType": 0,
                        "timeParams": null,
                        "updateTime": null
                    },
                    {
                        "agreement": "",
                        "agreementName": "活动规则",
                        "agreementNameSuffix": "及页面规则",
                        "cnId": 0,
                        "createTime": null,
                        "dateParams": null,
                        "defaultChoose": 2,
                        "delFlag": false,
                        "enable": false,
                        "enterId": 0,
                        "extendData": {},
                        "id": 11356,
                        "isAsc": "",
                        "orderByColumn": "",
                        "searchValue": "",
                        "showLimit": 0,
                        "skuId": 0,
                        "templateType": 0,
                        "timeParams": null,
                        "updateTime": null
                    }
                ],
                "submitOrderLinkConfigLinkType": 0,
                "submitOrderLinkConfigLinkUrl": "",
                "submitOrderLinkConfigWindowText": "",
                "supplierServicePhone": "95106",
                "tabId": 1,
                "taobaoProductId": "",
                "taobaoProducts": [],
                "templateType": 0,
                "tip": "",
                "tipTemplate": null,
                "title": "电信-集团电信PLUS会员月包19元/月（翼支付-山西）（5GB流量+影音/视频会员N选1）"
            },
            "skuItemList": [
                {
                    "agreementName": "隐私协议",
                    "agreementNameSuffix": "及页面规则",
                    "agreementShowLimit": 1,
                    "buttonImg": "",
                    "buttonText": "立即办理",
                    "category": "",
                    "categoryId": 1,
                    "channelBrand": "",
                    "channelProductMainTitle": "",
                    "channelProductSubTitle": "",
                    "cnId": 10034,
                    "confInfo": null,
                    "defaultChoose": 2,
                    "detailImgs": [
                        // "https://chaac.oss-cn-hangzhou.aliyuncs.com/ruleImgd25eb8b058604eeba97ffbf4cfe28d6a_20250710110056.jpg"
                    ],
                    "dialType": 0,
                    "enterLocation": "",
                    "errorToast": {
                        "authErrorToast": "",
                        "orderErrorToast": "",
                        "sendShortMessageErrorToast": "",
                        "tradeErrorToast": ""
                    },
                    "externalLinkUrl": "",
                    "extraConfig": {
                        "autoSendSmsCode": false,
                        "autoSubmitOrder": false,
                        "bulletComment": false
                    },
                    "failurePrompt": "提交异常，请重试",
                    "frontExtInfo": {
                        "flowNum": "5GB",
                        "enableType": "订购立即生效",
                        "enableTime": "当月有效",
                        "flowName": "全国流量",
                        "tips": "",
                        "contractPeriod": "无",
                        "exit": "退订次月生效",
                        "subTitle": "19元/月",
                        "mainTitle": "电信PLUS会员月包",
                        "renewDesc": "自动续订",
                        "detail": "业务规则详情\r\n1.业务介绍\r\n随心用轻享优惠包是由江苏电信联合省内优质商户打造的本地化生活消费类权益业务。随心用轻享优惠包业务包含每月6元*2张随心用消费券（微信立减金或云闪付代金券可任选1项领取），以及每月2GB国内通用流量。\r\n随心用消费券权益涵盖了商超便利、餐饮美食、休闲娱乐、生活服务等众多本地生活消费领域，旨在为用户提供品质化的本地生活消费优惠体验及服务。\r\n2.优惠资费\r\n10元/月\r\n3.订购规则\r\n1)<REDBOLD>订购成功立即生效（具体生效时间以短信通知为准），首月功能费全额计扣，流量全额提供，有效期至当月月底。次月起每月自动续订，费用月初一次性收取。<REDBOLDEND>\r\n2)业务有效期2年，如双方在有效期届满前30日未提出异议，有效期自动续展，每次续展2年。\r\n3)退订次月生效，退订当月正常收取整月月费。如不再需要此业务，用户需主动退订，退订可前往电信营业厅门店或拨打10000咨询。\r\n4)<REDBOLD>有效期内支持重复订购，每个号码12个月限订购5次。 注：本页面每个号码仅支持订购1次，如需再次订购可前往其他渠道办理（如线下营业厅）。\r\n5)时长型套餐、1元包天、不支持办理流量包的互联网卡等套餐的用户不可办理。<REDBOLDEND>\r\n6)订购期间如因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等，中国电信有权提前30天通过短信、用户电话或公告的方式通知用户终止本业务。\r\n7)本业务所含涉及功能为中国电信联合合作方提供，若合作关系发生变化，中国电信有权对相关内容进行调整或停止提供。若用户不同意调整，可申请退订本业务。\r\n4.随心用消费券权益领取规则\r\n1)订购用户每月可领取6元*2张随心用消费券。\r\n2)随心用消费券包含微信立减金及云闪付代金券两种形式，用户可根据使用需求每月任选1项领取。\r\n3)订购首月随心用消费券权益领取时间为自订购成功之日起30天内，次月起每月领取时间为当月1日5:00至当月最后一日23:59。\r\n4)随心用消费券领取方式：\r\n使用已订购业务手机号码，\r\n登录“118114聪明生活”微信小程序，前往“我的-我的权益”页面领取。\r\n或登录“天翼生活”app，前往“我的-待领权益”页面领取。\r\n5)已订购业务手机号码在非正常状态下（如欠费停机、停机保号、销户等）无法领取随心用消费券。\r\n6)当月随心用消费券超期未领视为自动放弃处理，权益自动失效。\r\n5.随心用消费券使用说明\r\n1)微信立减金\r\n微信立减金领取成功后，可通过微信app“我-卡包-券和礼品卡”页面查看到账情况及使用。\r\n微信立减金领取成功后30天内有效，到期未使用自动失效。\r\n领取页面全部商户列表，选择【微信支付专区】可查看微信立减金可用券商户。\r\n前往商户门店使用微信支付消费，订单金额大于立减金面额0.01元即可自动抵扣使用，单笔订单限使用1张。\r\n微信立减金一经领用，不退现、不找零，不可转他人使用，使用后若发生退款将不再返还。\r\n<REDBOLD>随心用微信立减金优先级使用规则为微信端统一配置要求，具体以微信端实际抵扣情况为准，如有疑问可联系微信客服。<REDBOLDEND>\r\n2)云闪付代金券\r\n云闪付代金券领取成功后，可使用业务订购手机号登录云闪付app“我的-优惠券”页面查看到账情况及使用。\r\n云闪付代金券领取成功后30天内有效，到期未使用自动失效。\r\n领取页面全部商户列表，选择【云闪付支付专区】可查看云闪付代金券可用券商户。\r\n前往商户门店使用云闪付支付消费，订单金额大于代金券面额0.01元即可自动抵扣使用，单笔订单限使用1张。\r\n云闪付代金券一经领用，不退现、不找零，不可转他人使用，使用后若发生退款将不再返还。\r\n6.流量发放及使用规则\r\n1)订购成功后首月流量立即到账，次月起每月1号流量自动充值到账。\r\n2)包内流量为国内通用流量，可用于中国电信移动通信网络，仅限在中国大陆境内（不含港澳台地区）使用，不含WLAN（Wi-Fi）上网。\r\n3)包内流量仅限业务订购号码单独使用，不可与其他号码共享，当月剩余流量自动清零，不可结转至次月。\r\n4)提速规则：\r\n本业务不具备提速功能，流量包使用速率与主套餐速率保持一致。\r\n对于达量降速套餐用户订购本业务，本业务所含流量不纳入套餐的达量降速阈值，即主套餐达量降速流量阈值与本业务流量分别独立计算。\r\n5)<REDBOLD>流量包抵扣顺序：优先于套内流量使用。<REDBOLDEND>\r\n7.特别说明\r\n1)本业务所涉及的各项权益，其相关功能系中国电信联合合作方提供，若在业务有效期内、外出现中国电信联合合作方的平台变更、技术升级、产品迭代或合作关系变化等情况，中国电信可以对相关业务内容、功能、可选权益等进行调整或优化升级，以便为用户提供更好的服务。\r\n2)页面可用券门店仅供参考，具体以门店实际营业状态为准。如遇商户门店经营状态变更(如停业、歇业等)导致无法用券的情况，您可就近前往其他可用券门店使用随心用消费券，或联系客服处理。\r\n3)<REDBOLD>如有其他相关问题，可拨打客服热线118114-4-5（拨打客服热线正常收取通话费用）。<REDBOLDEND>",
                        "crossMonth": "0",
                        "flowPrice": "19元"
                    },
                    "headerImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/headImg788a0d2b76334bd58d536e6b9d9e2656_20250710110048.png",
                    "iconImg": "",
                    "isReadOnly": 0,
                    "isvTitle": "电信PLUS会员月包19元/月",
                    "itemId": 105270,
                    "listImg": "",
                    "logoImg": "",
                    "marketingSkuTip": null,
                    "marketingSkuTitle": "特惠流量1122",
                    "packageItemGroupId": 0,
                    "packageItemGroupName": "",
                    "payChannelList": [
                        {
                            "browserType": "",
                            "channelGroup": "",
                            "cnId": 10034,
                            "cnName": "聚合H5",
                            "createTime": "2022-11-01 09:44:23",
                            "dateParams": null,
                            "delFlag": false,
                            "extendData": {},
                            "iconImg": "",
                            "id": 94,
                            "isAsc": "",
                            "orderByColumn": "",
                            "payType": 0,
                            "searchValue": "",
                            "showName": "话费支付",
                            "timeParams": null,
                            "updateTime": "2024-12-25 10:40:24"
                        }
                    ],
                    "payType": 0,
                    "pluginBackgroundImg": "",
                    "pluginProductImg": "",
                    "pocTitle": "",
                    "pocTitleTwo": "",
                    "price": 19.00,
                    "productAttributes": 19,
                    "productAttributesName": "充流量",
                    "productEntryId": 27,
                    "productEntryName": "权益组合包",
                    "promoteScore": 0.0,
                    "ranks": 1,
                    "servicePhoneType": 0,
                    "skuId": 12811,
                    "skuImg": "",
                    "skuProps": {
                        "合约": "1"
                    },
                    "skuUserAgreements": [
                        {
                            "agreement": "",
                            "agreementName": "隐私协议",
                            "agreementNameSuffix": "及页面规则",
                            "cnId": 0,
                            "createTime": null,
                            "dateParams": null,
                            "defaultChoose": 2,
                            "delFlag": false,
                            "enable": false,
                            "enterId": 0,
                            "extendData": {},
                            "id": 11355,
                            "isAsc": "",
                            "orderByColumn": "",
                            "searchValue": "",
                            "showLimit": 0,
                            "skuId": 0,
                            "templateType": 0,
                            "timeParams": null,
                            "updateTime": null
                        },
                        {
                            "agreement": "",
                            "agreementName": "活动规则",
                            "agreementNameSuffix": "及页面规则",
                            "cnId": 0,
                            "createTime": null,
                            "dateParams": null,
                            "defaultChoose": 2,
                            "delFlag": false,
                            "enable": false,
                            "enterId": 0,
                            "extendData": {},
                            "id": 11356,
                            "isAsc": "",
                            "orderByColumn": "",
                            "searchValue": "",
                            "showLimit": 0,
                            "skuId": 0,
                            "templateType": 0,
                            "timeParams": null,
                            "updateTime": null
                        }
                    ],
                    "submitOrderLinkConfigLinkType": 0,
                    "submitOrderLinkConfigLinkUrl": "",
                    "submitOrderLinkConfigWindowText": "",
                    "supplierServicePhone": "95106",
                    "tabId": 1,
                    "taobaoProductId": "",
                    "taobaoProducts": [],
                    "templateType": 0,
                    "tip": "",
                    "tipTemplate": null,
                    "title": "电信-集团电信PLUS会员月包19元/月（翼支付-山西）（5GB流量+影音/视频会员N选1）"
                },
                {
                    "agreementName": "",
                    "agreementNameSuffix": "",
                    "agreementShowLimit": 0,
                    "buttonImg": "",
                    "buttonText": "立即办理",
                    "category": "",
                    "categoryId": 1,
                    "channelBrand": "https://chaac.oss-cn-hangzhou.aliyuncs.com/575e3d2fd28b41a4412998291519bddf13b_20250730152922.jpg",
                    "channelProductMainTitle": "",
                    "channelProductSubTitle": "",
                    "cnId": 10034,
                    "confInfo": null,
                    "defaultChoose": 0,
                    "detailImgs": [
                        "https://chaac.oss-cn-hangzhou.aliyuncs.com/ruleImgad96317f5d3141c7ba696a2851284c0f_20250722164808.png"
                    ],
                    "dialType": 0,
                    "enterLocation": "",
                    "errorToast": {
                        "authErrorToast": "",
                        "orderErrorToast": "",
                        "sendShortMessageErrorToast": "",
                        "tradeErrorToast": ""
                    },
                    "externalLinkUrl": "",
                    "extraConfig": {
                        "autoSendSmsCode": false,
                        "autoSubmitOrder": false,
                        "bulletComment": false
                    },
                    "failurePrompt": "提交异常，请重试",
                    "frontExtInfo": {
                        "flowNum": "10GB",
                        "subTitle": "20元",
                        "mainTitle": "10GB 流量月包",
                        "enableTime": "当月有效",
                        "detail": "一、适用范围\r\n69元及以上套餐用户订购。\r\n二、订购规则\r\n20元10GB全国通用流量，订购成功后流量立即生效，订购当月功能费按日计扣（入网当日到月底），费用四舍五入到分；包内流量按天折算，流量向上取整到MB。不可重复订购。\r\n三、流量规则\r\n主副卡流量可共享，副卡可单独订购，流量可结转。\r\n四、变更规则\r\n订购成功立即生效为连续包月产品，不允许用户变更，允许退订，当月退订次月生效。\r\n五、流量抵扣顺序\r\n定向流量包、不限量视频流量包、赠送闲时流量、闲时流量包、非账单支付假日流量包、1天流量包、3天流量包、7天流量包、30天流量包、畅聊流量包、后向全国流量月包、赠送全国流量、5G特惠流量包、套餐内全国流量、非账单支付流量加餐包、流量加餐包、包月流量包、后向全国流量季包、非账单支付季/半年/年包流量、季/半年/年包流量、不限量升级包、不限量提速包，超出后执行套外流量资费，各省根据省内实际情况微调。\r\n六、退订规则\r\n当月退订，次月生效，退订路径:“陕西电信”微信小程序：服务大厅-办理-业务订购-已订业务/“中国电信”APP：查询办理-手机-全部-业务办理-业务订购-已订业务。",
                        "flowName": "特惠流量月包",
                        "tips": "",
                        "flowPrice": "20元"
                    },
                    "headerImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12541/24487/headImg.png",
                    "iconImg": "",
                    "isReadOnly": 0,
                    "isvTitle": "20元10GB特惠流量包",
                    "itemId": 105031,
                    "listImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12541/24487/productImg.png",
                    "logoImg": "",
                    "marketingSkuTip": null,
                    "marketingSkuTitle": "特惠流量",
                    "packageItemGroupId": 0,
                    "packageItemGroupName": "",
                    "payChannelList": [
                        {
                            "browserType": "",
                            "channelGroup": "",
                            "cnId": 10034,
                            "cnName": "聚合H5",
                            "createTime": "2022-11-01 09:44:23",
                            "dateParams": null,
                            "delFlag": false,
                            "extendData": {},
                            "iconImg": "",
                            "id": 94,
                            "isAsc": "",
                            "orderByColumn": "",
                            "payType": 0,
                            "searchValue": "",
                            "showName": "话费支付",
                            "timeParams": null,
                            "updateTime": "2024-12-25 10:40:24"
                        }
                    ],
                    "payType": 0,
                    "pluginBackgroundImg": "",
                    "pluginProductImg": "",
                    "pocTitle": "",
                    "pocTitleTwo": "",
                    "price": 20.00,
                    "productAttributes": 19,
                    "productAttributesName": "充流量",
                    "productEntryId": 25,
                    "productEntryName": "月包",
                    "promoteScore": 0.0,
                    "ranks": 1,
                    "servicePhoneType": 0,
                    "skuId": 12541,
                    "skuImg": "",
                    "skuProps": {
                        "合约": "1"
                    },
                    "skuUserAgreements": [],
                    "submitOrderLinkConfigLinkType": 0,
                    "submitOrderLinkConfigLinkUrl": "",
                    "submitOrderLinkConfigWindowText": "",
                    "supplierServicePhone": "4000002967",
                    "tabId": 1,
                    "taobaoProductId": "",
                    "taobaoProducts": [
                        {
                            "productId": "857358243552",
                            "enterName": "czjgy"
                        }
                    ],
                    "templateType": 0,
                    "tip": "",
                    "tipTemplate": null,
                    "title": "电信-陕西20元10GB特惠流量包-新接口"
                },
                {
                    "agreementName": "",
                    "agreementNameSuffix": "",
                    "agreementShowLimit": 0,
                    "buttonImg": "",
                    "buttonText": "立即办理",
                    "category": "",
                    "categoryId": 1,
                    "channelBrand": "",
                    "channelProductMainTitle": "",
                    "channelProductSubTitle": "",
                    "cnId": 10034,
                    "confInfo": null,
                    "defaultChoose": 0,
                    "detailImgs": [
                        "https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12431/23838/ruleImg.png"
                    ],
                    "dialType": 0,
                    "enterLocation": "",
                    "errorToast": {
                        "authErrorToast": "",
                        "orderErrorToast": "",
                        "sendShortMessageErrorToast": "",
                        "tradeErrorToast": ""
                    },
                    "externalLinkUrl": "",
                    "extraConfig": {
                        "autoSendSmsCode": false,
                        "autoSubmitOrder": false,
                        "bulletComment": false
                    },
                    "failurePrompt": "提交异常，请重试",
                    "frontExtInfo": {
                        "flowNum": "20GB",
                        "enableType": "立即生效",
                        "cornerIcon": "推荐",
                        "enableTime": "当月有效",
                        "range": "不含港澳台",
                        "flowName": "特惠月包",
                        "tips": "",
                        "contractPeriod": "无",
                        "exit": "退订次月生效",
                        "subTitle": "售价：39元",
                        "mainTitle": "20GB 特惠月包",
                        "renewDesc": "不退订自动续订",
                        "detail": "一、资费内容：39元/月，含20GB国内通用流量，主副卡不可共享包内流量，副卡可单独订购。\r\n二、订购及生效规则\r\n1、订购立即生效，订购当月资费按订购当日至月底的天数折算收取，费用四舍五入到分，流量按天数折算提供，不可变更，退订次月生效。\r\n2、该销售品为连续包月月包，开通后如不取消长期有效。\r\n3、不允许重复订购。\r\n三、其他说明\r\n1、适用范围：适用于除订购天翼畅享（达量降速版）套餐、畅享升级包（达量降速版）以及时长类套餐等不适用加装流量包的套餐之外的所有其他套餐用户订购。\r\n2、流量包内的“国内”指中国内地，不含港澳台。\r\n3、手机上网流量只适用于中国电信移动通信网络，限在中国大陆境内（不含港澳台）使用，不含WLAN（Wi-Fi）上网，互联网卡如遇断网后复机，复机后流量资费以主套餐断网规则约定执行。\r\n4、流量抵扣顺序：定向流量包（包括但不限于：抖音流量包、头条系APP定向流包、爱奇艺视频APP定向包、腾讯视频APP定向包、优酷视频APP定向包、网易云APP定向包等等）＞区域流量包（指流量包内所含流量仅支持在江西省境内使用，不含WLAN(Wi-Fi)上网）＞流量天包（包括但不限于：1天流量包、5天流量包、30天流量包等等）＞全国流量包（指流量包内所含流量支持在中国大陆境内（不含港澳台）使用，不含WLAN(Wi-Fi)上网。）＞套餐流量。\r\n5、该流量包的流量及月基本费，不计入套餐外流量及费用的封顶值计算。",
                        "crossMonth": "0",
                        "flowPrice": "售价：39元"
                    },
                    "headerImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12431/23838/headImg.png",
                    "iconImg": "",
                    "isReadOnly": 0,
                    "isvTitle": "39元20GB流量月包",
                    "itemId": 104922,
                    "listImg": "https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12431/23838/productImg.png",
                    "logoImg": "",
                    "marketingSkuTip": null,
                    "marketingSkuTitle": "特惠流量",
                    "packageItemGroupId": 0,
                    "packageItemGroupName": "",
                    "payChannelList": [
                        {
                            "browserType": "",
                            "channelGroup": "",
                            "cnId": 10034,
                            "cnName": "聚合H5",
                            "createTime": "2022-11-01 09:44:23",
                            "dateParams": null,
                            "delFlag": false,
                            "extendData": {},
                            "iconImg": "",
                            "id": 94,
                            "isAsc": "",
                            "orderByColumn": "",
                            "payType": 0,
                            "searchValue": "",
                            "showName": "话费支付",
                            "timeParams": null,
                            "updateTime": "2024-12-25 10:40:24"
                        }
                    ],
                    "payType": 0,
                    "pluginBackgroundImg": "",
                    "pluginProductImg": "",
                    "pocTitle": "",
                    "pocTitleTwo": "",
                    "price": 39.00,
                    "productAttributes": 19,
                    "productAttributesName": "充流量",
                    "productEntryId": 25,
                    "productEntryName": "月包",
                    "promoteScore": 0.0,
                    "ranks": 1,
                    "servicePhoneType": 0,
                    "skuId": 12431,
                    "skuImg": "",
                    "skuProps": {
                        "合约": "1"
                    },
                    "skuUserAgreements": [],
                    "submitOrderLinkConfigLinkType": 0,
                    "submitOrderLinkConfigLinkUrl": "",
                    "submitOrderLinkConfigWindowText": "",
                    "supplierServicePhone": "4000002967",
                    "tabId": 1,
                    "taobaoProductId": "",
                    "taobaoProducts": [
                        {
                            "productId": "897218025994",
                            "enterName": "czjgy"
                        }
                    ],
                    "templateType": 0,
                    "tip": "",
                    "tipTemplate": null,
                    "title": "电信-江西39元20GB流量月包"
                }
            ],
            "status": 1,
            "subSkuItemList": [],
            "tabPackageList": []
        }
    },
    "msg": "成功",
    "noOrderPlace": false,
    "success": true
}
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        buttonImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
        categoryPackageList: [],
        data: null,
        errorToast: {
          authErrorToast: '',
          orderErrorToast: '',
          sendShortMessageErrorToast: '',
          tradeErrorToast: '',
        },
        frontExtInfo: {
          exit: '退订次月生效，退订当月费用不退还',
          flowNum: '5GB',
          enableType: '订购立即生效',
          mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          renewDesc: '自动续订',
          detail:
            '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
          flowName: '通用流量',
          crossMonth: '1',
          tips: '',
          flowPrice: '19.9元',
        },
        headImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
        holderImg:
          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
        llgAccount: '',
        marketingTitle: '',
        msg: '获取成功',
        operatorCode: 0,
        oppoServiceTypeNo: '',
        provinceId: 0,
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
        skuItem: {
          agreementName: '权益包开通协议',
          agreementNameSuffix: '及页面规则',
          agreementShowLimit: 1,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelBrand: '',
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 2,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
          ],
          dialType: 0,
          enterLocation: '',
          errorToast: {
            authErrorToast: '',
            orderErrorToast: '',
            sendShortMessageErrorToast: '',
            tradeErrorToast: '',
          },
          externalLinkUrl: '',
          extraConfig: {
            autoSendSmsCode: false,
            autoSubmitOrder: false,
            bulletComment: false,
          },
          failurePrompt: '提交异常，请重试',
          frontExtInfo: {
            exit: '退订次月生效，退订当月费用不退还',
            flowNum: '5GB',
            enableType: '订购立即生效',
            mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            renewDesc: '自动续订',
            detail:
              '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
            flowName: '通用流量',
            crossMonth: '1',
            tips: '',
            flowPrice: '19.9元',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          isvTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          itemId: 105364,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
          logoImg: '',
          marketingSkuTip: {
            cancelButtonText: '残忍拒绝',
            cancelButtonType: 0,
            confirmButtonSize: 100,
            confirmButtonText: '确认订购',
            confirmButtonType: 0,
            createTime: '2025-07-09 15:05:18',
            dateParams: null,
            delFlag: false,
            ejectTiming: 0,
            enterId: 0,
            extendData: {},
            id: 310,
            isAsc: '',
            itemId: 105364,
            marketingId: 101138,
            marketingSkuTipType: 'MARKETING_SKU_TIP',
            operUserId: 207,
            orderByColumn: '',
            packageId: 1005426,
            searchValue: '',
            showCloseButton: 1,
            showPhone: 1,
            showSecondConfirm: false,
            showSecondConfirmText: '',
            showServicePhone: 0,
            skuId: 12908,
            timeParams: null,
            tipBackground:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipBackgroundFile.png',
            tipDetailPic:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipDetailPicFile.png',
            tipStatus: true,
            tipText: '',
            tipTitle: '',
            tipType: 0,
            titleColor: '',
            topIcon: '',
            updateTime: '2025-07-11 14:33:29',
          },
          marketingSkuTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10081,
              cnName: '信息流测试H5',
              createTime: '2024-11-19 15:45:45',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 131,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2024-11-19 15:45:51',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 19.9,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 27,
          productEntryName: '权益组合包',
          promoteScore: 0.0,
          ranks: 1,
          servicePhoneType: 0,
          skuId: 12908,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [
            {
              agreement: '',
              agreementName: '权益包开通协议',
              agreementNameSuffix: '及页面规则',
              cnId: 0,
              createTime: null,
              dateParams: null,
              defaultChoose: 2,
              delFlag: false,
              enable: false,
              enterId: 0,
              extendData: {},
              id: 11393,
              isAsc: '',
              orderByColumn: '',
              searchValue: '',
              showLimit: 0,
              skuId: 0,
              templateType: 0,
              timeParams: null,
              updateTime: null,
            },
          ],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          supplierServicePhone: '95106',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: null,
          title: '电信-集团19.9元5G通用流量橙翼权益包（24个月）（翼支付-广东）',
        },
        skuItemList: [
          {
            agreementName: '权益包开通协议',
            agreementNameSuffix: '及页面规则',
            agreementShowLimit: 1,
            buttonImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
            buttonText: '立即办理',
            category: '',
            categoryId: 1,
            channelBrand: '',
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10035,
            confInfo: null,
            defaultChoose: 2,
            detailImgs: [
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
            ],
            dialType: 0,
            enterLocation: '',
            errorToast: {
              authErrorToast: '',
              orderErrorToast: '',
              sendShortMessageErrorToast: '',
              tradeErrorToast: '',
            },
            externalLinkUrl: '',
            extraConfig: {
              autoSendSmsCode: false,
              autoSubmitOrder: false,
              bulletComment: false,
            },
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              exit: '退订次月生效，退订当月费用不退还',
              flowNum: '5GB',
              enableType: '订购立即生效',
              mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
              renewDesc: '自动续订',
              detail:
                '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
              flowName: '通用流量',
              crossMonth: '1',
              tips: '',
              flowPrice: '19.9元',
            },
            headerImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
            iconImg: '',
            isReadOnly: 0,
            isvTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            itemId: 105364,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
            logoImg: '',
            marketingSkuTip: {
              cancelButtonText: '残忍拒绝',
              cancelButtonType: 0,
              confirmButtonSize: 100,
              confirmButtonText: '确认订购',
              confirmButtonType: 0,
              createTime: '2025-07-09 15:05:18',
              dateParams: null,
              delFlag: false,
              ejectTiming: 0,
              enterId: 0,
              extendData: {},
              id: 310,
              isAsc: '',
              itemId: 105364,
              marketingId: 101138,
              marketingSkuTipType: 'MARKETING_SKU_TIP',
              operUserId: 207,
              orderByColumn: '',
              packageId: 1005426,
              searchValue: '',
              showCloseButton: 1,
              showPhone: 1,
              showSecondConfirm: false,
              showSecondConfirmText: '',
              showServicePhone: 0,
              skuId: 12908,
              timeParams: null,
              tipBackground:
                'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipBackgroundFile.png',
              tipDetailPic:
                'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipDetailPicFile.png',
              tipStatus: true,
              tipText: '',
              tipTitle: '',
              tipType: 0,
              titleColor: '',
              topIcon: '',
              updateTime: '2025-07-11 14:33:29',
            },
            marketingSkuTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            packageItemGroupId: 0,
            packageItemGroupName: '',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10081,
                cnName: '信息流测试H5',
                createTime: '2024-11-19 15:45:45',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 131,
                isAsc: '',
                orderByColumn: '',
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2024-11-19 15:45:51',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 19.9,
            productAttributes: 19,
            productAttributesName: '充流量',
            productEntryId: 27,
            productEntryName: '权益组合包',
            promoteScore: 0.0,
            ranks: 1,
            servicePhoneType: 0,
            skuId: 12908,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [
              {
                agreement: '',
                agreementName: '权益包开通协议',
                agreementNameSuffix: '及页面规则',
                cnId: 0,
                createTime: null,
                dateParams: null,
                defaultChoose: 2,
                delFlag: false,
                enable: false,
                enterId: 0,
                extendData: {},
                id: 11393,
                isAsc: '',
                orderByColumn: '',
                searchValue: '',
                showLimit: 0,
                skuId: 0,
                templateType: 0,
                timeParams: null,
                updateTime: null,
              },
            ],
            submitOrderLinkConfigLinkType: 0,
            submitOrderLinkConfigLinkUrl: '',
            submitOrderLinkConfigWindowText: '',
            supplierServicePhone: '95106',
            tabId: 1,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '电信-集团19.9元5G通用流量橙翼权益包（24个月）（翼支付-广东）',
          },
        ],
        status: 1,
        subSkuItemList: [],
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        headImg: getFileByEnv('headImg'),
        holderImg: getFileByEnv('holderImg'),
        errorToast: {
          authErrorToast: '鉴权失败文案覆盖',
          orderErrorToast: '下单失败文案覆盖',
          sendShortMessageErrorToast: '发送验证码失败文案',
          tradeErrorToast: '',
        },
        errorToast: null,
        marketingTitle: '广东联通畅享包',
        msg: '获取成功',
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/rule_img.png',
        skuItem: {
          isvTitle: '我是运营商商品名称',
          enterLocation: '来源编码',
          agreementName: '',
          agreementNameSuffix: '',
          agreementShowLimit: 0,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 0,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
          ],
          externalLinkUrl: '',
          failurePrompt: '接口超时',
          frontExtInfo: {
            exit: '退订次月生效。',
            subTitle: '仅需20元',
            enableType: '立即生效',
            mainTitle: '特惠包',
            enableTime: '当月有效',
            detail:
              '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
            flowName: '送出行券',
            tips: '',
            flowPrice: '20',
            contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          itemId: 104497,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
          logoImg: '',
          marketingSkuTitle: '新标题1',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10035,
              cnName: '测试H5',
              createTime: '2022-11-01 09:44:23',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 95,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2022-11-01 10:33:06',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 20.0,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 24,
          productEntryName: '短期包',
          promoteScore: 0.0,
          ranks: 10,
          skuId: 11926,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: {
            picUrl:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
            tipTemplateFormTitle: '广西20元综合出行权益',
            showPhoneNumber: 1,
            ejectTiming: 1,
          },
          title: '电信-广西20元综合出行权益',
        },
        skuItemList: [
          {
            isvTitle: '我是运营商商品名称',
            enterLocation: '来源编码',
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/rule.png'],
            failurePrompt: '充值享好礼',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/top.png',
            itemId: 101207,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6640,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东15元10G7天包-支付宝宫格',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/top.png',
            itemId: 100973,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6220,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量10元10GB 3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/top.png',
            itemId: 100925,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6152,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元25G7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/top.png',
            itemId: 100934,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6153,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3G3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/top.png',
            itemId: 100935,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6154,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3GB快餐日包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/top.png',
            itemId: 100974,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6221,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量20元14GB7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/top.png',
            itemId: 101112,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6492,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东20元3G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/top.png',
            itemId: 101100,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6429,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元1G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/top.png',
            itemId: 101113,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6493,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元6G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/top.png',
            itemId: 101114,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6494,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东40元9G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/top.png',
            itemId: 101063,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6392,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东199元200GB半年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/top.png',
            itemId: 101064,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6393,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东299元360GB年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/top.png',
            itemId: 101062,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6391,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东99元60GB季包-宫格聚合页',
          },
        ],
        status: 1,
      },
    },
    msg: '成功',
    success: true,
  };
};
