module.exports = (req) => ({
  code: 200,
  data: {
    dataList: [],
    dataMap: {
      headImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/head_img.png',
      holderImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/holder_img.png',
      marketingTitle: '广东联通畅享包',
      msg: '获取成功',
      ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/rule_img.png',
      skuItemList: [
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/rule.png'],
          failurePrompt: '充值享好礼',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/top.png',
          itemId: 101207,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6640,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东15元10G7天包-支付宝宫格',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/top.png',
          itemId: 100973,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6220,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东协议流量10元10GB 3天包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/top.png',
          itemId: 100925,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6152,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东30元25G7天包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/top.png',
          itemId: 100934,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6153,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东10元3G3天包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/top.png',
          itemId: 100935,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6154,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东10元3GB快餐日包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/top.png',
          itemId: 100974,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6221,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东协议流量20元14GB7天包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/top.png',
          itemId: 101112,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6492,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东20元3G月包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/top.png',
          itemId: 101100,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6429,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东10元1G月包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/top.png',
          itemId: 101113,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6493,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东30元6G月包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/top.png',
          itemId: 101114,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6494,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东40元9G月包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/top.png',
          itemId: 101063,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6392,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东199元200GB半年包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/top.png',
          itemId: 101064,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6393,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东299元360GB年包-宫格聚合页',
        },
        {
          cnId: 10005,
          detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/rule.png'],
          failurePrompt: '请仔细核对号码',
          frontExtInfo: {
            tips: '',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/top.png',
          itemId: 101062,
          listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/icon.png',
          pocTitle: '',
          pocTitleTwo: '',
          price: 0.0,
          ranks: 1,
          skuId: 6391,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          taobaoProductId: '',
          taobaoProducts: [],
          title: '联通-广东99元60GB季包-宫格聚合页',
        },
      ],
      status: 1,
    },
  },
  msg: '成功',
  success: true,
});
