const address = require('address');
const { port } = require('../../config');

const getFileByEnv = (key) => {
  const fileName = `${key}.png`;
  const url = `http://${address.ip()}:${port}/static/benefit/${fileName}`;
  return url;
};

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        buttonImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
        categoryPackageList: [],
        data: null,
        errorToast: {
          authErrorToast: '',
          orderErrorToast: '',
          sendShortMessageErrorToast: '',
          tradeErrorToast: '',
        },
        frontExtInfo: {
          exit: '退订次月生效，退订当月费用不退还',
          flowNum: '5GB',
          enableType: '订购立即生效',
          mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          renewDesc: '自动续订',
          detail:
            '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
          flowName: '通用流量',
          crossMonth: '1',
          tips: '',
          flowPrice: '19.9元',
        },
        headImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
        holderImg:
          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
        llgAccount: '',
        marketingTitle: '',
        msg: '获取成功',
        operatorCode: 0,
        oppoServiceTypeNo: '',
        provinceId: 0,
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
        skuItem: {
          agreementName: '权益包开通协议',
          agreementNameSuffix: '及页面规则',
          agreementShowLimit: 1,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelBrand: '',
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 2,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
          ],
          dialType: 0,
          enterLocation: '',
          errorToast: {
            authErrorToast: '',
            orderErrorToast: '',
            sendShortMessageErrorToast: '',
            tradeErrorToast: '',
          },
          externalLinkUrl: '',
          extraConfig: {
            autoSendSmsCode: false,
            autoSubmitOrder: false,
            bulletComment: false,
          },
          failurePrompt: '提交异常，请重试',
          frontExtInfo: {
            exit: '退订次月生效，退订当月费用不退还',
            flowNum: '5GB',
            enableType: '订购立即生效',
            mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            renewDesc: '自动续订',
            detail:
              '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
            flowName: '通用流量',
            crossMonth: '1',
            tips: '',
            flowPrice: '19.9元',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          isvTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          itemId: 105364,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
          logoImg: '',
          marketingSkuTip: {
            cancelButtonText: '残忍拒绝',
            cancelButtonType: 0,
            confirmButtonSize: 100,
            confirmButtonText: '确认订购',
            confirmButtonType: 0,
            createTime: '2025-07-09 15:05:18',
            dateParams: null,
            delFlag: false,
            ejectTiming: 0,
            enterId: 0,
            extendData: {},
            id: 310,
            isAsc: '',
            itemId: 105364,
            marketingId: 101138,
            marketingSkuTipType: 'MARKETING_SKU_TIP',
            operUserId: 207,
            orderByColumn: '',
            packageId: 1005426,
            searchValue: '',
            showCloseButton: 1,
            showPhone: 1,
            showSecondConfirm: false,
            showSecondConfirmText: '',
            showServicePhone: 0,
            skuId: 12908,
            timeParams: null,
            tipBackground:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipBackgroundFile.png',
            tipDetailPic:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipDetailPicFile.png',
            tipStatus: true,
            tipText: '',
            tipTitle: '',
            tipType: 0,
            titleColor: '',
            topIcon: '',
            updateTime: '2025-07-11 14:33:29',
          },
          marketingSkuTitle: '19.9元5G通用流量橙翼权益包（24个月）',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10081,
              cnName: '信息流测试H5',
              createTime: '2024-11-19 15:45:45',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 131,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2024-11-19 15:45:51',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 19.9,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 27,
          productEntryName: '权益组合包',
          promoteScore: 0.0,
          ranks: 1,
          servicePhoneType: 0,
          skuId: 12908,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [
            {
              agreement: '',
              agreementName: '权益包开通协议',
              agreementNameSuffix: '及页面规则',
              cnId: 0,
              createTime: null,
              dateParams: null,
              defaultChoose: 2,
              delFlag: false,
              enable: false,
              enterId: 0,
              extendData: {},
              id: 11393,
              isAsc: '',
              orderByColumn: '',
              searchValue: '',
              showLimit: 0,
              skuId: 0,
              templateType: 0,
              timeParams: null,
              updateTime: null,
            },
          ],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          supplierServicePhone: '95106',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: null,
          title: '电信-集团19.9元5G通用流量橙翼权益包（24个月）（翼支付-广东）',
        },
        skuItemList: [
          {
            agreementName: '权益包开通协议',
            agreementNameSuffix: '及页面规则',
            agreementShowLimit: 1,
            buttonImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/buttonImg.png',
            buttonText: '立即办理',
            category: '',
            categoryId: 1,
            channelBrand: '',
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10035,
            confInfo: null,
            defaultChoose: 2,
            detailImgs: [
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/ruleImg.png',
            ],
            dialType: 0,
            enterLocation: '',
            errorToast: {
              authErrorToast: '',
              orderErrorToast: '',
              sendShortMessageErrorToast: '',
              tradeErrorToast: '',
            },
            externalLinkUrl: '',
            extraConfig: {
              autoSendSmsCode: false,
              autoSubmitOrder: false,
              bulletComment: false,
            },
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              exit: '退订次月生效，退订当月费用不退还',
              flowNum: '5GB',
              enableType: '订购立即生效',
              mainTitle: '19.9元5G通用流量橙翼权益包（24个月）',
              renewDesc: '自动续订',
              detail:
                '本礼包由10元5G流量包、9.9元权益包（24个月）组成。同类产品有效期内，同一号码仅可以享受一次，不可重复参与本次活动（包括在其他渠道或活动办理过同类产品)，具体参与资格以系统校验为准。\r\n每月资费19.9元/月，组合礼包24个月到期后，9.9元权益包（24个月）自动取消，10元5G流量包按月收费，每月收费10元。\r\n\r\n10元5G流量包\r\n一、资费内容\r\n资费：10元/月，包含5GB国内通用流量。\r\n二、适用范围\r\n适用于中国电信除时长型套餐等已发文明确不允许订购流量包的套餐以外的4G/5G手机用户。\r\n三、包内业务使用规则\r\n（一）流量包内流量为国内流量，用于中国电信现有移动通信网络，仅限中国大陆境内使用（不区分5G\\4G\\3G\\2G网络），不含港澳台，不含WLAN（Wi-Fi）上网。\r\n（二）主副卡不共享，副卡可单独订购。\r\n（三）适用于流量不清零规则。\r\n（四）包内流量及月功能费，不计入套餐外流量封顶及费用封顶值计算。\r\n（五）提速与降速：本产品具备提速功能，支持畅享套餐或畅享升级包用户订购，未被降速的用户订购后，等同于增加降速阈值，首次达到套餐所对应的流量阈值时不降速，流量包使用完后降速；已降速用户订购后，恢复速率，流量包使用完后再次降速。\r\n（六）流量抵扣顺序：遵循有利于用户使用的原则，优先使用业务限制大、有效期短的流量，原则上按照定向流量包-闲时流量包-通用流量包-套内流量-套外流量的规则进行抵扣，具体顺序以产品实际情况为准。本流量抵扣顺序相当于“通用流量包”。\r\n四、其他规则\r\n（一）生效规则：\r\n订购立即生效，当月费用按日计扣（入网当日到月底），四舍五入到分；包内流量按天折算，向上取整到MB。开通后如不取消长期有效。可随时退订，退订次月生效，退订当月费用不退还。\r\n（二）流量包有效期：\r\n有效期为2年，自订购之日起算。如双方在有效期届满前30日均未提出异议的，套餐有效期自动续展，每次续展期限为2年。续展期内，因中国电信的电信业务经营许可证业务范围、业务种类发生改变，或中国电信对通信网络进行整体换代升级、技术进步、国家政策变动、业务调整等， 中国电信有权提前30天通过短信、客户电话或公告的方式通知用户终止本业务。用户有权办理业务终止或变更。\r\n（三）重复订购规则：\r\n有效期内不允许重复订购。\r\n\r\n9.9元权益包（24个月）\r\n一、资费内容\r\n1、月基本费9.9元。自订购当月起，每月可领取翼支付权益，连续24个月，订购立即生效，到期自动取消。\r\n2、翼支付权益：办理时默认开通翼支付功能，办理后需到电子渠道指定页面领取权益（广东电信微信小程序-权益专区等）。权益含互联网会员权益及翼支付券等（权益不定期更新，部分权益可能因合作停止等原因调整，具体以领取页面为准）。\r\n二、适用范围：适用于所有4G/5G手机套餐用户，包括预付费和后付费。 仅限个人名用户办理。\r\n三、其他规则：\r\n1、生效规则：新老用户均可订购，订购后立即生效，首月全额计费，不按天折算。有效期内，不允许重复订购。\r\n2、变更、退订规则：退订次月生效。如当月退订，退订后权益不可领取。允许拆机，拆机立即生效。\r\n3、续约规则：24个月到期取消，不自动续约。\r\n4、权益按月领取，如退订，次月起不可领取权益。\r\n5、支付方式：账单支付。\r\n6、号码处于欠费、停机、挂失、未实名、拆机等状态不可办理。\r\n7、订单完成后，可在广东电信网上营业厅“我的协议”处，查询电子协议回执。\r\n\r\n退订入口：\r\nA.中国电信APP-查询办理-办理-基础业务办理-业务退订；\r\nB.广东电信小程序-服务大厅-办理-基础业务办理-业务退订；\r\nC.触屏版中国电信网厅-服务大厅-办理-基础业务办理-业务退订；\r\nD.中国电信网厅-个人主页-办理-基础业务-业务退订\r\nE.拨打中国电信10000号客服热线进行退订。',
              flowName: '通用流量',
              crossMonth: '1',
              tips: '',
              flowPrice: '19.9元',
            },
            headerImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/headImg.png',
            iconImg: '',
            isReadOnly: 0,
            isvTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            itemId: 105364,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12908/101138/productImg.png',
            logoImg: '',
            marketingSkuTip: {
              cancelButtonText: '残忍拒绝',
              cancelButtonType: 0,
              confirmButtonSize: 100,
              confirmButtonText: '确认订购',
              confirmButtonType: 0,
              createTime: '2025-07-09 15:05:18',
              dateParams: null,
              delFlag: false,
              ejectTiming: 0,
              enterId: 0,
              extendData: {},
              id: 310,
              isAsc: '',
              itemId: 105364,
              marketingId: 101138,
              marketingSkuTipType: 'MARKETING_SKU_TIP',
              operUserId: 207,
              orderByColumn: '',
              packageId: 1005426,
              searchValue: '',
              showCloseButton: 1,
              showPhone: 1,
              showSecondConfirm: false,
              showSecondConfirmText: '',
              showServicePhone: 0,
              skuId: 12908,
              timeParams: null,
              tipBackground:
                'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipBackgroundFile.png',
              tipDetailPic:
                'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101138/1005426/105364/12908/tipDetailPicFile.png',
              tipStatus: true,
              tipText: '',
              tipTitle: '',
              tipType: 0,
              titleColor: '',
              topIcon: '',
              updateTime: '2025-07-11 14:33:29',
            },
            marketingSkuTitle: '19.9元5G通用流量橙翼权益包（24个月）',
            packageItemGroupId: 0,
            packageItemGroupName: '',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10081,
                cnName: '信息流测试H5',
                createTime: '2024-11-19 15:45:45',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 131,
                isAsc: '',
                orderByColumn: '',
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2024-11-19 15:45:51',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 19.9,
            productAttributes: 19,
            productAttributesName: '充流量',
            productEntryId: 27,
            productEntryName: '权益组合包',
            promoteScore: 0.0,
            ranks: 1,
            servicePhoneType: 0,
            skuId: 12908,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [
              {
                agreement: '',
                agreementName: '权益包开通协议',
                agreementNameSuffix: '及页面规则',
                cnId: 0,
                createTime: null,
                dateParams: null,
                defaultChoose: 2,
                delFlag: false,
                enable: false,
                enterId: 0,
                extendData: {},
                id: 11393,
                isAsc: '',
                orderByColumn: '',
                searchValue: '',
                showLimit: 0,
                skuId: 0,
                templateType: 0,
                timeParams: null,
                updateTime: null,
              },
            ],
            submitOrderLinkConfigLinkType: 0,
            submitOrderLinkConfigLinkUrl: '',
            submitOrderLinkConfigWindowText: '',
            supplierServicePhone: '95106',
            tabId: 1,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '电信-集团19.9元5G通用流量橙翼权益包（24个月）（翼支付-广东）',
          },
        ],
        status: 1,
        subSkuItemList: [],
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        headImg: getFileByEnv('headImg'),
        holderImg: getFileByEnv('holderImg'),
        errorToast: {
          authErrorToast: '鉴权失败文案覆盖',
          orderErrorToast: '下单失败文案覆盖',
          sendShortMessageErrorToast: '发送验证码失败文案',
          tradeErrorToast: '',
        },
        errorToast: null,
        marketingTitle: '广东联通畅享包',
        msg: '获取成功',
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/rule_img.png',
        skuItem: {
          isvTitle: '我是运营商商品名称',
          enterLocation: '来源编码',
          agreementName: '',
          agreementNameSuffix: '',
          agreementShowLimit: 0,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 0,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
          ],
          externalLinkUrl: '',
          failurePrompt: '接口超时',
          frontExtInfo: {
            exit: '退订次月生效。',
            subTitle: '仅需20元',
            enableType: '立即生效',
            mainTitle: '特惠包',
            enableTime: '当月有效',
            detail:
              '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
            flowName: '送出行券',
            tips: '',
            flowPrice: '20',
            contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          itemId: 104497,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
          logoImg: '',
          marketingSkuTitle: '新标题1',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10035,
              cnName: '测试H5',
              createTime: '2022-11-01 09:44:23',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 95,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2022-11-01 10:33:06',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 20.0,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 24,
          productEntryName: '短期包',
          promoteScore: 0.0,
          ranks: 10,
          skuId: 11926,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: {
            picUrl:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
            tipTemplateFormTitle: '广西20元综合出行权益',
            showPhoneNumber: 1,
            ejectTiming: 1,
          },
          title: '电信-广西20元综合出行权益',
        },
        skuItemList: [
          {
            isvTitle: '我是运营商商品名称',
            enterLocation: '来源编码',
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/rule.png'],
            failurePrompt: '充值享好礼',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/top.png',
            itemId: 101207,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6640,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东15元10G7天包-支付宝宫格',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/top.png',
            itemId: 100973,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6220,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量10元10GB 3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/top.png',
            itemId: 100925,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6152,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元25G7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/top.png',
            itemId: 100934,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6153,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3G3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/top.png',
            itemId: 100935,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6154,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3GB快餐日包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/top.png',
            itemId: 100974,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6221,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量20元14GB7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/top.png',
            itemId: 101112,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6492,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东20元3G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/top.png',
            itemId: 101100,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6429,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元1G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/top.png',
            itemId: 101113,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6493,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元6G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/top.png',
            itemId: 101114,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6494,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东40元9G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/top.png',
            itemId: 101063,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6392,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东199元200GB半年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/top.png',
            itemId: 101064,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6393,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东299元360GB年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/top.png',
            itemId: 101062,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6391,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东99元60GB季包-宫格聚合页',
          },
        ],
        status: 1,
      },
    },
    msg: '成功',
    success: true,
  };
};
