const address = require('address');
const { port } = require('../../config');

const getFileByEnv = (key) => {
  const fileName = `${key}.png`;
  const url = `http://${address.ip()}:${port}/static/benefit/${fileName}`;
  return url;
};

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        headImg: getFileByEnv('headImg'),
        holderImg: getFileByEnv('holderImg'),
        errorToast: {
          authErrorToast: '鉴权失败文案覆盖',
          orderErrorToast: '下单失败文案覆盖',
          sendShortMessageErrorToast: '发送验证码失败文案',
          tradeErrorToast: '',
        },
        errorToast: null,
        marketingTitle: '广东联通畅享包',
        msg: '获取成功',
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/rule_img.png',
        skuItem: {
          isvTitle: '我是运营商商品名称',
          enterLocation: '来源编码',
          agreementName: '',
          agreementNameSuffix: '',
          agreementShowLimit: 0,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 0,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
          ],
          externalLinkUrl: '',
          failurePrompt: '接口超时',
          frontExtInfo: {
            exit: '退订次月生效。',
            subTitle: '仅需20元',
            enableType: '立即生效',
            mainTitle: '特惠包',
            enableTime: '当月有效',
            detail:
              '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
            flowName: '送出行券',
            tips: '',
            flowPrice: '20',
            contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          itemId: 104497,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
          logoImg: '',
          marketingSkuTitle: '新标题1',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10035,
              cnName: '测试H5',
              createTime: '2022-11-01 09:44:23',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 95,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2022-11-01 10:33:06',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 20.0,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 24,
          productEntryName: '短期包',
          promoteScore: 0.0,
          ranks: 10,
          skuId: 11926,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: {
            picUrl:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
            tipTemplateFormTitle: '广西20元综合出行权益',
            showPhoneNumber: 1,
            ejectTiming: 1,
          },
          title: '电信-广西20元综合出行权益',
        },
        skuItemList: [
          {
            isvTitle: '我是运营商商品名称',
            enterLocation: '来源编码',
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/rule.png'],
            failurePrompt: '充值享好礼',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/top.png',
            itemId: 101207,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6640,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东15元10G7天包-支付宝宫格',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/top.png',
            itemId: 100973,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6220,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量10元10GB 3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/top.png',
            itemId: 100925,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6152,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元25G7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/top.png',
            itemId: 100934,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6153,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3G3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/top.png',
            itemId: 100935,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6154,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3GB快餐日包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/top.png',
            itemId: 100974,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6221,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量20元14GB7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/top.png',
            itemId: 101112,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6492,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东20元3G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/top.png',
            itemId: 101100,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6429,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元1G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/top.png',
            itemId: 101113,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6493,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元6G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/top.png',
            itemId: 101114,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6494,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东40元9G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/top.png',
            itemId: 101063,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6392,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东199元200GB半年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/top.png',
            itemId: 101064,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6393,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东299元360GB年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/top.png',
            itemId: 101062,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 10,
            skuId: 6391,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东99元60GB季包-宫格聚合页',
          },
        ],
        status: 1,
      },
    },
    msg: '成功',
    success: true,
  };
};
