const address = require('address');
const { port } = require('../../config');

const getFileByEnv = (key) => {
  const fileName = `${key}.png`;
  const url = `http://${address.ip()}:${port}/static/benefit/${fileName}`;
  return url;
};

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        buttonImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
        categoryPackageList: [],
        data: null,
        frontExtInfo: null,
        headImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
        holderImg:
          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
        marketingTitle: '特惠业务',
        msg: '获取成功',
        operatorCode: 0,
        oppoServiceTypeNo: '',
        provinceId: 0,
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
        skuItem: {
          agreementName: '',
          agreementNameSuffix: '',
          agreementShowLimit: 0,
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
          buttonText: '立即办理',
          category: '',
          categoryId: 1,
          channelProductMainTitle: '',
          channelProductSubTitle: '',
          cnId: 10035,
          confInfo: null,
          defaultChoose: 0,
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
          ],
          externalLinkUrl: '',
          failurePrompt: '接口超时',
          frontExtInfo: {
            exit: '退订次月生效。',
            subTitle: '仅需20元',
            enableType: '立即生效',
            mainTitle: '特惠包',
            enableTime: '当月有效',
            detail:
              '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
            flowName: '送出行券',
            tips: '',
            flowPrice: '20',
            contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
          },
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
          iconImg: '',
          isReadOnly: 0,
          itemId: 104497,
          listImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
          logoImg: '',
          packageItemGroupId: 0,
          packageItemGroupName: '',
          payChannelList: [
            {
              browserType: '',
              channelGroup: '',
              cnId: 10035,
              cnName: '测试H5',
              createTime: '2022-11-01 09:44:23',
              dateParams: null,
              delFlag: false,
              extendData: {},
              iconImg: '',
              id: 95,
              isAsc: '',
              orderByColumn: '',
              payType: 0,
              searchValue: '',
              showName: '话费支付',
              timeParams: null,
              updateTime: '2022-11-01 10:33:06',
            },
          ],
          payType: 0,
          pluginBackgroundImg: '',
          pluginProductImg: '',
          pocTitle: '',
          pocTitleTwo: '',
          price: 20.0,
          productAttributes: 19,
          productAttributesName: '充流量',
          productEntryId: 24,
          productEntryName: '短期包',
          promoteScore: 0.0,
          ranks: 1,
          skuId: 11926,
          skuImg: '',
          skuProps: {
            合约: '1',
          },
          skuUserAgreements: [],
          submitOrderLinkConfigLinkType: 0,
          submitOrderLinkConfigLinkUrl: '',
          submitOrderLinkConfigWindowText: '',
          tabId: 1,
          taobaoProductId: '',
          taobaoProducts: [],
          templateType: 0,
          tip: '',
          tipTemplate: {
            picUrl:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
            tipTemplateFormTitle: '广西20元综合出行权益',
            showPhoneNumber: 1,
            ejectTiming: 1,
          },
          title: '电信-广西20元综合出行权益',
        },
        skuItemList: [
          {
            agreementName: '',
            agreementNameSuffix: '',
            agreementShowLimit: 0,
            buttonImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/buttonImg.png',
            buttonText: '立即办理',
            category: '',
            categoryId: 1,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10035,
            confInfo: null,
            defaultChoose: 0,
            detailImgs: [
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/ruleImg.png',
            ],
            externalLinkUrl: '',
            failurePrompt: '接口超时',
            frontExtInfo: {
              exit: '退订次月生效。',
              subTitle: '仅需20元',
              enableType: '立即生效',
              mainTitle: '特惠包',
              enableTime: '当月有效',
              detail:
                '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
              flowName: '送出行券',
              tips: '',
              flowPrice: '20',
              contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
            },
            headerImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/headImg.png',
            iconImg: '',
            isReadOnly: 0,
            itemId: 104497,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11926/101049/productImg.png',
            logoImg: '',
            packageItemGroupId: 0,
            packageItemGroupName: '',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10035,
                cnName: '测试H5',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 95,
                isAsc: '',
                orderByColumn: '',
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 20.0,
            productAttributes: 19,
            productAttributesName: '充流量',
            productEntryId: 24,
            productEntryName: '短期包',
            promoteScore: 0.0,
            ranks: 1,
            skuId: 11926,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            submitOrderLinkConfigLinkType: 0,
            submitOrderLinkConfigLinkUrl: '',
            submitOrderLinkConfigWindowText: '',
            tabId: 1,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: {
              picUrl:
                'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
              tipTemplateFormTitle: '广西20元综合出行权益',
              showPhoneNumber: 1,
              ejectTiming: 1,
            },
            title: '电信-广西20元综合出行权益',
          },
        ],
        status: 1,
        subSkuItemList: [],
        tabPackageList: [],
      },
    },
    msg: '成功',
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        buttonImg: '',
        categoryPackageList: [],
        data: null,
        frontExtInfo: null,
        headImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/metas/marketing/100853/headImg999.jpg',
        holderImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/5697/5696/icon.png',
        marketingTitle: '权益领取',
        msg: '获取成功',
        oppoServiceTypeNo: 'SERVICE_TYPE_2000',
        operatorCode: 0,
        provinceId: 0,
        ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/6640/5481/ruleImg.png',
        skuItemList: [],
        status: 1,
        subSkuItemList: [
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '月度VIP',
              equityTitle: '芒果TV会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '芒果TV',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/metas/marketing/100853/headImg999.jpg',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10693/18309/iconImg.png',
            isReadOnly: 0,
            itemId: 103403,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10693/18309/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10693,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-芒果TV月度VIP',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '大会员月卡',
              equityTitle: '哔哩哔哩会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '哔哩哔哩',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10695/18312/iconImg.png',
            isReadOnly: 0,
            itemId: 103405,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10695/18312/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10695,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-哔哩哔哩大会员月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '月度VIP',
              equityTitle: '优酷视频会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '优酷视频',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10694/18311/iconImg.png',
            isReadOnly: 0,
            itemId: 103404,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10694/18311/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10694,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-优酷月度VIP',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '黄金月卡',
              equityTitle: '爱奇艺会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '爱奇艺',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10690/18308/iconImg.png',
            isReadOnly: 0,
            itemId: 103400,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10690/18308/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10690,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-爱奇艺黄金月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '月度VIP',
              equityTitle: '腾讯视频会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '腾讯视频',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10689/18307/iconImg.png',
            isReadOnly: 0,
            itemId: 103399,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10689/18307/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10689,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-腾讯视频月度VIP',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '绿钻月卡',
              equityTitle: 'QQ音乐会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: 'QQ音乐',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10688/18306/iconImg.png',
            isReadOnly: 0,
            itemId: 103398,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10688/18306/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10688,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-QQ音乐绿钻月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '会员月卡',
              equityTitle: '喜马拉雅会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '喜马拉雅',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10686/18304/iconImg.png',
            isReadOnly: 0,
            itemId: 103395,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10686/18304/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10686,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-喜马拉雅VIP月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: '饿了么超级会员月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10760/18869/iconImg.png',
            isReadOnly: 0,
            itemId: 103459,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10760/18869/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10760,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-饿了么超级会员月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: '百度网盘svip月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10759/18868/iconImg.png',
            isReadOnly: 0,
            itemId: 103458,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10759/18868/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10759,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-百度网盘svip月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: '酷我豪华VIP月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10758/18867/iconImg.png',
            isReadOnly: 0,
            itemId: 103457,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10758/18867/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 15,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10758,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-酷我豪华VIP月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: '知乎盐选月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10757/18866/iconImg.png',
            isReadOnly: 0,
            itemId: 103456,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10757/18866/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10757,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-知乎盐选月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: '新浪微博会员月',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10756/18865/iconImg.png',
            isReadOnly: 0,
            itemId: 103455,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10756/18865/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10756,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-新浪微博会员月',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: 'WPS稻壳会员月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10754/18863/iconImg.png',
            isReadOnly: 0,
            itemId: 103453,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10754/18863/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10754,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-WPS稻壳会员月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              subTitle: '黑胶VIP月卡',
              equityTitle: '网易云音乐会员',
              enableType: '领取后立即生效',
              flex: '1:1',
              mainTitle: '网易云音乐',
              enableTime: '30天有效',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10687/18305/iconImg.png',
            isReadOnly: 0,
            itemId: 103397,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10687/18305/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 21,
            productEntryName: '影音会员',
            promoteScore: 0,
            ranks: 1,
            skuId: 10687,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-网易云音乐黑胶VIP月卡',
          },
          {
            agreementName: '',
            buttonText: '立即办理',
            category: '',
            categoryId: 0,
            channelProductMainTitle: '',
            channelProductSubTitle: '',
            cnId: 10015,
            confInfo: null,
            detailImgs: [''],
            externalLinkUrl: '',
            failurePrompt: '提交异常，请重试',
            frontExtInfo: {
              equityTips: '月月领',
              equityTitle: 'KEEP会员月卡',
              flex: '1:1',
              tips: '',
            },
            headerImg: '',
            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10755/18864/iconImg.png',
            isReadOnly: 0,
            itemId: 103454,
            listImg:
              'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/10755/18864/productImg.png',
            logoImg: '',
            packageItemGroupId: 100033,
            packageItemGroupName: '视听会员5选1',
            payChannelList: [
              {
                browserType: '',
                channelGroup: '',
                cnId: 10016,
                cnName: '存量小程序无需支付',
                createTime: '2022-11-01 09:44:23',
                dateParams: null,
                delFlag: false,
                extendData: {},
                iconImg: '',
                id: 77,
                payType: 0,
                searchValue: '',
                showName: '话费支付',
                timeParams: null,
                updateTime: '2022-11-01 10:33:06',
              },
            ],
            payType: 0,
            pluginBackgroundImg: '',
            pluginProductImg: '',
            pocTitle: '',
            pocTitleTwo: '',
            price: 30,
            productAttributes: 20,
            productAttributesName: '会员权益',
            productEntryId: 23,
            productEntryName: '其他',
            promoteScore: 0,
            ranks: 1,
            skuId: 10755,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            skuUserAgreements: [],
            tabId: 0,
            taobaoProductId: '',
            taobaoProducts: [],
            templateType: 0,
            tip: '',
            tipTemplate: null,
            title: '全网-KEEP会员月卡',
          },
        ],
        tabPackageList: [],
      },
    },
    msg: '成功',
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        // headImg: getFileByEnv('headImg'),
        headerImg: 'https://img.temp.im/750x500/fe5039/fe5039',
        // holderImg: getFileByEnv('holderImg'),
        holderImg: 'https://img.temp.im/700x610/ffad66/ffad66',
        marketingTitle: '广东联通畅享包',
        msg: '获取成功',
        // ruleImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/enterPackage/100378/1001149/rule_img.png',
        ruleImg: 'https://img.temp.im/750x1500/ff935b/ff935b',
        skuItemList: [
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/rule.png'],
            failurePrompt: '充值享好礼',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/top.png',
            itemId: 101207,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6640/4615/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6640,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东15元10G7天包-支付宝宫格',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/top.png',
            itemId: 100973,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6220/4215/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6220,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量10元10GB 3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/top.png',
            itemId: 100925,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6152/4150/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6152,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元25G7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/top.png',
            itemId: 100934,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6153/4151/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6153,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3G3天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/top.png',
            itemId: 100935,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6154/4152/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6154,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元3GB快餐日包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/top.png',
            itemId: 100974,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6221/4216/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6221,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东协议流量20元14GB7天包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/top.png',
            itemId: 101112,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6492/4481/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6492,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东20元3G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/top.png',
            itemId: 101100,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6429/4419/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6429,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东10元1G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/top.png',
            itemId: 101113,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6493/4482/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6493,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东30元6G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/top.png',
            itemId: 101114,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6494/4483/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6494,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东40元9G月包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/top.png',
            itemId: 101063,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6392/4384/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6392,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东199元200GB半年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/top.png',
            itemId: 101064,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6393/4385/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6393,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东299元360GB年包-宫格聚合页',
          },
          {
            cnId: 10005,
            detailImgs: ['https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/rule.png'],
            failurePrompt: '请仔细核对号码',
            frontExtInfo: {
              tips: '',
            },
            headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/top.png',
            itemId: 101062,
            listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/6391/4383/icon.png',
            pocTitle: '',
            pocTitleTwo: '',
            price: 0.0,
            ranks: 1,
            skuId: 6391,
            skuImg: '',
            skuProps: {
              合约: '1',
            },
            taobaoProductId: '',
            taobaoProducts: [],
            title: '联通-广东99元60GB季包-宫格聚合页',
          },
        ],
        status: 1,
      },
    },
    msg: '成功',
    success: true,
  };
};
