const address = require('address');
const { port } = require('../../config');

const FileNameMap = {
  headImg: 'headImg.png',
  listImg: 'listImg.png',
  ruleImg: 'ruleImg.png',
  iconImg: 'iconImg.png',
};

module.exports = (req) => {
  // 如果是开发模式, 则读取public文件夹下的素材
  // const isDevelopment = true;
  const isDevelopment = false;

  const getFileByEnv = (key, defaultPath) => {
    if (isDevelopment) {
      const url = `http://${address.ip()}:${port}/static/benefit/${FileNameMap[key]}`;
      return url;
    }
    return defaultPath;
  };
  // 陕西移动
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        blackList: false,
        categoryPackageList: [],
        hasProduct: true,
        marketingFlag: true,
        msg: '有商品',
        noProduct: false,
        operatorCode: 2,
        phoneNumber: '159cjjaeb49',
        provinceId: 61,
        provinceName: '陕西',
        provinceOperatorName: '陕西移动',
        showPackageInfo: null,
        showPackageList: [
          {
            categoryId: 1,
            detailImg: '',
            firstPriority: -10000,
            frontExtInfo: {},
            headerImg: '',
            marketingFlag: true,
            marketingTitle: '产品链接',
            packageId: 1005449,
            packageMutexGroups: '',
            priority: 1,
            productAttributes: 0,
            productEntryId: 0,
            productId: '',
            quotaLimit: 0,
            routeGroup: '',
            sendSms: true,
            showItemList: [
              {
                detailImg: '',
                formInfo: null,
                hideType: 0,
                indexImg: '',
                itemId: 105387,
                listImg: '',
                maxShowSkuNum: 10,
                optional: true,
                packagerId: 0,
                skuRanks: 0,
                skus: [
                  {
                    agreementName: '',
                    agreementNameSuffix: '',
                    agreementShowLimit: 0,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12931/101070/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 0,
                    channelBrand:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/541d8ba25098a954f1b8736a1bfdd8e6cc7_20250715134212.png',
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10081,
                    confInfo: null,
                    defaultChoose: 0,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/ruleImg8b3859f961aa4b66b907c4222af40110_20251118120258.png',
                    ],
                    dialType: 0,
                    enterLocation: '',
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    extraConfig: {
                      autoSendSmsCode: false,
                      autoSubmitOrder: false,
                      bulletComment: false,
                    },
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      exit: '到期自动失效',
                      flowNum: '80GB流量',
                      subTitle: '80GB国内通用流量',
                      enableType: '立即生效',
                      mainTitle: '热门会员月卡',
                      enableTime: '有效期7天，到期自动失效',
                      detail:
                        '1、办理对象 :本活动仅限陕西移动用户参加，欠费、黑名单停机用户不能办理。\r\n2、生效方式:办理立即生效，立即扣费，有效期7天，到期自动失效。\r\n3、产品权益 :40元包含80GB国内通用流量，1个热门会员月卡权益(包含爱奇艺、优酷、芒果TV、搜狐视频、酷狗音乐QQ音乐、酷我音乐、网易云音乐、喜马拉雅多选一，领取成功后有效期一个月)，流量包有效期7天，办理立即生效，到期自动失效。会员权益需在流量包有效期内领取，同时加送移动云盘500G空间、视频彩铃基础会员、咪咕视频钻石会员、咪咕快游会员，有效期至当月月底。\r\n4、权益领取规则:会员权益需在流量包有效期内领取，领取权益请点击 https://dx.10086.cn/shipin。未领则作废，即未领取不能补领。\r\n5、退订说明 :本产品办理成功后不可退订。\r\n6、流量不可共享，不可结转，订购关系到期自动失效。\r\n7、其他说明:本产品不可叠加办理,\r\n8、如您办理成功，有任何疑问请联系我们，请致电4000002967或拨打10086咨询',
                      flowName: '全国通用流量',
                      tips: '',
                      flowPrice: '40元/7天',
                      contractPeriod: '无合约期',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12931/101070/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    isvTitle: '40元80GB超值流量包',
                    itemId: 105387,
                    listImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12931/101070/productImg.png',
                    logoImg: '',
                    marketingSkuTip: {
                      cancelButtonText: '确认取消',
                      cancelButtonType: 0,
                      confirmButtonSize: 100,
                      confirmButtonText: '确认订购',
                      confirmButtonType: 0,
                      createTime: '2025-07-15 18:53:55',
                      dateParams: null,
                      delFlag: false,
                      ejectTiming: 1,
                      enterId: 0,
                      extendData: {},
                      id: 314,
                      isAsc: '',
                      itemId: 105387,
                      marketingId: 101070,
                      marketingSkuTipType: 'MARKETING_SKU_TIP',
                      operUserId: 174,
                      orderByColumn: '',
                      packageId: 1005449,
                      searchValue: '',
                      showCloseButton: 1,
                      showPhone: 1,
                      showSecondConfirm: false,
                      showSecondConfirmText: '',
                      showServicePhone: 0,
                      skuId: 12931,
                      timeParams: null,
                      tipBackground:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1005449/105387/12931/tipBackgroundFile.png',
                      tipDetailPic:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1005449/105387/12931/tipDetailPicFile.png',
                      tipStatus: true,
                      tipText:
                        '<p><span style="color: rgb(38, 38, 38);">业务名称：40元80GB超值流量包特惠</span></p><p><span style="color: rgb(38, 38, 38);">业务资费：40元/7天</span></p><p><span style="color: rgb(38, 38, 38);">业务内容：包含80GB全国通用流量，1个热门会员月卡权益，同时加送移动云盘500G空间、视频彩铃基础会员、咪咕视频钻石会员、咪咕快游会员。</span></p><p><span style="color: rgb(38, 38, 38);">生效及退订方式：办理立即生效，立即扣费，有效期7天，到期自动失效。</span></p>',
                      tipTitle: '40元80GB超值流量包',
                      tipType: 0,
                      titleColor: '#ffffff',
                      topIcon: '',
                      updateTime: '2025-11-24 14:04:07',
                    },
                    marketingSkuTitle: '40元80GB超值流量包',
                    opCommId: '96060767',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10081,
                        cnName: '信息流测试H5',
                        createTime: '2024-11-19 15:45:45',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 131,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2024-11-19 15:45:51',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 40.0,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 25,
                    productEntryName: '月包',
                    promoteScore: 0.0,
                    ranks: -10000,
                    servicePhoneType: 0,
                    skuId: 12931,
                    skuImg: '',
                    skuProps: {
                      合约: '1',
                    },
                    skuUserAgreements: [],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 0,
                    taobaoProductId: '',
                    taobaoProducts: [],
                    templateType: 0,
                    tip: '',
                    tipTemplate: null,
                    title: '移动-陕西40元80GB超值会员权益流量包-7天包',
                  },
                ],
                title: '移动-陕西40元80GB超值会员权益流量包-7天包',
              },
            ],
            smsLength: 4,
            success: true,
            tabId: 1,
          },
        ],
        status: 1,
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        blackList: false,
        categoryPackageList: [],
        hasProduct: true,
        marketingFlag: true,
        msg: '有商品',
        noProduct: false,
        operatorCode: 3,
        phoneNumber: '177hgabee76',
        provinceId: 45,
        provinceName: '广西',
        provinceOperatorName: '广西电信',
        showPackageInfo: null,
        showPackageList: [
          {
            categoryId: 1,
            detailImg: '',
            firstPriority: -10000,
            frontExtInfo: {
              autoCtrlUpCycleRegularUp: '2025-09-03 07:00:54',
              autoCtrlUpOperate: '0',
              autoCtrlUpCycle: 'regular',
              autoCtrlUpCycleRegularDown: '2025-09-03 12:00:54',
            },
            headerImg: '',
            marketingFlag: true,
            marketingTitle: '广西电信',
            packageId: 1005291,
            packageMutexGroups: '',
            priority: 1,
            productAttributes: 0,
            productEntryId: 0,
            productId: '',
            quotaLimit: 1,
            routeGroup: '',
            sendSms: true,
            showItemList: [
              {
                detailImg: '',
                formInfo: null,
                hideType: 0,
                indexImg: '',
                itemId: 105232,
                listImg: '',
                maxShowSkuNum: 10,
                optional: true,
                packagerId: 0,
                skuRanks: 0,
                skus: [
                  {
                    agreementName: '用户服务协议、隐私协议',
                    agreementNameSuffix: '及页面规则',
                    agreementShowLimit: 1,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12881/101280/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 0,
                    channelBrand: '',
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10035,
                    confInfo: null,
                    defaultChoose: 2,
                    detailImgs: [''],
                    dialType: 0,
                    enterLocation: '',
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    extraConfig: {
                      autoSendSmsCode: false,
                      autoSubmitOrder: false,
                      bulletComment: false,
                    },
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      flowNum: '10GB',
                      enableType: '立即生效',
                      enableTime: '订购立即生效',
                      flowName: '全国通用流量',
                      tips: '',
                      contractPeriod: '12个月',
                      exit: '退订次月生效',
                      subTitle: '25元霸王茶姬畅饮权益包',
                      equityTitle: '霸王茶姬畅饮权益包',
                      equityPrice: '25',
                      mainTitle: '电信-广西25元霸王茶姬畅饮权益包',
                      renewDesc: '到期自动续费',
                      detail:
                        '25元霸王茶姬畅饮权益包，该业务的资费是25元/月，包含霸王茶姬权益优惠、全国通用流量10GB。办理成功立即生效，具体权益优惠内容、流量规则详见：\\r\\n一、权益优惠内容规则：\\r\\n（一）权益内容：1*霸王茶姬12元代金券、1*霸王茶姬满减券(满29元减4元)、2*霸王茶姬满减券(满29元减3元)、首月办理额外赠送：伯牙绝弦大杯单品券（价值20元）。。\\r\\n（二）权益说明：代金券及满减券使用有效期、使用方式请登录霸王茶姬微信小程序查看，具体以权益官方发放到账实际说明为准，限办理的手机号码使用。\\r\\n（三）权益发放：销售品订购成功后，按自然月，每月5日前代金券及满减券自动发放至用户霸王茶姬账号，不可提现，不可挂失；权益发放需手机号码状态正常。\\r\\n二、通用流量规则：\\r\\n1.流量适用范围：手机上网流量限在中国大陆地区（不含港澳台）使用，适用于中国电信移动通信网络，不含WLAN(Wi-Fi)上网。\\r\\n2.包内流量当月有效，即当月剩余流量不可结转至下月使用。\\r\\n3.本流量包的流量仅限办理的手机号码使用。\\r\\n4.流量抵扣顺序：定向流量包、适用畅享视频流量包、赠送闲时流量、闲时流量包、非账单支付假日流量包、1天流量包、2天流量包、3天流量包、5天流量包、7天流量包、30天流量包、畅聊流量包、后向全国流量月包、赠送全国流量、5G升级会员包流量、套餐内全国流量、非账单支付流量加餐包、流量加餐包、包月流量包、后向全国流量季包、非账单支付季/半年/年包流量、季/半年/年包流量、5G升级会员包流量（适用畅享）、适用畅享提速包，超出后执行套外流量资费。（本包流量处于套餐内全国流量前）\\r\\n5.流量包的包内流量及月基本费，不计入套餐外流量封顶及费用封顶值计算。\\r\\n三、套餐有效期：12个月，自订购之日起算。如到期未退订或变更的，套餐有效期自动续展12个月，以此类推，续展次数不限，直至办理退订或变更。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，则业务自动终止，双方互不承担违约责任。\\r\\n四、业务规则\\r\\n（一）订购适用范围：全国通用流量10GB流量适用于广西电信除爽卡外的天翼手机套餐用户办理；霸王茶姬权益适用于广西电信天翼新老手机用户订购。\\r\\n（二）生效方式：订购立即生效。\\r\\n（三）过渡期资费：订购首月功能费全收，包内业务量全送。\\r\\n（四）包内权益主副卡不共享，副卡可单独订购。\\r\\n（五）重复订购规则：不支持重复订购。\\r\\n（六）变更、退订规则：不支持变更，允许退订，退订次月生效，退订当月已收取费用不再退回。活动期内，权益包、流量包、流量减免包为组合销售，相互依赖，不可单独订购或取消其中单个产品，三款产品需同时订购、同时取消。\\r\\n（七）退订方式：登录广西电信微信公众号、前往电信营业厅、拨打4008771189或10000号办理。',
                      flowPrice: '25',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12881/101280/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    isvTitle: '25元霸王茶姬畅饮权益包（适用畅享）',
                    itemId: 105232,
                    listImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12881/101280/productImg.png',
                    logoImg: '',
                    marketingSkuTip: null,
                    marketingSkuTitle: '广西电信',
                    opCommId: '108658',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10035,
                        cnName: '测试H5',
                        createTime: '2022-11-01 09:44:23',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 95,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2022-11-01 10:33:06',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 25.0,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 27,
                    productEntryName: '权益组合包',
                    promoteScore: 0.0,
                    ranks: -10000,
                    servicePhoneType: 0,
                    skuId: 12881,
                    skuImg: '',
                    skuProps: { 合约: '10' },
                    skuUserAgreements: [
                      {
                        agreement: '',
                        agreementName: '用户服务协议、隐私协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 2,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11382,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                      {
                        agreement: '',
                        agreementName: '业务受理协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 2,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11383,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                    ],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 0,
                    taobaoProductId: '',
                    taobaoProducts: [{ productId: '952828929113', enterName: 'czjgy' }],
                    templateType: 1,
                    tip: '',
                    tipTemplate: null,
                    title: '电信-广西25元霸王茶姬畅饮权益包（适用畅享）',
                  },
                ],
                title: '电信-广西25元霸王茶姬畅饮权益包',
              },
            ],
            smsLength: 6,
            success: true,
            tabId: 1,
          },
        ],
        status: 1,
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };

  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        blackList: false,
        categoryPackageList: [],
        hasProduct: true,
        marketingFlag: true,
        msg: '有商品',
        noProduct: false,
        operatorCode: 3,
        phoneNumber: '177ahhbia61',
        provinceId: 45,
        provinceName: '广西',
        provinceOperatorName: '广西电信',
        showPackageInfo: null,
        showPackageList: [
          {
            categoryId: 1,
            detailImg: '',
            firstPriority: -10000,
            frontExtInfo: {
              // isIframe: 1,
            },
            headerImg: '',
            marketingFlag: true,
            marketingTitle: '广西电信测试',
            packageId: 1005193,
            packageMutexGroups: '',
            priority: 1,
            productAttributes: 0,
            productEntryId: 0,
            productId: '',
            quotaLimit: 1,
            routeGroup: '',
            sendSms: true,
            showItemList: [
              {
                detailImg: '',
                formInfo: null,
                hideType: 0,
                indexImg: '',
                itemId: 105231,
                listImg: '',
                maxShowSkuNum: 10,
                optional: true,
                packagerId: 0,
                skuRanks: 0,
                skus: [
                  {
                    opCommId: '1232',
                    agreementName: '业务受理协议',
                    agreementNameSuffix: '及页面规则',
                    agreementShowLimit: 1,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12770/101276/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 0,
                    channelBrand: '',
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10035,
                    confInfo: null,
                    defaultChoose: 2,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12770/101276/ruleImg.png',
                    ],
                    dialType: 0,
                    enterLocation: '',
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    extraConfig: {
                      autoSendSmsCode: false,
                      autoSubmitOrder: false,
                      bulletComment: false,
                    },
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      exit: '退订次月生效',
                      flowNum: '10GB',
                      subTitle: '20元//月',
                      enableType: '办理立即生效',
                      mainTitle: '20元霸王茶姬轻享权益包',
                      renewDesc: '期内不取消自动续费',
                      detail:
                        '20元霸王茶姬轻享权益包，该业务的资费是20元/月，包含霸王茶姬权益优惠、全国通用流量10GB。办理成功立即生效，具体权益优惠内容、流量规则详见：\r\n一、权益优惠内容规则：\r\n（一）权益内容：1*霸王茶姬10元代金券、1*霸王茶姬满减券(满29元减4元)、1*霸王茶姬满减券(满29元减3元)、首月办理额外赠送伯牙绝弦中杯单品券（价值16元）。\r\n（二）权益说明：代金券及满减券使用有效期、使用方式请登录霸王茶姬微信小程序查看，具体以权益官方发放到账实际说明为准，限办理的手机号码使用。\r\n（三）权益发放：销售品订购成功后，按自然月，每月5日前代金券及满减券自动发放至用户霸王茶姬账号，不可提现，不可挂失；权益发放需手机号码状态正常。\r\n二、通用流量规则：\r\n1.流量适用范围：手机上网流量限在中国大陆地区（不含港澳台）使用，适用于中国电信移动通信网络，不含WLAN(Wi-Fi)上网。\r\n2.包内流量当月有效，即当月剩余流量不可结转至下月使用。\r\n3.本流量包的流量仅限办理的手机号码使用。\r\n4.流量抵扣顺序：定向流量包、适用畅享视频流量包、赠送闲时流量、闲时流量包、非账单支付假日流量包、1天流量包、2天流量包、3天流量包、5天流量包、7天流量包、30天流量包、畅聊流量包、后向全国流量月包、赠送全国流量、5G升级会员包流量、套餐内全国流量、非账单支付流量加餐包、流量加餐包、包月流量包、后向全国流量季包、非账单支付季/半年/年包流量、季/半年/年包流量、5G升级会员包流量（适用畅享）、适用畅享提速包，超出后执行套外流量资费。（本包流量处于套餐内全国流量前）\r\n5.流量包的包内流量及月基本费，不计入套餐外流量封顶及费用封顶值计算。\r\n三、套餐有效期：12个月，自订购之日起算。如到期未退订或变更的，套餐有效期自动续展12个月，以此类推，续展次数不限，直至办理退订或变更。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，则业务自动终止，双方互不承担违约责任。\r\n四、业务规则\r\n（一）订购适用范围：全国通用流量10GB流量适用于广西电信除爽卡外的天翼手机套餐用户办理；霸王茶姬权益适用于广西电信天翼新老手机用户订购。\r\n（二）生效方式：订购立即生效。\r\n（三）过渡期资费：订购首月功能费全收，包内业务量全送。\r\n（四）包内权益主副卡不共享，副卡可单独订购。\r\n（五）重复订购规则：不支持重复订购。\r\n（六）变更、退订规则：不支持变更，允许退订，退订次月生效，退订当月已收取费用不再退回。\r\n（七）退订方式：登录广西电信微信公众号、前往电信营业厅、拨打4008771189或10000号办理。',
                      flowName: '全国通用流量',
                      tips: '',
                      flowPrice: '20元',
                      contractPeriod: '12个月',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12770/101276/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    isvTitle: '霸王茶姬轻享权益包20元',
                    itemId: 105231,
                    listImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/12770/101276/productImg.png',
                    logoImg: '',
                    marketingSkuTip: null,
                    marketingSkuTitle: '20元霸王茶姬轻享权益包',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10035,
                        cnName: '测试H5',
                        createTime: '2022-11-01 09:44:23',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 95,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2022-11-01 10:33:06',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 20.0,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 27,
                    productEntryName: '权益组合包',
                    promoteScore: 0.0,
                    ranks: -10000,
                    servicePhoneType: 0,
                    skuId: 12881,
                    skuImg: '',
                    skuProps: {
                      合约: '5',
                    },
                    skuUserAgreements: [
                      {
                        agreement: '',
                        agreementName: '业务受理协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 2,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11388,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                      {
                        agreement: '',
                        agreementName: '用户服务协议、隐私协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 2,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11389,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                    ],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 0,
                    taobaoProductId: '',
                    taobaoProducts: [],
                    templateType: 1,
                    tip: '',
                    tipTemplate: null,
                    title: '电信-广西霸王茶姬轻享权益包20元',
                  },
                ],
                title: '电信-广西20元霸王茶姬轻享权益包',
              },
            ],
            smsLength: 6,
            success: true,
            tabId: 1,
          },
        ],
        status: 1,
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
  // return {
  //   code: 200,
  //   data: {
  //     dataList: [],
  //     dataMap: {
  //       blackList: false,
  //       categoryPackageList: [],
  //       hasProduct: true,
  //       marketingFlag: true,
  //       msg: '有商品',
  //       noProduct: false,
  //       operatorCode: 3,
  //       phoneNumber: '177hgabee76',
  //       provinceId: 45,
  //       provinceName: '广西',
  //       provinceOperatorName: '广西电信',
  //       showPackageInfo: null,
  //       showPackageList: [
  //         {
  //           categoryId: 1,
  //           detailImg: '',
  //           firstPriority: 99999999,
  //           frontExtInfo: {},
  //           headerImg: '',
  //           marketingFlag: true,
  //           marketingTitle: '特惠流量',
  //           packageId: 1004589,
  //           packageMutexGroups: '',
  //           priority: 1,
  //           productAttributes: 0,
  //           productEntryId: 0,
  //           productId: '',
  //           quotaLimit: 0,
  //           routeGroup: '',
  //           sendSms: true,
  //           showItemList: [
  //             {
  //               detailImg: '',
  //               formInfo: null,
  //               hideType: 0,
  //               indexImg: '',
  //               itemId: 104497,
  //               listImg: '',
  //               maxShowSkuNum: 10,
  //               optional: true,
  //               packagerId: 0,
  //               skuRanks: 0,
  //               skus: [
  //                 {
  //                   agreementName: '隐私协议、服务协议',
  //                   agreementNameSuffix: '及页面规则',
  //                   agreementShowLimit: 1,
  //                   buttonImg: '',
  //                   buttonText: '立即办理',
  //                   category: '',
  //                   categoryId: 0,
  //                   channelBrand:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/channelSupplier/channelBrand/1000289/2/194.jpg',
  //                   channelProductMainTitle: '',
  //                   channelProductSubTitle: '',
  //                   cnId: 10034,
  //                   confInfo: null,
  //                   defaultChoose: 0,
  //                   detailImgs: [
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/21937/ruleImg.png',
  //                   ],
  //                   dialType: 0,
  //                   enterLocation: '',
  //                   errorToast: {
  //                     authErrorToast: '',
  //                     orderErrorToast: '',
  //                     sendShortMessageErrorToast: '',
  //                     tradeErrorToast: '',
  //                   },
  //                   externalLinkUrl: '',
  //                   extraConfig: {
  //                     autoSendSmsCode: false,
  //                     autoSubmitOrder: false,
  //                     bulletComment: false,
  //                   },
  //                   failurePrompt: '提交异常，请重试',
  //                   frontExtInfo: {
  //                     exit: '退订次月生效。',
  //                     flowNum: '30GB',
  //                     subTitle: '售价 20元',
  //                     enableType: '立即生效',
  //                     mainTitle: '30GB 月包',
  //                     enableTime: '当月有效',
  //                     detail:
  //                       '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
  //                     flowName: '区域流量权益月包',
  //                     tips: '',
  //                     flowPrice: '20元',
  //                     contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
  //                   },
  //                   headerImg:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/21937/headImg.png',
  //                   iconImg: '',
  //                   isReadOnly: 0,
  //                   isvTitle: '',
  //                   itemId: 104497,
  //                   listImg:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/21937/productImg.png',
  //                   logoImg: '',
  //                   marketingSkuTip: null,
  //                   marketingSkuTitle: '特惠流量',
  //                   packageItemGroupId: 0,
  //                   packageItemGroupName: '',
  //                   payChannelList: [
  //                     {
  //                       browserType: '',
  //                       channelGroup: '',
  //                       cnId: 10034,
  //                       cnName: '聚合H5',
  //                       createTime: '2022-11-01 09:44:23',
  //                       dateParams: null,
  //                       delFlag: false,
  //                       extendData: {},
  //                       iconImg: '',
  //                       id: 94,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       payType: 0,
  //                       searchValue: '',
  //                       showName: '话费支付',
  //                       timeParams: null,
  //                       updateTime: '2024-12-25 10:40:24',
  //                     },
  //                   ],
  //                   payType: 0,
  //                   pluginBackgroundImg: '',
  //                   pluginProductImg: '',
  //                   pocTitle: '',
  //                   pocTitleTwo: '',
  //                   price: 20.0,
  //                   productAttributes: 19,
  //                   productAttributesName: '充流量',
  //                   productEntryId: 24,
  //                   productEntryName: '短期包',
  //                   promoteScore: 0.0,
  //                   ranks: 1,
  //                   servicePhoneType: 0,
  //                   skuId: 11926,
  //                   skuImg: '',
  //                   skuProps: {
  //                     合约: '12',
  //                   },
  //                   skuUserAgreements: [
  //                     {
  //                       agreement: '',
  //                       agreementName: '隐私协议、服务协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 1,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11178,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                     {
  //                       agreement: '',
  //                       agreementName: '业务受理协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 1,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11179,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                     {
  //                       agreement: '',
  //                       agreementName: '业务受理协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11184,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                     {
  //                       agreement: '',
  //                       agreementName: '隐私协议、服务协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11185,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                   ],
  //                   submitOrderLinkConfigLinkType: 0,
  //                   submitOrderLinkConfigLinkUrl: '',
  //                   submitOrderLinkConfigWindowText: '',
  //                   supplierServicePhone: '4000002967',
  //                   tabId: 0,
  //                   taobaoProductId: '',
  //                   taobaoProducts: [],
  //                   templateType: 1,
  //                   tip: '亲，您即将办理【综合出行权益包20元】产品资费\r\n名称:综合出行权益包20元\r\n资费说明:20元/月，含出行权益N选1。\r\n1.权益内容:滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n价格:20元/月\r\n合约期:\r\n(1)本套餐合约期12个月，自业务开通当月起计算。\r\n(2)合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。\r\n(3)合约期内客户因退订、拆机、变更等原因需要提前解约的情形，解约后须按如下规则支付违约金，违约金=20元x未完成的合约月份数，违约金最高封顶三个月，入网首月和合约到期当月取消不计算违约金。\r\n使用规则\r\n1、同一号码不可重复订购\r\n2、可选包订购当月月基本费全额计扣，包内权益全额提供\r\n3、不支持变更，允许退订，退订次月生效，退\r\n订当月已收取费用不再退回，包内有效至当月月底。\r\n温馨提示\r\n办理成功立即生效，会有短信通知您开通结果，请您注意查收',
  //                   tipTemplate: null,
  //                   title: '电信-广西20元综合出行权益',
  //                 },
  //               ],
  //               title: '电信-广西20元综合出行权益',
  //             },
  //           ],
  //           smsLength: 6,
  //           success: true,
  //           tabId: 1,
  //         },
  //         {
  //           categoryId: 1,
  //           detailImg: '',
  //           firstPriority: 99999999,
  //           frontExtInfo: {
  //             excludeProvinces: [13, 22, 23, 31, 32, 33, 34, 35, 36, 37, 42, 43, 44, 50, 53, 54, 61, 62, 64, 65],
  //           },
  //           headerImg: '',
  //           marketingFlag: true,
  //           marketingTitle: '特惠流量',
  //           packageId: 1005099,
  //           packageMutexGroups: '',
  //           priority: 1,
  //           productAttributes: 0,
  //           productEntryId: 0,
  //           productId: '',
  //           quotaLimit: 0,
  //           routeGroup: '',
  //           sendSms: true,
  //           showItemList: [
  //             {
  //               detailImg: '',
  //               formInfo: null,
  //               hideType: 0,
  //               indexImg: '',
  //               itemId: 105000,
  //               listImg: '',
  //               maxShowSkuNum: 10,
  //               optional: true,
  //               packagerId: 0,
  //               skuRanks: 0,
  //               skus: [
  //                 {
  //                   agreementName: '服务协议',
  //                   agreementNameSuffix: '。',
  //                   agreementShowLimit: 1,
  //                   buttonImg: '',
  //                   buttonText: '立即办理',
  //                   category: '',
  //                   categoryId: 0,
  //                   channelBrand: '',
  //                   channelProductMainTitle: '',
  //                   channelProductSubTitle: '',
  //                   cnId: 10034,
  //                   confInfo: null,
  //                   defaultChoose: 0,
  //                   detailImgs: [
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12542/24224/ruleImg.png',
  //                   ],
  //                   dialType: 0,
  //                   enterLocation: '',
  //                   errorToast: {
  //                     authErrorToast: '',
  //                     orderErrorToast: '',
  //                     sendShortMessageErrorToast: '',
  //                     tradeErrorToast: '',
  //                   },
  //                   externalLinkUrl: '',
  //                   extraConfig: {
  //                     autoSendSmsCode: false,
  //                     autoSubmitOrder: false,
  //                     bulletComment: false,
  //                   },
  //                   failurePrompt: '提交异常，请重试',
  //                   frontExtInfo: {
  //                     subTitle: '仅需9元',
  //                     equityTitle: '通信助理尊享版',
  //                     mainTitle: '通信助理尊享版',
  //                     cornerIcon: '天翼通信',
  //                     detail:
  //                       '1.通信助理尊享版9元/月业务仅针对号码归属地非江苏、山西、福建上海的中国电信手机用户，且需开通VOLTE网络。其中号码归属地为四川的仅针对60周岁以下、使用智能机且在7:00-22:59订购的用户\r\n2.用户订购通信助理尊享版9.00元/月业务，资费长期有效，订购当月按日计费，次月起按整月计费，退订当月按日计费，实际扣费以账单为准。开通失败则订单自动取消，不产生费用。\r\n3.业务开通后，前往“天翼通信助理”小程序(http://m.e114.so/KnqA )查看漏话信息及设置AI数字人。\r\n4.若已开通天翼通信助理或其他呼转类业务，可能导致服务开通失败以最终开通结果为准。手机设置的呼叫转移号码会影响通信助理尊享版9.00元/月正常使用。\r\n5.退订服务可拨打10000号\r\n6.客服热线:4000002967(服务时间:周一至周日，上午8:00至下午24:00)\r\n7.因不可抗力、技术故障等原因，我司有权根据相应情况调整或终止业务，但会提前通过公告等形式通知用户。',
  //                     flowName: '通信助理尊享版',
  //                     tips: '',
  //                     flowPrice: '售价：9元',
  //                   },
  //                   headerImg:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12542/24224/headImg.png',
  //                   iconImg: '',
  //                   isReadOnly: 0,
  //                   isvTitle: '通信助理尊享版',
  //                   itemId: 105000,
  //                   listImg:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12542/24224/productImg.png',
  //                   logoImg: '',
  //                   marketingSkuTip: null,
  //                   marketingSkuTitle: '特惠流量',
  //                   packageItemGroupId: 0,
  //                   packageItemGroupName: '',
  //                   payChannelList: [
  //                     {
  //                       browserType: '',
  //                       channelGroup: '',
  //                       cnId: 10034,
  //                       cnName: '聚合H5',
  //                       createTime: '2022-11-01 09:44:23',
  //                       dateParams: null,
  //                       delFlag: false,
  //                       extendData: {},
  //                       iconImg: '',
  //                       id: 94,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       payType: 0,
  //                       searchValue: '',
  //                       showName: '话费支付',
  //                       timeParams: null,
  //                       updateTime: '2024-12-25 10:40:24',
  //                     },
  //                   ],
  //                   payType: 0,
  //                   pluginBackgroundImg: '',
  //                   pluginProductImg: '',
  //                   pocTitle: '',
  //                   pocTitleTwo: '',
  //                   price: 9.0,
  //                   productAttributes: 19,
  //                   productAttributesName: '充流量',
  //                   productEntryId: 35,
  //                   productEntryName: '其他',
  //                   promoteScore: 0.0,
  //                   ranks: 50,
  //                   servicePhoneType: 0,
  //                   skuId: 12542,
  //                   skuImg: '',
  //                   skuProps: {
  //                     合约: '1',
  //                   },
  //                   skuUserAgreements: [
  //                     {
  //                       agreement: '',
  //                       agreementName: '服务协议',
  //                       agreementNameSuffix: '。',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11268,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 0,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                     {
  //                       agreement: '',
  //                       agreementName: '隐私政策',
  //                       agreementNameSuffix: '。',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11269,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 0,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                   ],
  //                   submitOrderLinkConfigLinkType: 0,
  //                   submitOrderLinkConfigLinkUrl: '',
  //                   submitOrderLinkConfigWindowText: '',
  //                   supplierServicePhone: '4000002967',
  //                   tabId: 0,
  //                   taobaoProductId: '',
  //                   taobaoProducts: [],
  //                   templateType: 0,
  //                   tip: '',
  //                   tipTemplate: null,
  //                   title: '电信-集团通信助理尊享版',
  //                 },
  //               ],
  //               title: '电信-集团通信助理尊享版',
  //             },
  //           ],
  //           smsLength: 6,
  //           success: true,
  //           tabId: 1,
  //         },
  //       ],
  //       status: 1,
  //       tabPackageList: [],
  //     },
  //   },
  //   msg: '成功',
  //   noOrderPlace: false,
  //   success: true,
  // };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        blackList: false,
        categoryPackageList: [],
        hasProduct: true,
        marketingFlag: true,
        msg: '有商品',
        noProduct: false,
        operatorCode: 3,
        phoneNumber: '181hdjfad22',
        provinceId: 43,
        provinceName: '湖南',
        provinceOperatorName: '湖南电信',
        showPackageInfo: null,
        showPackageList: [
          {
            categoryId: 1,
            detailImg: '',
            firstPriority: -10000,
            frontExtInfo: {},
            headerImg: '',
            marketingFlag: true,
            marketingTitle: '30元20GB月包202404',
            packageId: 1003927,
            packageMutexGroups: '',
            priority: 4,
            productAttributes: 0,
            productEntryId: 0,
            productId: '',
            quotaLimit: 3,
            routeGroup: '',
            sendSms: true,
            showItemList: [
              {
                detailImg: '',
                formInfo: null,
                hideType: 0,
                indexImg: '',
                itemId: 103774,
                listImg: '',
                maxShowSkuNum: 10,
                optional: true,
                packagerId: 0,
                skuRanks: 0,
                skus: [
                  {
                    agreementName: '订购须知',
                    agreementNameSuffix: '。',
                    agreementShowLimit: 1,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11208/101024/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 0,
                    channelBrand:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/564c80e7270ffd840dea7334b63655b942e_20250725222628.jpg',
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10080,
                    confInfo: null,
                    defaultChoose: 0,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11208/101024/ruleImg.png',
                    ],
                    dialType: 0,
                    enterLocation: '',
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    extraConfig: {
                      autoSendSmsCode: false,
                      autoSubmitOrder: false,
                      bulletComment: false,
                    },
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      exit: '可退订，次月生效',
                      flowNum: '20GB',
                      subTitle: '仅需30元',
                      enableType: '立即生效',
                      mainTitle: '20GB 月包',
                      enableTime: '可结转至次月继续使用（退订后不可结转）',
                      renewDesc: '自动续订',
                      detail:
                        '1、全国通用流量30元20G月包（主副卡共享），月基本费30元，含全国流量20GB。\r\n2、主副卡均可订购，包内流量主副卡共享，同一档位包月包不可重复订购。该流量包不具备提速功能。\r\n3、订购立即生效，按月自动续订，订购当月功能费全额计扣，流量全额提供，变更、退订、次月生效，退订后再次订购次月生效。\r\n4、包内当月剩余流量可结转至次月继续使用（退订后不可结转），次月底未使用完的结转流量清零。\r\n5、流量包内流量为国内流量，限在中国大陆境内（不含港澳台地区）使用，不含WLAN（Wi-Fi）上网。',
                      flowName: '月包',
                      crossMonth: '0',
                      tips: '',
                      flowPrice: '30元',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11208/101024/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    isvTitle: '',
                    itemId: 103774,
                    listImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/11208/101024/productImg.png',
                    logoImg: '',
                    marketingSkuTip: null,
                    marketingSkuTitle: '30元20GB月包202404',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10080,
                        cnName: '信息流H5',
                        createTime: '2024-11-19 15:45:45',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 130,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2024-11-19 15:45:51',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 30.0,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 25,
                    productEntryName: '月包',
                    promoteScore: 0.0,
                    ranks: -10000,
                    servicePhoneType: 0,
                    skuId: 11208,
                    skuImg: '',
                    skuProps: {
                      合约: '11111111111111111111',
                    },
                    skuUserAgreements: [
                      {
                        agreement: '',
                        agreementName: '订购须知',
                        agreementNameSuffix: '。',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 0,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11377,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 0,
                        timeParams: null,
                        updateTime: null,
                      },
                    ],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 0,
                    taobaoProductId: '',
                    taobaoProducts: [
                      {
                        productId: '794570378277',
                        enterName: 'czjgy',
                      },
                      {
                        productId: '30000001147001',
                        enterName: 'tbhd',
                      },
                      {
                        productId: '30000001142002',
                        enterName: 'tbhd2',
                      },
                    ],
                    templateType: 0,
                    tip: '',
                    tipTemplate: {
                      picUrl:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11208/tipTemplate/10080/tipPic.png',
                      tipTemplateFormTitle: '30元20G月包',
                      showPhoneNumber: 0,
                      ejectTiming: 1,
                    },
                    title: '电信-湖南30元20GB月包202404',
                  },
                ],
                title: '电信-湖南30元20GB月包202404',
              },
            ],
            smsLength: 4,
            success: true,
            tabId: 1,
          },
        ],
        status: 1,
        tabPackageList: [],
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
};
