const address = require('address');
const { port } = require('../../config');

const FileNameMap = {
  headImg: 'headImg.png',
  listImg: 'listImg.png',
  ruleImg: 'ruleImg.png',
  iconImg: 'iconImg.png',
};

module.exports = (req) => {
  // 如果是开发模式, 则读取public文件夹下的素材
  // const isDevelopment = true;
  const isDevelopment = false;

  const getFileByEnv = (key, defaultPath) => {
    if (isDevelopment) {
      const url = `http://${address.ip()}:${port}/static/benefit/${FileNameMap[key]}`;
      return url;
    }
    return defaultPath;
  };
  
  // return {
  //   code: 200,
  //   data: {
  //     dataList: [],
  //     dataMap: {
  //       blackList: false,
  //       categoryPackageList: [],
  //       hasProduct: true,
  //       marketingFlag: true,
  //       msg: '有商品',
  //       noProduct: false,
  //       operatorCode: 1,
  //       phoneNumber: '175ahfffe09',
  //       provinceId: 44,
  //       provinceName: '广东',
  //       provinceOperatorName: '广东联通',
  //       showPackageInfo: null,
  //       showPackageList: [
  //         {
  //           categoryId: 1,
  //           detailImg: '',
  //           firstPriority: 99999999,
  //           frontExtInfo: {
  //             isIframe: 1,
  //           },
  //           headerImg: '',
  //           marketingFlag: true,
  //           marketingTitle: '特惠流量',
  //           packageId: 1005331,
  //           packageMutexGroups: '',
  //           priority: 22,
  //           productAttributes: 0,
  //           productEntryId: 0,
  //           productId: '',
  //           quotaLimit: 0,
  //           routeGroup: '',
  //           sendSms: true,
  //           showItemList: [
  //             {
  //               detailImg: '',
  //               formInfo: null,
  //               hideType: 0,
  //               indexImg: '',
  //               itemId: 104757,
  //               listImg: '',
  //               maxShowSkuNum: 10,
  //               optional: true,
  //               packagerId: 0,
  //               skuRanks: 0,
  //               skus: [
  //                 {
  //                   agreementName: '',
  //                   agreementNameSuffix: '',
  //                   agreementShowLimit: 0,
  //                   buttonImg: '',
  //                   buttonText: '立即办理',
  //                   category: '',
  //                   categoryId: 0,
  //                   channelBrand: '',
  //                   channelProductMainTitle: '',
  //                   channelProductSubTitle: '',
  //                   cnId: 10028,
  //                   confInfo: null,
  //                   defaultChoose: 0,
  //                   detailImgs: [
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12216/22894/ruleImg.png',
  //                   ],
  //                   dialType: 0,
  //                   enterLocation: '',
  //                   errorToast: {
  //                     authErrorToast: '',
  //                     orderErrorToast: '',
  //                     sendShortMessageErrorToast: '',
  //                     tradeErrorToast: '',
  //                   },
  //                   externalLinkUrl: '',
  //                   extraConfig: {
  //                     autoSendSmsCode: false,
  //                     autoSubmitOrder: false,
  //                     bulletComment: false,
  //                   },
  //                   failurePrompt: '提交异常，请重试',
  //                   frontExtInfo: {
  //                     exit: '可退订，合约期内退订需支付履行完月份*6元金额作为违约金',
  //                     flowNum: '5GB',
  //                     subTitle: '售价：14元',
  //                     enableType: '立即生效，合约期12个月',
  //                     mainTitle: '5GB 生活权益流量月包',
  //                     renewDesc: '每月自动续订，自动扣费',
  //                     detail:
  //                       '20元畅付优享生活权益流量组合包（广东）-立即生效\r\n可用范围：流量全国通用（不含港澳台）\r\n生效方式：立即生效，合约期12个月\r\n续订说明：每月自动续订，自动扣费\r\n退订说明：可退订，合约期内退订需支付履行完月份*6元金额作为违约金\r\n扣费规则：前12个月14元/月（12月后恢复20元/月）\r\n到账说明：流量自动到账，权益可通过 https://u.10010.cn/qAvMe 或登录"中国联通APP-老用户专区-领会员"进行领取。\r\n\r\n详情规则\r\n一、产品订购说明\r\n1、产品内容：每月享1款权益资源+5GB国内通用流量月包。\r\n2、权益内容（N选1）：14元商超便利微信立减金、14元餐饮微信立减金、14元药店微信立减金、14元小猪胖胖微信立减金、瑞幸咖啡29元饮品券、奈雪の茶20元代金券、百果园20元、库迪咖啡26元饮品代金券、美团外卖红包10元、腾讯视频会员月卡、爱奇艺黄金会员月卡、优酷会员月卡、bi1ibili会员月卡、芒果TV会员月卡、QQ音乐绿钻豪华版月卡、网易云音乐黑胶月卡、喜马拉雅vip月卡、懒人听书vip会员月卡、饿了么超级吃货月卡、贝乐虎儿歌视频会员月卡、作业帮会员月卡、青柠单车月卡、美团单车月卡（30天30次卡）、哈啰单车月卡、WPS超级会员月卡、掌阅VIP月卡、百度网盘VIP会员月卡、知乎盐选会员月卡、洪恩思维月卡（ 38天）、洪恩识字VIP月卡（ 38天）。\r\n3、适用用户：广东联通手机用户 (达量降速套餐、4G全国流量王8元套餐除外)。\r\n4、互斥关系：单个产品不可重复订购\r\n5、计费规则：前12个月14元/月，12个月后恢复20元/月。\r\n6、生效规则：订购后立即生效，并从话费中扣取产品资费，次月1日自动续订并扣费。\r\n7、活动规则：\r\n（1）该产品有合约期，合约期12个月，合约期内可享受产品资费减免6元，即14元/月，合约期结束后恢复原价。\r\n（2）合约期额外赠送“畅付优享叠加送”权益，即每月可额外领取一个【美团外卖红包88元】（该权益不定期更新，具体权益和兑换方式会根据合作方变动进行调整，以权益领取页面展示为准）。\r\n二、产品使用说明\r\n1、权益规则\r\n（1）到账方式：1款自选权益，每月需用户手动领取使用。领取路径：权益可通过 https://u.10010.cn/qAvMe ，或登录"中国联通APP-老用户专区-领会员"进行领取。所有权益仅限订购手机号码本机使用。\r\n（2）权益使用说明：具体以当期领取兑换页面显示为准。\r\n（3）具体可兑换权益和权益兑换方式会根据合作方变动进行调整，具体以权益领取页面展示为准。权益兑换价格以当期页面显示为准，具体权益的价格会因当期合作方合作情况动态调整，期间产生的兑换差额不做补退。\r\n2、流量详细规则\r\n（1）5GB流量月包，全国通用（不包含港澳台地区），每月自动充值到账。\r\n（2）流量不可结转，与现有各类流量包均不互斥，超出流量按号码主套餐资费执行，须服从流量封顶统一限制。\r\n（3）主卡订购产品副卡可共享流量，副卡订购主卡不可共享流量。如退订，流量有效期截止到当月底。\r\n（4）使用顺序：定向流量包/闲时流量包之后，主套餐流量之前。\r\n（5）5G速率：享受5G下行峰值300Mbps速率服务。\r\n①用户实际体验速率受网络环境、用户位置、同一时间上网用户数、终端、业务等因素的影响可能会低于最高速率。\r\n②有流量封顶限制（如: 达到40GB、100GB后系统自动关闭数据网络）的用户，封顶前订购该产品，计算套餐封顶阀值时该产品包含的5G通用流量不计入套内流量，封顶后订购，系统不会自动为用户解除流量封顶限制。\r\n3、其他说明\r\n与合作方联合开展合作的权益产品，如遇合作伙伴合作提前结束，为保障客户的合法权益我司将通过公告的形式提前告知客户产品合作结束。\r\n三、退订说明：\r\n（1）退订约束：合约期内退订需支付履行完月份*6元金额作为违约金。\r\n（2）退订路径：请前往线下营业厅咨询退订。\r\n（3）失效时间：退订次月生效，次月起不再收费。产品退订后，流量有效期至当月最后一日23:59:59后自动失效。',
  //                     flowName: '流量权益月包',
  //                     tips: '',
  //                     flowPrice: '售价：14元',
  //                     contractPeriod: '合约期12个月',
  //                   },
  //                   headerImg:
  //                     'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12216/22894/headImg.png',
  //                   iconImg: '',
  //                   isReadOnly: 0,
  //                   isvTitle: '',
  //                   itemId: 104757,
  //                   listImg: '',
  //                   logoImg: '',
  //                   marketingSkuTip: null,
  //                   marketingSkuTitle: '特惠流量',
  //                   packageItemGroupId: 0,
  //                   packageItemGroupName: '',
  //                   payChannelList: [
  //                     {
  //                       browserType: '',
  //                       channelGroup: '',
  //                       cnId: 10028,
  //                       cnName: '聚杰H5',
  //                       createTime: '2022-11-01 09:44:23',
  //                       dateParams: null,
  //                       delFlag: false,
  //                       extendData: {},
  //                       iconImg: '',
  //                       id: 88,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       payType: 0,
  //                       searchValue: '',
  //                       showName: '话费支付',
  //                       timeParams: null,
  //                       updateTime: '2022-11-01 10:33:06',
  //                     },
  //                   ],
  //                   payType: 0,
  //                   pluginBackgroundImg: '',
  //                   pluginProductImg: '',
  //                   pocTitle: '',
  //                   pocTitleTwo: '',
  //                   price: 20.0,
  //                   productAttributes: 19,
  //                   productAttributesName: '充流量',
  //                   productEntryId: 27,
  //                   productEntryName: '权益组合包',
  //                   promoteScore: 0.0,
  //                   ranks: 3,
  //                   servicePhoneType: 0,
  //                   skuId: 11831,
  //                   skuImg: '',
  //                   skuProps: {
  //                     合约: '1',
  //                   },
  //                   skuUserAgreements: [
  //                     {
  //                       agreement: '',
  //                       agreementName: '业务受理协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11184,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                     {
  //                       agreement: '',
  //                       agreementName: '隐私协议、服务协议',
  //                       agreementNameSuffix: '及页面规则',
  //                       cnId: 0,
  //                       createTime: null,
  //                       dateParams: null,
  //                       defaultChoose: 0,
  //                       delFlag: false,
  //                       enable: false,
  //                       enterId: 0,
  //                       extendData: {},
  //                       id: 11185,
  //                       isAsc: '',
  //                       orderByColumn: '',
  //                       searchValue: '',
  //                       showLimit: 0,
  //                       skuId: 0,
  //                       templateType: 1,
  //                       timeParams: null,
  //                       updateTime: null,
  //                     },
  //                   ],
  //                   submitOrderLinkConfigLinkType: 0,
  //                   submitOrderLinkConfigLinkUrl: '',
  //                   submitOrderLinkConfigWindowText: '',
  //                   supplierServicePhone: '4000002967',
  //                   tabId: 0,
  //                   taobaoProductId: '',
  //                   taobaoProducts: [],
  //                   templateType: 0,
  //                   tip: '',
  //                   tipTemplate: null,
  //                   title: '联通-广东20元畅付优享生活权益流量组合包',
  //                 },
  //               ],
  //               title: '联通-广东20元畅付优享生活权益流量组合包',
  //             },
  //           ],
  //           smsLength: 6,
  //           success: true,
  //           tabId: 1,
  //         },
  //       ],
  //       status: 1,
  //       tabPackageList: [],
  //     },
  //   },
  //   msg: '成功',
  //   noOrderPlace: false,
  //   success: true,
  // };

  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        categoryPackageList: [],
        hasProduct: true,
        marketingFlag: true,
        msg: '有商品',
        noProduct: false,
        operatorCode: 2,
        phoneNumber: '152ihfbbh19',
        provinceId: 53,
        provinceName: '云南',
        provinceOperatorName: '云南移动',
        showPackageInfo: null,
        showPackageList: [
          {
            categoryId: 1,
            detailImg: '',
            firstPriority: -10000,
            frontExtInfo: {},
            headerImg: '',
            marketingFlag: true,
            marketingTitle: '产品链接',
            packageId: 1002934,
            packageMutexGroups: '',
            priority: 1,
            productAttributes: 0,
            productEntryId: 0,
            productId: '',
            quotaLimit: 1,
            routeGroup: '',
            sendSms: true,
            showItemList: [
              {
                detailImg: '',
                formInfo: null,
                hideType: 0,
                indexImg: '',
                itemId: 105131,
                listImg: '',
                maxShowSkuNum: 10,
                optional: true,
                packagerId: 0,
                skuRanks: 0,
                skus: [
                  {
                    isvTitle: '我是运营商商品名称',
                    enterLocation: '来源编码', // 为电信集团特意搞的字段 https://devops.aliyun.com/projex/req/MTDJ-6034# 《电信集团-MCN渠道—权益订购页面埋点&同步》
                    agreementName: '',
                    agreementNameSuffix: '',
                    agreementShowLimit: 0,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 1,
                    channelBrand:
                      'https://jujie-test.oss-cn-hangzhou.aliyuncs.com/upload/channelSupplier/channelBrand/1000329/0/22.jpg',
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10081,
                    confInfo: null,
                    defaultChoose: 0,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/ruleImg.png',
                    ],
                    dialType: 0,
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      tips: '',
                      flowName: '当月有效',
                      feeName: '100 话费',
                      equityTitle: '芒果会员',
                      cornerIcon: '啊啊啊啊啊啊',
                      subTitle: '送视频会员',
                      mainTitle: '15GB',
                      range: '这是什么',
                      exit: '退订次月生效。',
                      enableType: '立即生效',
                      enableTime: '当月有效',
                      detail:
                        '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
                      tips: '',
                      flowPrice: '20',
                      contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    itemId: 104822,
                    listImg: 'https://img.temp.im/750x1/ffad66/ffffff',
                    logoImg: '',
                    marketingSkuTip: {
                      cancelButtonText: '确认取消',
                      cancelButtonType: 0,
                      confirmButtonSize: 100,
                      confirmButtonText: '确认订购',
                      confirmButtonType: 0,
                      createTime: '2025-03-11 18:08:42',
                      dateParams: null,
                      delFlag: false,
                      ejectTiming: 1,
                      enterId: 0,
                      extendData: {},
                      id: 62,
                      isAsc: '',
                      itemId: 104822,
                      marketingId: 101070,
                      marketingSkuTipType: 'MARKETING_SKU_TIP',
                      operUserId: 174,
                      orderByColumn: '',
                      packageId: 1004899,
                      searchValue: '',
                      showCloseButton: 1,
                      showPhone: 0,
                      showSecondConfirm: false,
                      showSecondConfirmText: '',
                      showServicePhone: 1,
                      skuId: 12306,
                      timeParams: null,
                      tipBackground:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipBackgroundFile.png',
                      tipDetailPic:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipDetailPicFile.png',
                      tipStatus: true,
                      tipText:
                        '<h4><span style="color: rgb(0, 0, 0);">您即将订购：</span></h4><h4><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-size: 13px;">19.9元流量包-头条抖音（首月五折优惠活动）</span></h4><h4><span style="color: rgb(0, 0, 0);">每月可享25GB定向流量、5GB国内通用流量，以上流量均不含港澳台地区，流量月底清零、不可共享或转赠，不具备提速功能。定向流量免流范围可发送SYFW至10086查询。</span></h4><h4><span style="color: rgb(0, 0, 0);">（首月5折）19.9元定向流量包，订购首月为9.9元/月，第二个月起恢复原价19.9元/月，办理后立即生效，即为您的在网开始时间，合约期24个月。</span></h4>',
                      tipTitle: '19.9元流量包-头条抖音-首月五折优惠',
                      tipType: 0,
                      titleColor: '#ffffff',
                      topIcon: '',
                      updateTime: '2025-03-21 15:42:40',
                    },
                    marketingSkuTip: {
                      cancelButtonText: '残忍拒绝',
                      cancelButtonType: 3,
                      confirmButtonSize: 120,
                      confirmButtonText: '确认订购',
                      confirmButtonType: 1,
                      createTime: '2025-04-01 14:07:29',
                      dateParams: null,
                      delFlag: false,
                      ejectTiming: 0,
                      enterId: 0,
                      extendData: {},
                      id: 174,
                      isAsc: '',
                      itemId: 102358,
                      marketingId: 101123,
                      marketingSkuTipType: 'MARKETING_SKU_TIP',
                      operUserId: 112,
                      orderByColumn: '',
                      packageId: 1002483,
                      searchValue: '',
                      showCloseButton: 1,
                      showPhone: 2,
                      showSecondConfirm: true,
                      showSecondConfirmText:
                        '说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊说点啥啊啊啊啊',
                      showServicePhone: 1,
                      skuId: 9499,
                      timeParams: null,
                      tipBackground:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101123/1002483/102358/9499/tipBackgroundFile.png',
                      tipDetailPic:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipDetailPicFile.png',
                      tipStatus: true,
                      tipText:
                        '<p>测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案，测试文案。</p>',
                      tipTitle: '',
                      tipType: 1,
                      titleColor: '',
                      topIcon: '',
                      updateTime: '2025-04-01 14:07:29',
                    },
                    marketingSkuTitle: '产品链接',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 19.9,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 25,
                    productEntryName: '月包',
                    promoteScore: 0.0,
                    ranks: 2,
                    servicePhoneType: 0,
                    skuId: 12651,
                    skuImg: '',
                    skuProps: {
                      合约: '1',
                    },
                    skuUserAgreements: [
                      {
                        agreement: '',
                        agreementName: '业务受理协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 0,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11184,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                      {
                        agreement: '',
                        agreementName: '隐私协议、服务协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 0,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11185,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                    ],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 1,
                    taobaoProductId: '',
                    taobaoProducts: [],
                    templateType: 0,
                    tip: '',
                    tipTemplate: {
                      picUrl:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/tipTemplate/10081/tipPic.png',
                      tipTemplateFormTitle: '19.9元流量包',
                      showPhoneNumber: 1,
                      ejectTiming: 1,
                    },
                    title: '移动-云南19.9元流量包-头条抖音（首月五折优惠活动）',
                  },
                  {
                    extraConfig: {
                      autoSendSmsCode: true,
                      autoSubmitOrder: true,
                      bulletComment: true,
                    },
                    agreementName: '',
                    agreementNameSuffix: '',
                    agreementShowLimit: 0,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 1,
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10081,
                    confInfo: null,
                    defaultChoose: 1,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/ruleImg.png',
                    ],
                    dialType: 0,
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      detail:
                        '一、活动时间：2022年6月21日-2025年12月31日\r\n二、（首月5折）19.9元定向流量活动说明\r\n1、活动对象\r\n（1）次月生效套餐28元及以上客户可办理，活动生效期间，只能在28元及以上指定套餐范围内变更。\r\n（2）已办理该定向流量、5G特惠流量包30元5GB、原价19.9元定向流量包（黄金会员版）、（首两月5折）19.9元定向流量包（黄金会员版）的客户，不能办理（首月5折）19.9元定向流量包；如需办理，需先解约定向流量、5G特惠流量包30元5GB、原价19.9元定向流量包（黄金会员版）、（首两月5折）19.9元定向流量包（黄金会员版）后才能办理。\r\n2、（首月5折）19.9元定向流量包，订购首月为9.9元/月，第二个月起恢复原价19.9元/月，办理后立即生效，即为您的在网开始时间，合约期24个月。每月可享25GB定向流量、5GB国内通用流量，以上流量均不含港澳台地区，流量月底清零、不可共享或转赠，不具备提速功能。定向流量免流范围可发送SYFW至10086查询。\r\n3、19.9元与9.9元之间不互斥，且同一个活动中的8个档次定向范围也不互斥，即每个客户参与活动，至高可有16个档次活动在生效。\r\n4、（首月5折）定向流量活动办理立即生效，当月不能返销，可在办理第2个月到归属地沟通100营业厅或拨打10086咨询、24个月合约期内提前解约需要支付违约金，违约金为1元/月*未履约月份数，24个月合约期后退订活动，不再收取违约金。\r\n5、客户现金话费实时余额不低于产品定价才能参与活动。\r\n三、其他说明\r\n特殊优惠客户 （万能副卡、CMWAP优惠资费、CPE卡、物联网卡、同心卡、移动宝卡、流量王卡等）及同一身份证下的所有号码欠费超过150元以上（含150元） 的客户不能参与。\r\n如果您无法参与活动并提示为：存在同一证件下所有号码合计欠费超150元的情况，处理流程：由于您身份证名下所有号码自2017年至今欠费累计已超过150元（含150元），在您未缴清欠费之前，您名下的所有号码（包括正常、欠费及销号号码）无法参与公司推出的营销活动，因此，请您携带个人有效证件及时到各地沟通100服务厅缴清您身份证下（含边境身份证）所有号码的欠费（包含已销户的号码）。缴清欠费48小时后重新参与活动。\r\n四、定向流量使用优先于套餐内通用流量、基站流量、夜间流量及短期流量。\r\n五、可享权益：活动办理后您每月可享移动云盘空间月卡、咪咕视频会员月卡、韵达50元好礼寄件券、高德100元打车券包权益4选1(因权益方内部调整，我们可能会变更、终止与权益方提供的产品，届时会为您提供其他权益产品），每月您可以至中国移动APP-我的-我的权益处领取。为给您提供更好的服务，每月最后3天前若您还未领取任一权益，则我们将每月为您提供一款生活权益（权益内容以系统下发为准），该权益不收取费用，后期会根据与权益方合作情况不定期的对该权益进行调整或终止。',
                      tips: '',
                      mainTitle: '啊啊啊啊啊啊',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/headImg.png',
                    headerImg: 'https://img.temp.im/750x780/999999/ffffff',
                    iconImg: '',
                    isReadOnly: 0,
                    itemId: 104822,
                    listImg: 'https://img.temp.im/750x1/ab3939/ffffff',
                    logoImg: '',
                    marketingSkuTip: {
                      cancelButtonText: '确认取消',
                      cancelButtonType: 0,
                      confirmButtonSize: 100,
                      confirmButtonText: '确认订购',
                      confirmButtonType: 0,
                      createTime: '2025-03-11 18:08:42',
                      dateParams: null,
                      delFlag: false,
                      ejectTiming: 1,
                      enterId: 0,
                      extendData: {},
                      id: 62,
                      isAsc: '',
                      itemId: 104822,
                      marketingId: 101070,
                      marketingSkuTipType: 'MARKETING_SKU_TIP',
                      operUserId: 174,
                      orderByColumn: '',
                      packageId: 1004899,
                      searchValue: '',
                      showCloseButton: 1,
                      showPhone: 0,
                      showSecondConfirm: false,
                      showSecondConfirmText: '',
                      showServicePhone: 1,
                      skuId: 12306,
                      timeParams: null,
                      tipBackground:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipBackgroundFile.png',
                      tipDetailPic:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipDetailPicFile.png',
                      tipStatus: true,
                      tipText:
                        '<h4><span style="color: rgb(0, 0, 0);">您即将订购：</span></h4><h4><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-size: 13px;">19.9元流量包-头条抖音（首月五折优惠活动）</span></h4><h4><span style="color: rgb(0, 0, 0);">每月可享25GB定向流量、5GB国内通用流量，以上流量均不含港澳台地区，流量月底清零、不可共享或转赠，不具备提速功能。定向流量免流范围可发送SYFW至10086查询。</span></h4><h4><span style="color: rgb(0, 0, 0);">（首月5折）19.9元定向流量包，订购首月为9.9元/月，第二个月起恢复原价19.9元/月，办理后立即生效，即为您的在网开始时间，合约期24个月。</span></h4>',
                      tipTitle: '19.9元流量包-头条抖音-首月五折优惠',
                      tipType: 1,
                      titleColor: '#ffffff',
                      topIcon: '',
                      updateTime: '2025-03-21 15:42:40',
                    },
                    marketingSkuTitle: '产品链接',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10081,
                        cnName: '信息流测试H5',
                        createTime: '2024-11-19 15:45:45',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 131,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2024-11-19 15:45:51',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 19.9,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 25,
                    productEntryName: '月包',
                    promoteScore: 0.0,
                    ranks: 1,
                    servicePhoneType: 0,
                    skuId: 12307,
                    skuImg: '',
                    skuProps: {
                      合约: '1',
                    },
                    skuUserAgreements: [
                      {
                        agreement: '',
                        agreementName: '业务受理协议',
                        agreementNameSuffix: '及页面规则',
                        cnId: 0,
                        createTime: null,
                        dateParams: null,
                        defaultChoose: 0,
                        delFlag: false,
                        enable: false,
                        enterId: 0,
                        extendData: {},
                        id: 11184,
                        isAsc: '',
                        orderByColumn: '',
                        searchValue: '',
                        showLimit: 0,
                        skuId: 0,
                        templateType: 1,
                        timeParams: null,
                        updateTime: null,
                      },
                    ],
                    skuUserAgreements: [],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 1,
                    taobaoProductId: '',
                    taobaoProducts: [],
                    templateType: 0,
                    tip: '',
                    tipTemplate: {
                      picUrl:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/tipTemplate/10081/tipPic.png',
                      tipTemplateFormTitle: '19.9元流量包',
                      showPhoneNumber: 1,
                      ejectTiming: 1,
                    },
                    title: '移动-云南19.9元流量包-头条抖音（首月五折优惠活动）',
                  },
                  {
                    agreementName: '',
                    agreementNameSuffix: '',
                    agreementShowLimit: 0,
                    buttonImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/buttonImg.png',
                    buttonText: '立即办理',
                    category: '',
                    categoryId: 1,
                    channelProductMainTitle: '',
                    channelProductSubTitle: '',
                    cnId: 10081,
                    confInfo: null,
                    defaultChoose: 0,
                    detailImgs: [
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/ruleImg.png',
                    ],
                    dialType: 0,
                    errorToast: {
                      authErrorToast: '',
                      orderErrorToast: '',
                      sendShortMessageErrorToast: '',
                      tradeErrorToast: '',
                    },
                    externalLinkUrl: '',
                    failurePrompt: '提交异常，请重试',
                    frontExtInfo: {
                      detail:
                        '一、活动时间：2022年6月21日-2025年12月31日\r\n二、（首月5折）19.9元定向流量活动说明\r\n1、活动对象\r\n（1）次月生效套餐28元及以上客户可办理，活动生效期间，只能在28元及以上指定套餐范围内变更。\r\n（2）已办理该定向流量、5G特惠流量包30元5GB、原价19.9元定向流量包（黄金会员版）、（首两月5折）19.9元定向流量包（黄金会员版）的客户，不能办理（首月5折）19.9元定向流量包；如需办理，需先解约定向流量、5G特惠流量包30元5GB、原价19.9元定向流量包（黄金会员版）、（首两月5折）19.9元定向流量包（黄金会员版）后才能办理。\r\n2、（首月5折）19.9元定向流量包，订购首月为9.9元/月，第二个月起恢复原价19.9元/月，办理后立即生效，即为您的在网开始时间，合约期24个月。每月可享25GB定向流量、5GB国内通用流量，以上流量均不含港澳台地区，流量月底清零、不可共享或转赠，不具备提速功能。定向流量免流范围可发送SYFW至10086查询。\r\n3、19.9元与9.9元之间不互斥，且同一个活动中的8个档次定向范围也不互斥，即每个客户参与活动，至高可有16个档次活动在生效。\r\n4、（首月5折）定向流量活动办理立即生效，当月不能返销，可在办理第2个月到归属地沟通100营业厅或拨打10086咨询、24个月合约期内提前解约需要支付违约金，违约金为1元/月*未履约月份数，24个月合约期后退订活动，不再收取违约金。\r\n5、客户现金话费实时余额不低于产品定价才能参与活动。\r\n三、其他说明\r\n特殊优惠客户 （万能副卡、CMWAP优惠资费、CPE卡、物联网卡、同心卡、移动宝卡、流量王卡等）及同一身份证下的所有号码欠费超过150元以上（含150元） 的客户不能参与。\r\n如果您无法参与活动并提示为：存在同一证件下所有号码合计欠费超150元的情况，处理流程：由于您身份证名下所有号码自2017年至今欠费累计已超过150元（含150元），在您未缴清欠费之前，您名下的所有号码（包括正常、欠费及销号号码）无法参与公司推出的营销活动，因此，请您携带个人有效证件及时到各地沟通100服务厅缴清您身份证下（含边境身份证）所有号码的欠费（包含已销户的号码）。缴清欠费48小时后重新参与活动。\r\n四、定向流量使用优先于套餐内通用流量、基站流量、夜间流量及短期流量。\r\n五、可享权益：活动办理后您每月可享移动云盘空间月卡、咪咕视频会员月卡、韵达50元好礼寄件券、高德100元打车券包权益4选1(因权益方内部调整，我们可能会变更、终止与权益方提供的产品，届时会为您提供其他权益产品），每月您可以至中国移动APP-我的-我的权益处领取。为给您提供更好的服务，每月最后3天前若您还未领取任一权益，则我们将每月为您提供一款生活权益（权益内容以系统下发为准），该权益不收取费用，后期会根据与权益方合作情况不定期的对该权益进行调整或终止。',
                      tips: '',
                    },
                    headerImg:
                      'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/headImg.png',
                    iconImg: '',
                    isReadOnly: 0,
                    itemId: 104822,
                    listImg: 'https://img.temp.im/750x1/ffad66/ffffff',
                    logoImg: '',
                    marketingSkuTip: {
                      cancelButtonText: '确认取消',
                      cancelButtonType: 0,
                      confirmButtonSize: 100,
                      confirmButtonText: '确认订购',
                      confirmButtonType: 0,
                      createTime: '2025-03-11 18:08:42',
                      dateParams: null,
                      delFlag: false,
                      ejectTiming: 1,
                      enterId: 0,
                      extendData: {},
                      id: 62,
                      isAsc: '',
                      itemId: 104822,
                      marketingId: 101070,
                      marketingSkuTipType: 'MARKETING_SKU_TIP',
                      operUserId: 174,
                      orderByColumn: '',
                      packageId: 1004899,
                      searchValue: '',
                      showCloseButton: 1,
                      showPhone: 0,
                      showSecondConfirm: false,
                      showSecondConfirmText: '',
                      showServicePhone: 1,
                      skuId: 12306,
                      timeParams: null,
                      tipBackground:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipBackgroundFile.png',
                      tipDetailPic:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/tip/101070/1004899/104822/12306/tipDetailPicFile.png',
                      tipStatus: true,
                      tipText:
                        '<h4><span style="color: rgb(0, 0, 0);">您即将订购：</span></h4><h4><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-size: 13px;">19.9元流量包-头条抖音（首月五折优惠活动）</span></h4><h4><span style="color: rgb(0, 0, 0);">每月可享25GB定向流量、5GB国内通用流量，以上流量均不含港澳台地区，流量月底清零、不可共享或转赠，不具备提速功能。定向流量免流范围可发送SYFW至10086查询。</span></h4><h4><span style="color: rgb(0, 0, 0);">（首月5折）19.9元定向流量包，订购首月为9.9元/月，第二个月起恢复原价19.9元/月，办理后立即生效，即为您的在网开始时间，合约期24个月。</span></h4>',
                      tipTitle: '19.9元流量包-头条抖音-首月五折优惠',
                      tipType: 0,
                      titleColor: '#ffffff',
                      topIcon: '',
                      updateTime: '2025-03-21 15:42:40',
                    },
                    marketingSkuTitle: '产品链接',
                    packageItemGroupId: 0,
                    packageItemGroupName: '',
                    payChannelList: [
                      {
                        browserType: '',
                        channelGroup: '',
                        cnId: 10081,
                        cnName: '信息流测试H5',
                        createTime: '2024-11-19 15:45:45',
                        dateParams: null,
                        delFlag: false,
                        extendData: {},
                        iconImg: '',
                        id: 131,
                        isAsc: '',
                        orderByColumn: '',
                        payType: 0,
                        searchValue: '',
                        showName: '话费支付',
                        timeParams: null,
                        updateTime: '2024-11-19 15:45:51',
                      },
                    ],
                    payType: 0,
                    pluginBackgroundImg: '',
                    pluginProductImg: '',
                    pocTitle: '',
                    pocTitleTwo: '',
                    price: 19.9,
                    productAttributes: 19,
                    productAttributesName: '充流量',
                    productEntryId: 25,
                    productEntryName: '月包',
                    promoteScore: 0.0,
                    ranks: 3,
                    servicePhoneType: 0,
                    skuId: 12308,
                    skuImg: '',
                    skuProps: {
                      合约: '1',
                    },
                    skuUserAgreements: [],
                    submitOrderLinkConfigLinkType: 0,
                    submitOrderLinkConfigLinkUrl: '',
                    submitOrderLinkConfigWindowText: '',
                    supplierServicePhone: '4000002967',
                    tabId: 1,
                    taobaoProductId: '',
                    taobaoProducts: [],
                    templateType: 0,
                    tip: '',
                    tipTemplate: {
                      picUrl:
                        'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/tipTemplate/10081/tipPic.png',
                      tipTemplateFormTitle: '19.9元流量包',
                      showPhoneNumber: 1,
                      ejectTiming: 1,
                    },
                    title: '移动-云南19.9元流量包-头条抖音（首月五折优惠活动）',
                  },
                ],
                title: '移动-云南19.9元流量包-头条抖音（首月五折优惠活动）',
              },
            ],
            smsLength: 6,
            success: true,
            tabId: 1,
          },
        ],
        status: 1,
        tabPackageList: [],
      },
    },
    msg: '成功',
    success: true,
  };

  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: (() => {
        if (
          req.body.phoneNumber === '18888888888' ||
          req.body.phoneNumber === '18900000000' ||
          req.body.direction === true
        ) {
          return {
            hasProduct: false,
            msg: '不可办理',
            noProduct: true,
            operatorCode: 0,
            phoneNumber: '',
            provinceId: 0,
            provinceName: '',
            provinceOperatorName: '',
            showPackageList: [],
            status: 3,
          };
        } else {
          return {
            hasProduct: true,
            marketingFlag: true,
            msg: '有商品',
            noProduct: false,
            operatorCode: 3,
            phoneNumber: req.body.phoneNumber.replace(/^(\d{3})\d{6}(\d{2})$/, '$1******$2'),
            provinceId: 34,
            provinceName: '安徽',
            provinceOperatorName: '安徽电信',
            showPackageList: [
              {
                frontExtInfo: {
                  bookUrl: 'https://benefit.jujienet.com/benefit/INDEX/20188',
                  isIframe: 0,
                  reportEvent: 1,
                },
                headerImg: '',
                mutexGroups: '',
                packageGroup: '',
                // packageId: 1002937, // iframe
                // packageId: 1001241, // 电信集团下单按钮文案
                // packageId: 1001129, // 电信集团优酷
                // packageId: 1001470, // 山东电信
                // packageId: 1001166, // 电信集团喜马拉雅
                // packageId: 1001214, // 学军
                packageId: 1004383, // 广西电信
                // packageId: 1000967, // 电信集团增加协议
                // packageId: 1001183, // 河南电信
                // packageId: 1001589, // 湖北电信
                // packageId: 1001737, // 改变按钮文案
                // packageId: 1000967, // 电信优酷
                priority: 2,
                quotaLimit: 0,
                routeGroup: '',
                sendSms: true,
                smsLength: 4,
                showItemList: [
                  {
                    detailImg: '',
                    formInfo: null,
                    hideType: 0,
                    indexImg: '',
                    itemId: 100689,
                    listImg: '',
                    maxShowSkuNum: 10,
                    optional: true,
                    packagerId: 0,
                    skus: [
                      {
                        submitOrderLinkConfigLinkType: 2,
                        buttonText: '下单啊！',
                        productEntryName: '话费',
                        pluginProductImg:
                          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/5708/5356/icon.png',
                        // externalLinkUrl: 'https://www.bing.com',
                        agreementName: '',
                        cnId: 10005,
                        // detailImgs: [getFileByEnv('ruleImg', 'https://img.temp.im/750x400/AAA/EEE')],
                        detailImgs: ['https://img.temp.im/750x1500/ff935b/ff935b'],
                        errorToast: {
                          authErrorToast: '鉴权失败文案覆盖',
                          orderErrorToast: '下单失败啊啊啊啊',
                          sendShortMessageErrorToast: '发送验证码失败啊啊啊啊啊',
                          tradeErrorToast: '',
                        },
                        failurePrompt: '如有欠费将不能办理',
                        frontExtInfo: {
                          tips: '',
                          flowName: '当月有效',
                          feeName: '100 话费',
                          equityTitle: '芒果会员',
                          cornerIcon: '啊啊啊啊啊啊',
                          subTitle: '送视频会员',
                          mainTitle: '15GB',
                          range: '这是什么',
                          exit: '退订次月生效。',
                          enableType: '立即生效',
                          enableTime: '当月有效',
                          detail:
                            '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
                          tips: '',
                          flowPrice: '20',
                          contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
                        },
                        // headerImg: getFileByEnv('headImg', 'https://img.temp.im/750x400/666/EEE'),
                        headerImg: 'https://img.temp.im/750x500/fe5039/fe5039',
                        itemId: 100689,
                        // listImg: getFileByEnv('listImg', 'https://img.temp.im/700x320/888/EEE'),
                        listImg: 'https://img.temp.im/700x460/ffad66/ffad66',
                        marketingSkuTitle: '新标题1',
                        payType: 1,
                        payChannelList: [
                          {
                            cnId: 10042,
                            cnName: '微信支付',
                            createTime: '2022-10-28 10:53:16',
                            dateParams: null,
                            delFlag: false,
                            extendData: {},
                            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/comm/logo/wechat.png',
                            id: 64,
                            searchValue: '',
                            showName: '微信',
                            timeParams: null,
                            updateTime: '2022-10-28 11:03:46',
                          },
                          // {
                          //   cnId: 10005,
                          //   cnName: '支付宝话费宝',
                          //   createTime: '2022-10-28 10:53:16',
                          //   dateParams: null,
                          //   delFlag: false,
                          //   extendData: {},
                          //   iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/comm/logo/alipay.png',
                          //   id: 47,
                          //   searchValue: '',
                          //   showName: '支付宝',
                          //   timeParams: null,
                          //   updateTime: '2022-10-28 11:03:31',
                          // },
                        ],
                        pocTitle: '5折抢10G',
                        pocTitleTwo: '5折抢10G',
                        price: 15,
                        ranks: 1,
                        skuId: 11994,
                        skuImg: '',
                        skuProps: {
                          合约: '合约30',
                        },
                        // skuUserAgreements: [
                        //   {
                        //     agreement: '',
                        //     agreementName: '业务受理协议',
                        //     agreementNameSuffix: '及页面规则',
                        //     cnId: 0,
                        //     createTime: null,
                        //     dateParams: null,
                        //     defaultChoose: 0,
                        //     delFlag: false,
                        //     enable: false,
                        //     enterId: 0,
                        //     extendData: {},
                        //     id: 11184,
                        //     isAsc: '',
                        //     orderByColumn: '',
                        //     searchValue: '',
                        //     showLimit: 0,
                        //     skuId: 0,
                        //     templateType: 1,
                        //     timeParams: null,
                        //     updateTime: null,
                        //   },
                        //   {
                        //     agreement: '',
                        //     agreementName: '隐私协议、服务协议',
                        //     agreementNameSuffix: '及页面规则',
                        //     cnId: 0,
                        //     createTime: null,
                        //     dateParams: null,
                        //     defaultChoose: 0,
                        //     delFlag: false,
                        //     enable: false,
                        //     enterId: 0,
                        //     extendData: {},
                        //     id: 11185,
                        //     isAsc: '',
                        //     orderByColumn: '',
                        //     searchValue: '',
                        //     showLimit: 0,
                        //     skuId: 0,
                        //     templateType: 1,
                        //     timeParams: null,
                        //     updateTime: null,
                        //   },
                        // ],
                        taobaoProductId: '',
                        taobaoProducts: [],
                        title: '电信-集团10G流量包29元/月升5G，升白金会员（畅享）',
                        tip: '产品资费\r\n名称：20GB国内流量+互联网视听会员N选2\r\n价格：30元/月\r\n国内流量：20GB\r\n有效期：订购立即生效，首月资费全额计扣，次月自动续订。只能抵扣订购成功后使用的流量。\r\n使用规则\r\n变更/退订：退订次月生效\r\n重复订购：不可重复订购\r\n权益说明：权益需每月手动领取，月底前未领取视为放弃当月权益。\r\n领取方式：翼支付APP-权益专区领取。\r\n合约说明\r\n合约期：12个月， 此产品的费用不算在套餐保底消费内\r\n<RED>违约金：合约期12个月，允许退订，退订次月生效。登录"中国电信"APP可自助办理退订（查询办理>基础业务>业务退订）。\r\n协议期内提前退订，需缴纳违约金，即违约金为：30元*已订购月份。</RED>',
                        tipTemplate: {
                          picUrl:
                            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/11926/tipTemplate/10035/tipPic.png',
                          tipTemplateFormTitle: '广西20元综合出行权益',
                          showPhoneNumber: 1,
                          ejectTiming: 1,
                        },
                      },
                    ],
                    title: '电信-集团4升5（融升套入口）',
                  },
                ],
                success: true,
              },
              {
                frontExtInfo: {
                  bookUrl: 'https://benefit.jujienet.com/benefit/INDEX/20188',
                },
                headerImg: '',
                mutexGroups: '',
                packageGroup: '',
                packageId: 1001686,
                priority: 2,
                quotaLimit: 0,
                routeGroup: '',
                sendSms: true,
                smsLength: 4,
                showItemList: [
                  {
                    detailImg: '',
                    formInfo: null,
                    hideType: 0,
                    indexImg: '',
                    itemId: 100690,
                    listImg: '',
                    maxShowSkuNum: 10,
                    optional: true,
                    packagerId: 0,
                    skus: [
                      {
                        productEntryName: '话费1',
                        pluginProductImg:
                          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/5708/5356/icon.png',
                        agreementName: '12333',
                        cnId: 10005,
                        detailImgs: [
                          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/rule.png',
                        ],
                        failurePrompt: '如有欠费将不能办理',
                        frontExtInfo: {
                          tips: '',
                          flowName: '当月有效',
                          feeName: '100 话费',
                          equityTitle: '芒果会员',
                          cornerIcon: '啊啊啊啊啊啊',
                          subTitle: '送视频会员',
                          mainTitle: '15GB',
                          range: '这是什么',
                          exit: '退订次月生效。',
                          enableType: '立即生效',
                          enableTime: '当月有效',
                          detail:
                            '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
                          tips: '',
                          flowPrice: '20',
                          contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
                        },
                        headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/top.png',
                        itemId: 100690,
                        listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/icon.png',
                        marketingSkuTitle: '新标题2',
                        payType: 0,
                        pocTitle: '5折抢10G',
                        pocTitleTwo: '5折抢10G',
                        price: 24,
                        ranks: 30,
                        skuId: 5819,
                        skuImg: '',
                        skuProps: {
                          合约: '合约30',
                        },
                        taobaoProductId: '',
                        taobaoProducts: [],
                        title: '电信-集团10G流量包29元/月升5G，升白金会员（畅享）',
                        // tip: '您即将办理 99元10G流量合约包，如需继续办理请仔细阅读以下信息，请点击确认\r\n<RED>1. 30元/月  10GB流</RED>量合约包\r\n2. 协议期：12个月 。\r\n3. 主副卡分享：仅限订购号码使用，套餐不共享。\r\n4. 退订： 合约期内不可退订，第12个月可以退订。若提前退订，需要到本地自有营业厅办理，并按已享受的权益价值缴纳违约金，即30元*已订购月份。',
                        // tip: '您即将办理 99元10G流量合约包，如需继续办理请仔细阅读以下信息，请点击确认\r\n1. 30元/月  10GB流量合约包\r\n2. 协议期：12个月 。\r\n3. 主副卡分享：仅限订购号码使用，套餐不共享。\r\n4. 退订： 合约期内不可退订，第12个月可以退订。若提前退订，需要到本地自有营业厅办理，并按已享受的权益价值缴纳违约金，即30元*已订购月份。',
                      },
                    ],
                    title: '电信-集团4升5（融升套入口）',
                  },
                ],
                success: true,
              },
              {
                frontExtInfo: {
                  bookUrl: 'https://benefit.jujienet.com/benefit/INDEX/20188',
                },
                headerImg: '',
                mutexGroups: '',
                packageGroup: '',
                packageId: 1000775,
                priority: 2,
                quotaLimit: 0,
                routeGroup: '',
                sendSms: true,
                smsLength: 4,
                showItemList: [
                  {
                    detailImg: '',
                    formInfo: null,
                    hideType: 0,
                    indexImg: '',
                    itemId: 100691,
                    listImg: '',
                    maxShowSkuNum: 10,
                    optional: true,
                    packagerId: 0,
                    skus: [
                      {
                        productEntryName: '话费2',
                        pluginProductImg:
                          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/5708/5356/icon.png',
                        agreementName: '12333飒飒',
                        cnId: 10005,
                        detailImgs: [
                          'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/rule.png',
                        ],
                        failurePrompt: '如有欠费将不能办理',
                        frontExtInfo: {
                          tips: '',
                          flowName: '当月有效',
                          feeName: '100 话费',
                          equityTitle: '芒果会员',
                          cornerIcon: '啊啊啊啊啊啊',
                          subTitle: '送视频会员',
                          mainTitle: '15GB',
                          range: '这是什么',
                          exit: '退订次月生效。',
                          enableType: '立即生效',
                          enableTime: '当月有效',
                          detail:
                            '一、资费内容\r\n（一）月资费：20元/月，含出行权益。\r\n（二）出行权益：含滴滴快车代金券、国内火车票代金券、美团电单车-7天5次卡等每月N选1，权益不定期更新，具体可选权益以领取页面展示为准。\r\n二、业务规则\r\n（一）适用范围：广西电信天翼手机用户。\r\n（二）生效方式：默认立即生效，可选次月生效。\r\n（三）过渡期资费：可选包订购当月月基本费全额计扣，包内权益全额提供。\r\n（四）订购规则：不允许重复订购。\r\n（五）变更、退订规则：\r\n1.不支持变更，允许退订，退订次月生效。\r\n2.退订当月已收取费用不再退回，包内权益有效至当月月底。\r\n3.退订方式：可移步当地营业厅或拨打4008771189咨询办理退订。\r\n（六）支付方式：账单支付。\r\n三、使用说明\r\n1.权益发放：销售品订购成功，用户需每月登录翼支付APP-权益专区或““广西电信”微信公众号-天翼会员·5G权益”领取权益。每月限领1次，每次可选择领取不同权益；如果用户当月未及时领取权益，或因号码停机、欠费、翼支付账户异常或离网状态导致领取权益失败的，则视同放弃权益，不再补发。\r\n2.权益说明：权益使用有效期具体以领取页面说明为准。\r\n3.因权益为虚拟电子券产品，一经领取，不可转赠、退换、兑现。\r\n四、合约内容\r\n（一）本套餐合约期12个月，自业务开通当月起计算。\r\n（二）合约到期当月，客户可到当地电信营业厅办理套餐变更或终止业务，如到期时未变更或终止，本套餐将按当前资费自动续展，每次续展12个月，续展次数不限，用户有权办理业务终止。如续展期间遇电信公司营销政策变化或客户已不满足活动办理条件，本套餐自动终止，双方互不承担违约责任。',
                          tips: '',
                          flowPrice: '20',
                          contractPeriod: '本套餐合约期12个月，自业务开通当月起计算。',
                        },
                        headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/top.png',
                        itemId: 100691,
                        listImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/100001/skus/5531/3559/icon.png',
                        marketingSkuTitle: '新标题3',
                        payType: 1,
                        payChannelList: [
                          {
                            cnId: 10042,
                            cnName: '微信支付',
                            createTime: '2022-10-28 10:53:16',
                            dateParams: null,
                            delFlag: false,
                            extendData: {},
                            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/comm/logo/wechat.png',
                            id: 64,
                            searchValue: '',
                            showName: '微信',
                            timeParams: null,
                            updateTime: '2022-10-28 11:03:46',
                          },
                          {
                            cnId: 10005,
                            cnName: '支付宝话费宝',
                            createTime: '2022-10-28 10:53:16',
                            dateParams: null,
                            delFlag: false,
                            extendData: {},
                            iconImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/comm/logo/alipay.png',
                            id: 47,
                            searchValue: '',
                            showName: '支付宝',
                            timeParams: null,
                            updateTime: '2022-10-28 11:03:31',
                          },
                        ],
                        pocTitle: '5折抢10G',
                        pocTitleTwo: '5折抢10G',
                        price: 34,
                        ranks: 30,
                        skuId: 5820,
                        skuImg: '',
                        skuProps: {
                          合约: '合约30',
                        },
                        taobaoProductId: '',
                        taobaoProducts: [],
                        title: '电信-集团10G流量包29元/月升5G，升白金会员（畅享）',
                      },
                    ],
                    title: '电信-集团4升5（融升套入口）',
                  },
                ],
                success: true,
              },
            ],
            status: 1,
          };
        }
      })(),
    },
    msg: '成功',
    success: true,
  };
};
