const moment = require('moment');

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        isActivityPrize: true,
        raffleActivity: {
          acId: 1003,
          acIds: '',
          acName: '支付宝权益专区暑期抽奖',
          acSill: 2,
          acType: 1,
          acTypes: '',
          animateDuring: 2,
          ashBtnImg: '',
          backgroundImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/raffleActivity/raffle_activity/1003/backgroundImg.png',
          basicTurns: 2,
          brightBtnImg: '',
          createTime: '2025-07-04 16:44:34',
          dateParams: null,
          delFlag: false,
          enable: true,
          endTime: '2025-08-31 23:59:11',
          enterIds: '',
          extendData: {},
          id: 4,
          isAsc: '',
          operatorCodes: '',
          orderByColumn: '',
          packageIds: '',
          packageProvinceIds: '',
          raffleRestrict: 'AC:10',
          raffleRestrictKey: '',
          raffleRestrictValue: '',
          remark: '',
          rule: '抽奖活动规则\r\n1.活动时间：2025/7/10-2025/8/31。\r\n2.抽奖参与资格：每个用户活动期间仅限参与10次抽奖，用户通过支付宝-手机充值-权益专区，成功办理任意联通、电信产品可获得1次抽奖机会。\r\n3.奖品清单：迪斯尼门票（成人一日票）、防晒遮阳伞、优酷会员月卡、腾讯会员月卡、淘票票会员月卡优惠券组合、热门会员7折优惠购等，奖品以实际中奖页面发放为准。\r\n4.奖品使用说明：\r\n①迪斯尼门票：奖品为迪斯尼实体礼品卡，您可在暑期（即日起至8月31日前）自行通过实体卡自行绑定出行人及游玩日期。中奖后请及时填写您的收货地址、联系人、联系电话，我们将在5个工作日内给您安排邮递实体礼品卡。\r\n②防晒遮阳伞：中奖后请及时填写您的收货地址、联系人、联系电话，我们将在5个工作日内给您安排邮递实物奖品。\r\n③优酷会员月卡、腾讯会员月卡、淘票票会员月卡优惠券组合：月卡均为30天有效期。中奖后请及时填写您的会员绑定手机号，我们将于1个工作日内给您完成会员充值。\r\n④热门会员7折优惠购：中奖即日起至8月31日前，享受热门视频7折购买资格。中奖后您可以通过奖品弹窗对应点击使用。\r\n5.其他：本活动由上海聚杰网络有限公司承接，若有疑问可联系客服电话4000002967咨询。\r\n\r\n办理送2元话费活动规则\r\n1.活动时间：2025/7/10-2025/8/31。\r\n2.活动规则：活动期间，用户每成功办理1次活动页面中送话费福利的产品，可额外获得2元话费红包。\r\n3.奖品说明：2元话费红包在产品办理成功后自动发放至支付宝卡包，3天有效，请及时在支付宝-手机充值进行充值使用。\r\n4.其他：本活动由上海聚杰网络有限公司承接，若有疑问可联系客服电话4000002967咨询。',
          searchValue: '',
          showPrizeSize: 6,
          startTime: '2025-07-04 00:00:11',
          timeParams: null,
          updateTime: '2025-07-10 11:43:33',
        },
        rafflePrizeList: [
          {
            acId: 1003,
            changeType: 1,
            couponCode: '',
            createTime: '2025-07-04 16:46:58',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:50',
            extendData: {},
            id: 19,
            initStock: 1,
            interfaceId: 0,
            isAsc: '',
            linkUrl: '11',
            orderByColumn: '',
            prId: 10014,
            prName: '迪士尼门票',
            prViceTitle: '成人一日票',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10014/prizeImg.png',
            prizeType: 0,
            rate: 0.01,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:50',
            stock: 1,
            timeParams: null,
            updateTime: '2025-07-04 16:46:58',
          },
          {
            acId: 1003,
            changeType: 1,
            couponCode: '',
            createTime: '2025-07-04 16:48:15',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:01',
            extendData: {},
            id: 20,
            initStock: 10,
            interfaceId: 0,
            isAsc: '',
            linkUrl: '1',
            orderByColumn: '',
            prId: 10015,
            prName: '防晒遮阳伞',
            prViceTitle: '清凉一夏',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10015/prizeImg.png',
            prizeType: 0,
            rate: 0.2,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:01',
            stock: 10,
            timeParams: null,
            updateTime: '2025-07-04 16:48:15',
          },
          {
            acId: 1003,
            changeType: 0,
            couponCode: 'tx030',
            createTime: '2025-07-04 17:06:28',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:07',
            extendData: {},
            id: 21,
            initStock: 50,
            interfaceId: 1000367,
            isAsc: '',
            linkUrl: '',
            orderByColumn: '',
            prId: 10016,
            prName: '腾讯视频',
            prViceTitle: '会员月卡',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10016/prizeImg.png',
            prizeType: 0,
            rate: 0.1,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:07',
            stock: 50,
            timeParams: null,
            updateTime: '2025-07-04 17:06:28',
          },
          {
            acId: 1003,
            changeType: 0,
            couponCode: 'prizePool_bkjupa9e8xwmtanz6m3y16r7maoebpyfezqyl',
            createTime: '2025-07-04 17:07:44',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:36',
            extendData: {},
            id: 22,
            initStock: 50,
            interfaceId: 1000526,
            isAsc: '',
            linkUrl: '',
            orderByColumn: '',
            prId: 10017,
            prName: '淘票票会员',
            prViceTitle: '月卡+8元券',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10017/prizeImg.png',
            prizeType: 0,
            rate: 0.1,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:36',
            stock: 50,
            timeParams: null,
            updateTime: '2025-07-04 17:07:44',
          },
          {
            acId: 1003,
            changeType: 0,
            couponCode: 'yk030',
            createTime: '2025-07-04 17:09:40',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:38',
            extendData: {},
            id: 23,
            initStock: 50,
            interfaceId: 1000367,
            isAsc: '',
            linkUrl: '',
            orderByColumn: '',
            prId: 10018,
            prName: '优酷视频',
            prViceTitle: '会员月卡',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10018/prizeImg.png',
            prizeType: 0,
            rate: 0.1,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:38',
            stock: 50,
            timeParams: null,
            updateTime: '2025-07-04 17:09:40',
          },
          {
            acId: 1003,
            changeType: 1,
            couponCode: '',
            createTime: '2025-07-04 17:11:47',
            dateParams: null,
            delFlag: false,
            enable: true,
            endTime: '2025-08-31 23:59:05',
            extendData: {},
            id: 24,
            initStock: 99999,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeType: 1,
            rate: 99.0,
            remark: '',
            searchValue: '',
            startTime: '2025-07-04 00:00:05',
            stock: 99995,
            timeParams: null,
            updateTime: '2025-07-11 13:59:24',
          },
        ],
        thisRaffleUserPrizeList: [],
        userActivity: null,
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
};
