const moment = require('moment');

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        isActivityPrize: true,
        raffleActivity: null,
        rafflePrizeList: [],
        thisRaffleUserPrizeList: [
          {
            acId: 1003,
            changeType: 1,
            cityId: 0,
            contactName: '',
            contactPhoneNumber: '',
            countyId: 0,
            createTime: '2025-07-11 14:11:00',
            dateParams: null,
            delFlag: false,
            expirationDate: '2025-08-31 23:59:05',
            extendData: {},
            getTime: null,
            id: 12,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            orderId: 0,
            postalAddress: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeStatus: 0,
            provinceId: 0,
            raUserId: 100101,
            searchValue: '',
            timeParams: null,
            updateTime: '2025-07-11 14:11:00',
            useTime: null,
          },
          {
            acId: 1003,
            changeType: 1,
            cityId: 0,
            contactName: '',
            contactPhoneNumber: '',
            countyId: 0,
            createTime: '2025-07-11 13:37:57',
            dateParams: null,
            delFlag: false,
            expirationDate: '2025-08-31 23:59:05',
            extendData: {},
            getTime: null,
            id: 11,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            orderId: 0,
            postalAddress: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeStatus: 0,
            provinceId: 0,
            raUserId: 100101,
            searchValue: '',
            timeParams: null,
            updateTime: '2025-07-11 13:37:57',
            useTime: null,
          },
          {
            acId: 1003,
            changeType: 1,
            cityId: 0,
            contactName: '',
            contactPhoneNumber: '',
            countyId: 0,
            createTime: '2025-07-11 13:37:56',
            dateParams: null,
            delFlag: false,
            expirationDate: '2025-08-31 23:59:05',
            extendData: {},
            getTime: null,
            id: 10,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            orderId: 0,
            postalAddress: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeStatus: 0,
            provinceId: 0,
            raUserId: 100101,
            searchValue: '',
            timeParams: null,
            updateTime: '2025-07-11 13:37:56',
            useTime: null,
          },
          {
            acId: 1003,
            changeType: 1,
            cityId: 0,
            contactName: '',
            contactPhoneNumber: '',
            countyId: 0,
            createTime: '2025-07-11 13:37:56',
            dateParams: null,
            delFlag: false,
            expirationDate: '2025-08-31 23:59:05',
            extendData: {},
            getTime: null,
            id: 9,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            orderId: 0,
            postalAddress: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeStatus: 0,
            provinceId: 0,
            raUserId: 100101,
            searchValue: '',
            timeParams: null,
            updateTime: '2025-07-11 13:37:56',
            useTime: null,
          },
          {
            acId: 1003,
            changeType: 1,
            cityId: 0,
            contactName: '',
            contactPhoneNumber: '',
            countyId: 0,
            createTime: '2025-07-11 13:37:55',
            dateParams: null,
            delFlag: false,
            expirationDate: '2025-08-31 23:59:05',
            extendData: {},
            getTime: null,
            id: 8,
            interfaceId: 0,
            isAsc: '',
            linkUrl: 'https://benefit.jujienet.com/benefit/index/910522',
            orderByColumn: '',
            orderId: 0,
            postalAddress: '',
            prId: 10019,
            prName: '爱优腾芒',
            prViceTitle: '会员7折购',
            prizeImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/rafflePrize/raffle_prize/10019/prizeImg.png',
            prizeStatus: 0,
            provinceId: 0,
            raUserId: 100101,
            searchValue: '',
            timeParams: null,
            updateTime: '2025-07-11 13:37:55',
            useTime: null,
          },
        ],
        userActivity: {
          acId: 1003,
          createTime: '2025-07-11 13:32:15',
          dateParams: null,
          dayRequest: true,
          delFlag: false,
          extendData: {},
          id: 30,
          isAsc: '',
          lastTime: '2025-07-11 14:09:58',
          orderByColumn: '',
          raUserId: 100101,
          searchValue: '',
          surplus: 5,
          timeParams: null,
          totalSurplus: 10,
          updateTime: '2025-07-11 14:09:58',
        },
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
};
