const Mock = require('mockjs');

module.exports = (req) =>
  Mock.mock({
    code: 200,
    data: [
      {
        allCount: 1,
        cycleOrderRecordId: '',
        detailButton: { orderId: '', style: 1, title: '去领取', type: 6 },
        detailImgs: null,
        frontExtInfo: { equityTitle: '标题', equityTips: 'tips' },
        groupType: null,
        icon: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/9507/12821/iconimg.png',
        itemId: 102366,
        linkUrl: 'chooseN',
        list: null,
        orderId: '202212071008381283',
        packageItemGroupId: null,
        packageItemTitle: '优酷随心看',
        subTitle: '',
        takeMode: 1,
        takenCount: null,
        title: '优酷随心看（首月）',
        tradeId: '202212072008116842',
        underButton: '',
      },
      {
        allCount: 1260,
        cycleOrderRecordId: '',
        detailButton: { orderId: '', style: 1, title: '去领取', type: 6 },
        detailImgs: null,
        frontExtInfo: { equityTitle: '标题', equityTips: 'tips' },
        groupType: null,
        icon: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/9508/12822/iconimg.png',
        itemId: 102367,
        linkUrl: 'equityCommunication',
        list: null,
        orderId: '202212071008381284',
        packageItemGroupId: null,
        packageItemTitle: '优酷随心看',
        subTitle: '',
        takeMode: 1,
        takenCount: null,
        title: '优酷随心看（次月）',
        tradeId: '202212072008116842',
        underButton: '',
      },
      // {
      //   allCount: 36,
      //   cycleOrderRecordId: '',
      //   detailButton: { orderId: '', style: 2, title: '已发放', type: 5 },
      //   detailImgs: null,
      //   groupType: null,
      //   icon: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/9510/12836/iconimg.png',
      //   itemId: 102369,
      //   linkUrl: '#',
      //   list: null,
      //   orderId: '202212071008381285',
      //   packageItemGroupId: null,
      //   packageItemTitle: '3元话费红包',
      //   subTitle: '',
      //   takeMode: 2,
      //   takenCount: null,
      //   title: '联通-全国3元话费红包-优酷',
      //   tradeId: '202212072008116842',
      //   underButton: '',
      // },
      // {
      //   allCount: 1,
      //   cycleOrderRecordId: '',
      //   detailButton: { orderId: '', style: 2, title: '领取中', type: 4 },
      //   detailImgs: null,
      //   groupType: null,
      //   icon: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/9509/12838/iconimg.png',
      //   itemId: 102368,
      //   linkUrl: '#',
      //   list: null,
      //   orderId: '202212071008381286',
      //   packageItemGroupId: null,
      //   packageItemTitle: '2元话费红包',
      //   subTitle: '',
      //   takeMode: 2,
      //   takenCount: null,
      //   title: '联通-全国2元话费红包-优酷',
      //   tradeId: '202212072008116842',
      //   underButton: '',
      // },
    ],
    msg: '成功',
  });
