const URI = '/benefit/api/';

module.exports = [
  {
    name: 'getToken',
    method: 'post',
    url: `${URI}getToken`,
    response: require('./getToken'),
    description: '获取token',
    delay: 0,
  },
  {
    name: 'getMarketingInfo',
    method: 'post',
    url: `${URI}getMarketingInfo`,
    response: require('./getMarketingInfo'),
    description: '获取营销配置',
    delay: 1000,
  },
  {
    name: 'getPackages',
    method: 'post',
    url: `${URI}getPackages`,
    response: require('./getPackages'),
    description: '鉴权接口',
    delay: 0,
  },
  {
    name: 'sendSkuSmsCode',
    method: 'post',
    url: `${URI}sendSkuSmsCode`,
    response: require('./sendSkuSmsCode'),
    description: '发送验证码',
    delay: 0,
  },
  {
    name: 'createTrade',
    method: 'post',
    url: `${URI}createTrade`,
    response: require('./createTrade'),
    description: '创单',
    delay: 0,
  },
  {
    name: 'getPayInfo',
    method: 'post',
    url: `${URI}getPayInfo`,
    response: require('./getPayInfo'),
    description: '获取支付信息',
    delay: 0,
  },
  {
    name: 'createTaobaoOrder',
    method: 'post',
    url: `${URI}createTaobaoOrder`,
    response: require('./createTaobaoOrder'),
    description: '创建淘宝单子',
    delay: 0,
  },
  {
    name: 'getConfig',
    method: 'post',
    url: `${URI}getConfig`,
    response: require('./getConfig'),
    description: '获取优酷一分钱拉起iframe的配置',
    delay: 0,
  },
  {
    name: 'getTradeList',
    method: 'post',
    url: `${URI}getTradeList`,
    response: require('./getTradeList'),
    description: '订单列表',
    delay: 0,
  },
  {
    name: 'getTradeDetail',
    method: 'post',
    url: `${URI}getTradeDetail`,
    response: require('./getTradeDetail'),
    description: '订单详情',
    delay: 0,
  },
  {
    name: 'receiveCycleRights',
    method: 'post',
    url: `${URI}receiveCycleRights`,
    response: require('./receiveCycleRights'),
    description: '领取权益-创建权益订单',
    delay: 0,
  },
  {
    name: 'getUserRights',
    method: 'post',
    url: `${URI}getUserRights`,
    response: require('./getUserRights'),
    description: '获取我的权益列表',
    delay: 0,
  },
  {
    name: 'getCycleOrderStatus',
    method: 'post',
    url: `${URI}getCycleOrderStatus`,
    response: require('./getCycleOrderStatus'),
    description: '领取权益-查询权益领取状态',
    delay: 0,
  },
  {
    name: 'decryptUserInfo',
    method: 'post',
    url: `${URI}decryptUserInfo`,
    response: require('./decryptUserInfo'),
    description: '获取手机号授权',
    delay: 0,
  },
  {
    name: 'getCategoryPackages',
    method: 'post',
    url: `${URI}getCategoryPackages`,
    response: require('./getCategoryPackages'),
    description: '主推/更多产品鉴权接口',
    delay: 0,
  },
  {
    name: 'getCategoryMarketingInfo',
    method: 'post',
    url: `${URI}getCategoryMarketingInfo`,
    response: require('./getCategoryMarketingInfo'),
    description: '主推/更多产品营销配置接口',
    delay: 0,
  },
  {
    name: 'strangeInterface',
    method: 'post',
    url: `${URI}strangeInterface`,
    response: require('./strangeInterface'),
    description: '埋点接口',
    delay: 0,
  },
  {
    name: 'getAgreement',
    method: 'post',
    url: `${URI}getAgreement`,
    response: require('./getAgreement'),
    description: '获取协议接口',
    delay: 0,
  },
  {
    name: 'getAdList',
    method: 'post',
    url: `${URI}getAdList`,
    response: require('./getAdList'),
    description: '获取广告接口',
    delay: 0,
  },
  {
    name: 'getUserTradeIds',
    method: 'post',
    url: `${URI}getUserTradeIds`,
    response: require('./getUserTradeIds'),
    description: '根据packageId查单子',
    delay: 0,
  },
  {
    name: 'getProductMarketingInfo',
    method: 'post',
    url: `${URI}getProductMarketingInfo`,
    response: require('./getProductMarketingInfo'),
    description: '',
    delay: 0,
  },
  {
    name: 'getProduct',
    method: 'post',
    url: `${URI}getProduct`,
    response: require('./getProduct'),
    description: '',
    delay: 0,
  },
  {
    name: 'getTradeStatus',
    method: 'post',
    url: `${URI}getTradeStatus`,
    response: require('./getTradeStatus'),
    description: '',
    delay: 0,
  },
  {
    name: 'getLotteryResult',
    method: 'post',
    url: `${URI}getLotteryResult`,
    response: require('./getLotteryResult'),
    description: '',
    delay: 0,
  },
];
