const moment = require('moment');
const Mock = require('mockjs');
const Random = Mock.Random;

module.exports = (req) => {
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        marketingSkuTip: {
          cancelButtonText: '取消办理',
          cancelButtonType: 0,
          confirmButtonSize: 100,
          confirmButtonText: '确认订购',
          confirmButtonType: 0,
          createTime: '2025-10-21 10:23:27',
          dateParams: null,
          delFlag: false,
          ejectTiming: 1,
          enterId: 0,
          extendData: {},
          id: 427,
          isAsc: '',
          itemId: 105708,
          marketingId: 101070,
          marketingSkuTipType: 'MARKETING_SKU_TIP',
          operUserId: 174,
          orderByColumn: '',
          packageId: 1005743,
          searchValue: '',
          showCloseButton: 1,
          showPhone: 1,
          showSecondConfirm: false,
          showSecondConfirmText: '',
          showServicePhone: 1,
          skuId: 13305,
          timeParams: null,
          tipBackground: '',
          tipDetailPic: '',
          tipStatus: true,
          tipText:
            '<h4><span style="color: rgb(89, 89, 89); font-size: 13px;">产品名称</span><span style="color: rgb(89, 89, 89);">：</span><span style="color: rgb(89, 89, 89); font-size: 13px;">5G权益包15元少儿读书会员(新疆)</span></h4><h4><span style="color: rgb(89, 89, 89); font-size: 13px;">产品说明</span><span style="color: rgb(89, 89, 89);">：</span><span style="color: rgb(89, 89, 89); font-size: 13px;">15元/月，每月享受少儿优选权益、2T云盘会员</span></h4><h4><span style="color: rgb(89, 89, 89); font-size: 13px;">生效及订购说明：办理成功，立即生效，包月产品，如不退订，每月收取费用</span></h4>',
          tipTitle: '5G权益包15元少儿读书会员(新疆)',
          tipType: 1,
          titleColor: '#FF7D00',
          topIcon: '',
          updateTime: '2025-10-21 11:28:10',
        },
        pageUrl: '/proxyInvestShowVerify',
        pathIndex: req.body.pathIndex || 1,
        phoneNumber: '15609918084',
        showPhoneText: true,
        skuReportItem: {
          agreementName: '',
          agreementNameSuffix: '',
          agreementShowLimit: 0,
          buttonImg: '',
          channelBrand: '',
          defaultChoose: 1,
          detailImgs: [],
          headerImg: '',
          iconImg: '',
          listImg: '',
          logoImg: '',
          pluginBackgroundImg: '',
          pluginProductImg: '',
          skuUserAgreements: [],
          templateType: 0,
        },
        skuTitle: '新疆联通特惠办理',
        smsCode: '620696',
        supplierServicePhone: '4000002967',
        tradeCreateTime: '2025-10-21 10:45:45',
        tradeId: '202510212053550394',
      },
    },
    msg: '成功',
    noOrderPlace: false,
    success: true,
  };
  return {
    code: 200,
    data: {
      dataList: [],
      dataMap: {
        pageUrl: '/mobileOppo',
        phoneNumber: '13812344321',
        skuReportItem: {
          buttonImg:
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/10051/101081/buttonImg.png',
          detailImgs: [
            'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/10051/101081/ruleImg.png',
          ],
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/marketing/100001/skus/10051/101081/headImg.png',
          headerImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/upload/temporary/100001/skus/12306/23106/headImg.png',
          iconImg: '',
          listImg: 'https://img.temp.im/750x780/ffad66/ffffff',
          logoImg: '',
          pluginBackgroundImg: '',
          pluginProductImg: '',
        },
        smsCode: '123456',
        tradeCreateTime: '2024-12-27 16:12:53',
      },
    },
    msg: '成功',
    success: true,
  };
};
