const Mock = require('mockjs');
module.exports = (req) =>
  Mock.mock({
    code: 1000,
    msg: '响应信息:调用成功',
    response: {
      status: null,
      msg: '',
      memberTaskList: [
        {
          taskId: 100001,
          title: '关注VV会员生活号',
          subTitle: '第一时间接收最新资讯',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100002,
          title: '收藏VV会员小程序',
          subTitle: '可在我的收藏中快速领取权益',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100003,
          title: '将VV会员卡加入卡包',
          subTitle: '可在卡包中快速领取权益',
          starNum: 2,
          status: 2,
          msg: '任务完成',
        },
        {
          taskId: 100004,
          title: '订阅活动开始提醒',
          subTitle: '接收会员各类活动消息',
          starNum: 2,
          status: 2,
          msg: '任务完成',
        },
        {
          taskId: 100005,
          title: '订阅会员状态提醒',
          subTitle: '接收会员状态提醒',
          starNum: 2,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100006,
          title: '订阅VV会员权益领取提醒',
          subTitle: '权益领取不再错过',
          starNum: 2,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100007,
          title: '领2GB流量权益',
          subTitle: '随领随用 立即到账',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100008,
          title: '领饿了么红包权益',
          subTitle: '最高可享66元红包',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100009,
          title: '领7折起猫超快消品权益',
          subTitle: '7折享生活好物',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100010,
          title: '领优酷月卡8折权益',
          subTitle: '8折享优酷视频月会员',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100011,
          title: '领取10包抽纸权益',
          subTitle: '仅需付邮费即可领10包抽纸',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100012,
          title: '浏览幸运开盲盒',
          subTitle: '最高开出iPhone13',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100013,
          title: '浏览免费领加湿器',
          subTitle: '仅需付邮费即可领加湿',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
        {
          taskId: 100014,
          title: '浏览免费领手机支架',
          subTitle: '仅需付邮费即可领手机支架',
          starNum: 1,
          status: 1,
          msg: '未完成',
        },
      ],
      userStarNum: 4,
      alreadyRenewalTimes: 0,
      allowRenewalTimes: 1,
    },
  });
