module.exports = (req) => ({
  code: 1000,
  msg: '响应信息:调用成功',
  response: {
    status: (() => {
      if (req.body.phoneNumberSign) {
        return 1;
      }
      return 1;
    })(),
    msg: '有商品',
    phoneNumber: '15990158853',
    packages: [
      {
        title: '联通VV会员尊享版',
        packageId: 100001,
        operatorCode: 1,
        templateId: 100001,
        ranks: 1,
        params: {
          agreements: [
            {
              name: '联通在网协议',
              src: 'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/commondity/commondity_20210624105142_product_934a4997.jpg',
            },
          ],
          agreementName: '协议名称',
          headImg: 'https://alipic.lanhuapp.com/xdcf81c139-de4f-4082-b00e-1cf5d6c30413',
          memberRule:
            'https://jj-img2019.oss-cn-hangzhou.aliyuncs.com/commondity/commondity_20210624105142_product_934a4997.jpg',
          navigationBarTitle: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/static/navigationLogoVip.png',
          submitBtnImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/static/submitBtn1.png',
          submitMarketingImg: 'https://alipic.lanhuapp.com/xdb9551228-3ee1-41d2-b69b-b32e7f4eeb9a',
        },
        groupTagList: [
          {
            groupTagId: 100001,
            name: '订购的主商品(隐藏)',
            ranks: 1,
            params: {},
            itemGroupList: [
              {
                groupId: 100001,
                groupName: '订购主商品(隐藏)',
                privilegeType: null,
                groupType: 1,
                groupSort: 1,
                groupTagId: 100001,
                hide: true,
                equityValue: '',
                itemList: [
                  {
                    itemId: 100001,
                    title: '联通VV会员尊享版',
                    showTitle: '联通VV会员尊享版',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 1,
                    cycleType: null,
                    autoCycleOrder: 1,
                    totalCycleNum: 1,
                    takeMode: 1,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100001,
                        itemId: 100001,
                        title: '联通VV会员尊享版',
                        goodsId: 'TEST001',
                        ranks: 1,
                        linkUrl: null,
                        params: {},
                        detailButton: null,
                      },
                    ],
                  },
                ],
                params: {},
              },
            ],
          },
          {
            groupTagId: 100002,
            name: '通信权益',
            ranks: 2,
            params: {
              detailHeadImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailGroupTag0.png',
              headImg: 'https://alipic.lanhuapp.com/xdb108e0b9-2b7f-4c6f-beae-1efd5c555055',
            },
            itemGroupList: [
              {
                groupId: 100002,
                groupName: '5G流量日包',
                privilegeType: null,
                groupType: 3,
                groupSort: 2,
                groupTagId: 100002,
                hide: false,
                equityValue: '',
                itemList: [
                  {
                    itemId: 100002,
                    title: '联通3GB流量日包',
                    showTitle: '联通3GB流量日包',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 1,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100002,
                        itemId: 100002,
                        title: '联通3GB流量日包',
                        goodsId: 'TEST001_1',
                        ranks: 1,
                        linkUrl: null,
                        params: {
                          flowBalance: 3,
                          skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailSku0.png',
                        },
                        detailButton: null,
                      },
                    ],
                  },
                  {
                    itemId: 100003,
                    title: '联通1GB流量日包(1)',
                    showTitle: '联通1GB流量日包(1)',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 2,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100003,
                        itemId: 100003,
                        title: '联通1GB流量日包',
                        goodsId: 'TEST001_2',
                        ranks: 1,
                        linkUrl: null,
                        params: {
                          flowBalance: 1,
                          skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailSku1.png',
                        },
                        detailButton: null,
                      },
                    ],
                  },
                  {
                    itemId: 100004,
                    title: '联通1GB流量日包(2)',
                    showTitle: '联通1GB流量日包(2)',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 3,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100004,
                        itemId: 100004,
                        title: '联通1GB流量日包',
                        goodsId: 'TEST001_3',
                        ranks: 1,
                        linkUrl: null,
                        params: {
                          flowBalance: 1,
                          skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailSku2.png',
                        },
                        detailButton: null,
                      },
                    ],
                  },
                ],
                params: {
                  detailHeadImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailItemTag0.png',
                  listImg: 'https://alipic.lanhuapp.com/xdfa777cd9-be21-41ab-8423-4f5a9007ae70',
                },
              },
              {
                groupId: 100003,
                groupName: '充值98折',
                privilegeType: null,
                groupType: 2,
                groupSort: 3,
                groupTagId: 100002,
                hide: false,
                equityValue: '',
                itemList: [
                  {
                    itemId: 100005,
                    title: '充30元送0.6元',
                    showTitle: '充30元送0.6元',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 1,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100005,
                        itemId: 100005,
                        title: '充30元送0.6元',
                        goodsId: 'TEST001_4',
                        ranks: 1,
                        linkUrl: null,
                        params: { skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/test/apsu/hf/1.png' },
                        detailButton: null,
                      },
                    ],
                  },
                  {
                    itemId: 100006,
                    title: '充50元送1元',
                    showTitle: '充50元送1元',
                    subtitle: '',
                    operatorCode: 1,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 2,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100006,
                        itemId: 100006,
                        title: '充50元送1元',
                        goodsId: 'TEST001_5',
                        ranks: 1,
                        linkUrl: null,
                        params: { skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/test/apsu/hf/2.png' },
                        detailButton: null,
                      },
                    ],
                  },
                ],
                params: { detailHeadImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailItemTag1.png' },
              },
            ],
          },
          {
            groupTagId: 100003,
            name: '生活权益',
            ranks: 3,
            params: {
              detailHeadImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/vvip/mock/detailGroupTag1.png',
              headImg: 'https://alipic.lanhuapp.com/xd365f1627-dd99-4490-a790-e8863869b112',
            },
            itemGroupList: [
              {
                groupId: 100004,
                groupName: '生活权益',
                privilegeType: null,
                groupType: 3,
                groupSort: 4,
                groupTagId: 100003,
                hide: false,
                equityValue: '',
                itemList: [
                  {
                    itemId: 100007,
                    title: '最高3元缴费红包',
                    showTitle: '最高3元缴费红包',
                    subtitle: '',
                    operatorCode: 0,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 1,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100007,
                        itemId: 100007,
                        title: '最高3元缴费红包',
                        goodsId: 'TEST002',
                        ranks: 1,
                        linkUrl: null,
                        params: { skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/test/apsu/2.png' },
                        detailButton: null,
                      },
                    ],
                  },
                  {
                    itemId: 100008,
                    title: '最高5元加油红包',
                    showTitle: '最高5元加油红包',
                    subtitle: '',
                    operatorCode: 0,
                    isValidatecode: false,
                    onlineCycle: '',
                    showSort: 2,
                    cycleType: null,
                    autoCycleOrder: 0,
                    totalCycleNum: 6,
                    takeMode: 2,
                    linkUrl: null,
                    params: {},
                    skuList: [
                      {
                        skuId: 100008,
                        itemId: 100008,
                        title: '最高5元加油红包',
                        goodsId: 'TEST003',
                        ranks: 1,
                        linkUrl: null,
                        params: { skuImg: 'https://chaac.oss-cn-hangzhou.aliyuncs.com/test/apsu/3.png' },
                        detailButton: null,
                      },
                    ],
                  },
                ],
                params: {},
              },
            ],
          },
        ],
      },
    ],
  },
});
